// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.
//
// Unit tests for the generated request-model Validate methods: each negative
// case mutates exactly one field on a known-valid baseline. Pure Go — no
// build tag, no infrastructure.

package rebacrelationshipsbridge

import (
	"strings"
	"testing"
)

func testPtr[T any](v T) *T { return &v }

func validCreateRebacRelationshipRequest() CreateRebacRelationshipRequest {
	return CreateRebacRelationshipRequest{
		ResourceType: "ok",
		ResourceID:   "ok",
		Relation:     "ok",
		SubjectType:  "ok",
		SubjectID:    "ok",
	}
}

func TestCreateRebacRelationshipRequestValidate(t *testing.T) {
	t.Run("valid request passes", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		if err := r.Validate(); err != nil {
			t.Fatalf("valid request: unexpected error: %v", err)
		}
	})
	t.Run("missing required resource_type", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.ResourceType = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("resource_type rejects value over max length", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.ResourceType = strings.Repeat("a", 65)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("missing required resource_id", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.ResourceID = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("resource_id rejects value over max length", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.ResourceID = strings.Repeat("a", 256)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("missing required relation", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.Relation = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("relation rejects value over max length", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.Relation = strings.Repeat("a", 65)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("missing required subject_type", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.SubjectType = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("subject_type rejects value over max length", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.SubjectType = strings.Repeat("a", 65)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("missing required subject_id", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.SubjectID = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("subject_id rejects value over max length", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.SubjectID = strings.Repeat("a", 256)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("subject_relation rejects value over max length", func(t *testing.T) {
		r := validCreateRebacRelationshipRequest()
		r.SubjectRelation = testPtr(strings.Repeat("a", 65))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
}

func TestUpdateRebacRelationshipRequestValidate(t *testing.T) {
	t.Run("empty update passes", func(t *testing.T) {
		r := UpdateRebacRelationshipRequest{}
		if err := r.Validate(); err != nil {
			t.Fatalf("empty update: unexpected error: %v", err)
		}
	})
	t.Run("update resource_type rejects value over max length", func(t *testing.T) {
		r := UpdateRebacRelationshipRequest{}
		r.ResourceType = testPtr(strings.Repeat("a", 65))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update resource_id rejects value over max length", func(t *testing.T) {
		r := UpdateRebacRelationshipRequest{}
		r.ResourceID = testPtr(strings.Repeat("a", 256))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update relation rejects value over max length", func(t *testing.T) {
		r := UpdateRebacRelationshipRequest{}
		r.Relation = testPtr(strings.Repeat("a", 65))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update subject_type rejects value over max length", func(t *testing.T) {
		r := UpdateRebacRelationshipRequest{}
		r.SubjectType = testPtr(strings.Repeat("a", 65))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update subject_id rejects value over max length", func(t *testing.T) {
		r := UpdateRebacRelationshipRequest{}
		r.SubjectID = testPtr(strings.Repeat("a", 256))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update subject_relation rejects value over max length", func(t *testing.T) {
		r := UpdateRebacRelationshipRequest{}
		r.SubjectRelation = testPtr(strings.Repeat("a", 65))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
}
