// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.

package invitationspgx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
	"github.com/gopernicus/gopernicus/sdk/fop"

	"github.com/gopernicus/gopernicus/core/repositories/rebac/invitations"
)

// Store implements invitations.Storer using PostgreSQL via pgx.
type Store struct {
	log *slog.Logger
	db  pgxdb.Querier
}

// NewStore creates a new invitations store backed by the given Querier.
// Querier is satisfied by both *pgxpool.Pool and pgx.Tx, enabling
// transaction composition.
func NewStore(log *slog.Logger, db pgxdb.Querier) *Store {
	return &Store{log: log, db: db}
}

// compile-time interface check (Storer is defined in repository.go)
var _ invitations.Storer = (*Store)(nil)

// ─── error mapping ────────────────────────────────────────────────────────────

func (s *Store) mapError(err error) error {
	dbErr := pgxdb.HandlePgError(err)
	switch {
	case errors.Is(dbErr, pgxdb.ErrDBDuplicatedEntry):
		return invitations.ErrInvitationAlreadyExists
	case errors.Is(dbErr, pgxdb.ErrDBForeignKeyViolation):
		return invitations.ErrInvitationInvalidReference
	case errors.Is(dbErr, pgxdb.ErrDBCheckViolation),
		errors.Is(dbErr, pgxdb.ErrDBNotNullViolation):
		return invitations.ErrInvitationInvalidInput
	default:
		return dbErr
	}
}

// ─── methods ──────────────────────────────────────────────────────────────────

func (s *Store) List(ctx context.Context, filter invitations.FilterList, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]invitations.Invitation, error) {
	data := pgx.NamedArgs{}

	baseSQL := `SELECT *
FROM public.invitations
WHERE $conditions AND $search`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListConditionsFilter(filter, data))
	baseSQL = replaceFilterPlaceholder(baseSQL, "$search", generatedApplyListSearchFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := invitations.OrderByFields[orderBy.Field]
	if !ok {
		of = invitations.OrderByFields[invitations.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "invitation_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "invitation_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[invitations.Invitation])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) Get(ctx context.Context, invitationID string) (invitations.Invitation, error) {
	query := `SELECT invitation_id, resource_type, resource_id, relation, identifier, identifier_type, resolved_subject_id, invited_by, token_hash, auto_accept, invitation_status, expires_at, accepted_at, record_state, created_at, updated_at, redirect_url
FROM public.invitations
WHERE invitation_id = @invitation_id`

	args := pgx.NamedArgs{
		"invitation_id": invitationID,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return invitations.Invitation{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[invitations.Invitation])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return invitations.Invitation{}, invitations.ErrInvitationNotFound
		}
		return invitations.Invitation{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) Create(ctx context.Context, input invitations.CreateInvitation) (invitations.Invitation, error) {
	now := time.Now().UTC()
	query := `INSERT INTO public.invitations (invitation_id, resource_type, resource_id, relation, identifier, identifier_type, resolved_subject_id, invited_by, token_hash, auto_accept, invitation_status, expires_at, accepted_at, record_state, redirect_url, created_at, updated_at)
		VALUES (@invitation_id, @resource_type, @resource_id, @relation, @identifier, @identifier_type, @resolved_subject_id, @invited_by, @token_hash, @auto_accept, @invitation_status, @expires_at, @accepted_at, @record_state, @redirect_url, @_created_at, @_updated_at)
		RETURNING invitation_id, resource_type, resource_id, relation, identifier, identifier_type, resolved_subject_id, invited_by, token_hash, auto_accept, invitation_status, expires_at, accepted_at, record_state, created_at, updated_at, redirect_url`

	args := pgx.NamedArgs{
		"invitation_id":       input.InvitationID,
		"resource_type":       input.ResourceType,
		"resource_id":         input.ResourceID,
		"relation":            input.Relation,
		"identifier":          input.Identifier,
		"identifier_type":     input.IdentifierType,
		"resolved_subject_id": input.ResolvedSubjectID,
		"invited_by":          input.InvitedBy,
		"token_hash":          input.TokenHash,
		"auto_accept":         input.AutoAccept,
		"invitation_status":   input.InvitationStatus,
		"expires_at":          input.ExpiresAt,
		"accepted_at":         input.AcceptedAt,
		"record_state":        input.RecordState,
		"redirect_url":        input.RedirectURL,
		"_created_at":         now,
		"_updated_at":         now,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return invitations.Invitation{}, s.mapError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[invitations.Invitation])
	if err != nil {
		return invitations.Invitation{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Update(ctx context.Context, invitationID string, input invitations.UpdateInvitation) (invitations.Invitation, error) {
	buf := bytes.NewBufferString("UPDATE public.invitations SET ")
	args := pgx.NamedArgs{
		"invitation_id": invitationID,
	}
	var setClauses []string
	if input.ResourceType != nil {
		setClauses = append(setClauses, "resource_type = @resource_type")
		args["resource_type"] = *input.ResourceType
	}
	if input.ResourceID != nil {
		setClauses = append(setClauses, "resource_id = @resource_id")
		args["resource_id"] = *input.ResourceID
	}
	if input.Relation != nil {
		setClauses = append(setClauses, "relation = @relation")
		args["relation"] = *input.Relation
	}
	if input.Identifier != nil {
		setClauses = append(setClauses, "identifier = @identifier")
		args["identifier"] = *input.Identifier
	}
	if input.IdentifierType != nil {
		setClauses = append(setClauses, "identifier_type = @identifier_type")
		args["identifier_type"] = *input.IdentifierType
	}
	if input.ResolvedSubjectID != nil {
		setClauses = append(setClauses, "resolved_subject_id = @resolved_subject_id")
		args["resolved_subject_id"] = *input.ResolvedSubjectID
	}
	if input.InvitedBy != nil {
		setClauses = append(setClauses, "invited_by = @invited_by")
		args["invited_by"] = *input.InvitedBy
	}
	if input.TokenHash != nil {
		setClauses = append(setClauses, "token_hash = @token_hash")
		args["token_hash"] = *input.TokenHash
	}
	if input.AutoAccept != nil {
		setClauses = append(setClauses, "auto_accept = @auto_accept")
		args["auto_accept"] = *input.AutoAccept
	}
	if input.InvitationStatus != nil {
		setClauses = append(setClauses, "invitation_status = @invitation_status")
		args["invitation_status"] = *input.InvitationStatus
	}
	if input.ExpiresAt != nil {
		setClauses = append(setClauses, "expires_at = @expires_at")
		args["expires_at"] = *input.ExpiresAt
	}
	if input.AcceptedAt != nil {
		setClauses = append(setClauses, "accepted_at = @accepted_at")
		args["accepted_at"] = *input.AcceptedAt
	}
	if input.UpdatedAt != nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = *input.UpdatedAt
	}
	if input.RedirectURL != nil {
		setClauses = append(setClauses, "redirect_url = @redirect_url")
		args["redirect_url"] = *input.RedirectURL
	}

	// Auto-set updated_at if not explicitly provided.
	if input.UpdatedAt == nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = time.Now().UTC()
	}

	if len(setClauses) == 0 {
		return invitations.Invitation{}, fmt.Errorf("no fields to update")
	}

	buf.WriteString(strings.Join(setClauses, ", "))
	buf.WriteString(" WHERE invitation_id = @invitation_id")
	buf.WriteString(" RETURNING invitation_id, resource_type, resource_id, relation, identifier, identifier_type, resolved_subject_id, invited_by, token_hash, auto_accept, invitation_status, expires_at, accepted_at, record_state, created_at, updated_at, redirect_url")

	rows, err := s.db.Query(ctx, buf.String(), args)
	if err != nil {
		return invitations.Invitation{}, s.mapError(err)
	}
	defer rows.Close()
	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[invitations.Invitation])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return invitations.Invitation{}, invitations.ErrInvitationNotFound
		}
		return invitations.Invitation{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) SoftDelete(ctx context.Context, invitationID string) error {
	args := pgx.NamedArgs{
		"invitation_id": invitationID,
	}

	query := `UPDATE public.invitations
SET record_state = 'deleted'
WHERE invitation_id = @invitation_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return invitations.ErrInvitationNotFound
	}

	return nil
}

func (s *Store) Archive(ctx context.Context, invitationID string) error {
	args := pgx.NamedArgs{
		"invitation_id": invitationID,
	}

	query := `UPDATE public.invitations
SET record_state = 'archived'
WHERE invitation_id = @invitation_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return invitations.ErrInvitationNotFound
	}

	return nil
}

func (s *Store) Restore(ctx context.Context, invitationID string) error {
	args := pgx.NamedArgs{
		"invitation_id": invitationID,
	}

	query := `UPDATE public.invitations
SET record_state = 'active'
WHERE invitation_id = @invitation_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return invitations.ErrInvitationNotFound
	}

	return nil
}

func (s *Store) Delete(ctx context.Context, invitationID string) error {
	args := pgx.NamedArgs{
		"invitation_id": invitationID,
	}

	query := `DELETE FROM public.invitations
WHERE invitation_id = @invitation_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return invitations.ErrInvitationNotFound
	}

	return nil
}

func (s *Store) GetByToken(ctx context.Context, tokenHash string, now time.Time) (invitations.Invitation, error) {
	query := `SELECT invitation_id, resource_type, resource_id, relation, identifier, identifier_type, resolved_subject_id, invited_by, token_hash, auto_accept, invitation_status, expires_at, accepted_at, record_state, created_at, updated_at, redirect_url
FROM public.invitations
WHERE token_hash = @token_hash
AND invitation_status = 'pending'
AND expires_at > @now`

	args := pgx.NamedArgs{
		"token_hash": tokenHash,
		"now":        now,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return invitations.Invitation{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[invitations.Invitation])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return invitations.Invitation{}, invitations.ErrInvitationNotFound
		}
		return invitations.Invitation{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) ListByResource(ctx context.Context, filter invitations.FilterListByResource, resourceType string, resourceID string, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]invitations.Invitation, error) {
	data := pgx.NamedArgs{
		"resource_type": resourceType,
		"resource_id":   resourceID,
	}

	baseSQL := `SELECT *
FROM public.invitations
WHERE resource_type = @resource_type
AND resource_id = @resource_id
AND $conditions AND $search`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListByResourceConditionsFilter(filter, data))
	baseSQL = replaceFilterPlaceholder(baseSQL, "$search", generatedApplyListByResourceSearchFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := invitations.OrderByFields[orderBy.Field]
	if !ok {
		of = invitations.OrderByFields[invitations.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "invitation_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "invitation_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[invitations.Invitation])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) ListBySubject(ctx context.Context, filter invitations.FilterListBySubject, resolvedSubjectID string, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]invitations.Invitation, error) {
	data := pgx.NamedArgs{
		"resolved_subject_id": resolvedSubjectID,
	}

	baseSQL := `SELECT *
FROM public.invitations
WHERE resolved_subject_id = @resolved_subject_id
AND $conditions`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListBySubjectConditionsFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := invitations.OrderByFields[orderBy.Field]
	if !ok {
		of = invitations.OrderByFields[invitations.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "invitation_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "invitation_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[invitations.Invitation])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) ListByIdentifier(ctx context.Context, filter invitations.FilterListByIdentifier, identifier string, identifierType string, now time.Time, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]invitations.Invitation, error) {
	data := pgx.NamedArgs{
		"identifier":      identifier,
		"identifier_type": identifierType,
		"now":             now,
	}

	baseSQL := `SELECT *
FROM public.invitations
WHERE identifier = @identifier
AND identifier_type = @identifier_type
AND expires_at > @now
AND $conditions`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListByIdentifierConditionsFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := invitations.OrderByFields[orderBy.Field]
	if !ok {
		of = invitations.OrderByFields[invitations.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "invitation_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "invitation_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[invitations.Invitation])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

// ─── filter placeholder substitution ─────────────────────────────────────────

func replaceFilterPlaceholder(sql, placeholder, fragment string) string {
	if fragment == "" {
		fragment = "TRUE"
	}
	return strings.Replace(sql, placeholder, "("+fragment+")", 1)
}

// ─── per-function named filters ──────────────────────────────────────────────

func generatedApplyListConditionsFilter(filter invitations.FilterList, data pgx.NamedArgs) string {
	var conditions []string

	// Auto-default record_state to 'active'.
	if filter.RecordState == nil {
		conditions = append(conditions, "record_state = @record_state")
		data["record_state"] = "active"
	} else if strings.Contains(*filter.RecordState, ",") {
		states := strings.Split(*filter.RecordState, ",")
		for i := range states {
			states[i] = strings.TrimSpace(states[i])
		}
		conditions = append(conditions, "record_state = ANY(@record_states)")
		data["record_states"] = states
	} else {
		conditions = append(conditions, "record_state = @record_state")
		data["record_state"] = *filter.RecordState
	}
	if filter.InvitationID != nil {
		conditions = append(conditions, "invitation_id = @filter_invitation_id")
		data["filter_invitation_id"] = *filter.InvitationID
	}
	if filter.ResourceType != nil {
		conditions = append(conditions, "resource_type = @filter_resource_type")
		data["filter_resource_type"] = *filter.ResourceType
	}
	if filter.ResourceID != nil {
		conditions = append(conditions, "resource_id = @filter_resource_id")
		data["filter_resource_id"] = *filter.ResourceID
	}
	if filter.Relation != nil {
		conditions = append(conditions, "relation = @filter_relation")
		data["filter_relation"] = *filter.Relation
	}
	if filter.Identifier != nil {
		conditions = append(conditions, "identifier = @filter_identifier")
		data["filter_identifier"] = *filter.Identifier
	}
	if filter.IdentifierType != nil {
		conditions = append(conditions, "identifier_type = @filter_identifier_type")
		data["filter_identifier_type"] = *filter.IdentifierType
	}
	if filter.ResolvedSubjectID != nil {
		conditions = append(conditions, "resolved_subject_id = @filter_resolved_subject_id")
		data["filter_resolved_subject_id"] = *filter.ResolvedSubjectID
	}
	if filter.InvitedBy != nil {
		conditions = append(conditions, "invited_by = @filter_invited_by")
		data["filter_invited_by"] = *filter.InvitedBy
	}
	if filter.TokenHash != nil {
		conditions = append(conditions, "token_hash = @filter_token_hash")
		data["filter_token_hash"] = *filter.TokenHash
	}
	if filter.AutoAccept != nil {
		conditions = append(conditions, "auto_accept = @filter_auto_accept")
		data["filter_auto_accept"] = *filter.AutoAccept
	}
	if filter.InvitationStatus != nil {
		conditions = append(conditions, "invitation_status = @filter_invitation_status")
		data["filter_invitation_status"] = *filter.InvitationStatus
	}
	if filter.ExpiresAt != nil {
		conditions = append(conditions, "expires_at = @filter_expires_at")
		data["filter_expires_at"] = *filter.ExpiresAt
	}
	if filter.ExpiresAtAfter != nil {
		conditions = append(conditions, "expires_at >= @filter_expires_at_after")
		data["filter_expires_at_after"] = *filter.ExpiresAtAfter
	}
	if filter.ExpiresAtBefore != nil {
		conditions = append(conditions, "expires_at <= @filter_expires_at_before")
		data["filter_expires_at_before"] = *filter.ExpiresAtBefore
	}
	if filter.AcceptedAt != nil {
		conditions = append(conditions, "accepted_at = @filter_accepted_at")
		data["filter_accepted_at"] = *filter.AcceptedAt
	}
	if filter.AcceptedAtAfter != nil {
		conditions = append(conditions, "accepted_at >= @filter_accepted_at_after")
		data["filter_accepted_at_after"] = *filter.AcceptedAtAfter
	}
	if filter.AcceptedAtBefore != nil {
		conditions = append(conditions, "accepted_at <= @filter_accepted_at_before")
		data["filter_accepted_at_before"] = *filter.AcceptedAtBefore
	}
	if filter.CreatedAt != nil {
		conditions = append(conditions, "created_at = @filter_created_at")
		data["filter_created_at"] = *filter.CreatedAt
	}
	if filter.CreatedAtAfter != nil {
		conditions = append(conditions, "created_at >= @filter_created_at_after")
		data["filter_created_at_after"] = *filter.CreatedAtAfter
	}
	if filter.CreatedAtBefore != nil {
		conditions = append(conditions, "created_at <= @filter_created_at_before")
		data["filter_created_at_before"] = *filter.CreatedAtBefore
	}
	if filter.UpdatedAt != nil {
		conditions = append(conditions, "updated_at = @filter_updated_at")
		data["filter_updated_at"] = *filter.UpdatedAt
	}
	if filter.UpdatedAtAfter != nil {
		conditions = append(conditions, "updated_at >= @filter_updated_at_after")
		data["filter_updated_at_after"] = *filter.UpdatedAtAfter
	}
	if filter.UpdatedAtBefore != nil {
		conditions = append(conditions, "updated_at <= @filter_updated_at_before")
		data["filter_updated_at_before"] = *filter.UpdatedAtBefore
	}
	if filter.RedirectURL != nil {
		conditions = append(conditions, "redirect_url = @filter_redirect_url")
		data["filter_redirect_url"] = *filter.RedirectURL
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "invitation_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

func generatedApplyListSearchFilter(filter invitations.FilterList, data pgx.NamedArgs) string {
	if filter.SearchTerm == nil || *filter.SearchTerm == "" {
		return "TRUE"
	}
	// ILIKE pattern search.
	searchPattern := "%" + *filter.SearchTerm + "%"
	data["search_term"] = searchPattern
	var searchConditions []string
	searchConditions = append(searchConditions, "resource_type ILIKE @search_term")
	searchConditions = append(searchConditions, "resource_id ILIKE @search_term")
	searchConditions = append(searchConditions, "relation ILIKE @search_term")
	searchConditions = append(searchConditions, "identifier ILIKE @search_term")
	searchConditions = append(searchConditions, "identifier_type ILIKE @search_term")
	searchConditions = append(searchConditions, "resolved_subject_id ILIKE @search_term")
	searchConditions = append(searchConditions, "invited_by ILIKE @search_term")
	searchConditions = append(searchConditions, "invitation_status ILIKE @search_term")
	if len(searchConditions) == 0 {
		return "TRUE"
	}
	return strings.Join(searchConditions, " OR ")
}

func generatedApplyListByResourceConditionsFilter(filter invitations.FilterListByResource, data pgx.NamedArgs) string {
	var conditions []string
	if filter.InvitationStatus != nil {
		conditions = append(conditions, "invitation_status = @filter_invitation_status")
		data["filter_invitation_status"] = *filter.InvitationStatus
	}
	if filter.Relation != nil {
		conditions = append(conditions, "relation = @filter_relation")
		data["filter_relation"] = *filter.Relation
	}
	if filter.AutoAccept != nil {
		conditions = append(conditions, "auto_accept = @filter_auto_accept")
		data["filter_auto_accept"] = *filter.AutoAccept
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "invitation_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

func generatedApplyListByResourceSearchFilter(filter invitations.FilterListByResource, data pgx.NamedArgs) string {
	if filter.SearchTerm == nil || *filter.SearchTerm == "" {
		return "TRUE"
	}
	// ILIKE pattern search.
	searchPattern := "%" + *filter.SearchTerm + "%"
	data["search_term"] = searchPattern
	var searchConditions []string
	searchConditions = append(searchConditions, "identifier ILIKE @search_term")
	if len(searchConditions) == 0 {
		return "TRUE"
	}
	return strings.Join(searchConditions, " OR ")
}

func generatedApplyListBySubjectConditionsFilter(filter invitations.FilterListBySubject, data pgx.NamedArgs) string {
	var conditions []string
	if filter.ResourceType != nil {
		conditions = append(conditions, "resource_type = @filter_resource_type")
		data["filter_resource_type"] = *filter.ResourceType
	}
	if filter.InvitationStatus != nil {
		conditions = append(conditions, "invitation_status = @filter_invitation_status")
		data["filter_invitation_status"] = *filter.InvitationStatus
	}
	if filter.Relation != nil {
		conditions = append(conditions, "relation = @filter_relation")
		data["filter_relation"] = *filter.Relation
	}
	if filter.AutoAccept != nil {
		conditions = append(conditions, "auto_accept = @filter_auto_accept")
		data["filter_auto_accept"] = *filter.AutoAccept
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "invitation_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

func generatedApplyListByIdentifierConditionsFilter(filter invitations.FilterListByIdentifier, data pgx.NamedArgs) string {
	var conditions []string
	if filter.InvitationStatus != nil {
		conditions = append(conditions, "invitation_status = @filter_invitation_status")
		data["filter_invitation_status"] = *filter.InvitationStatus
	}
	if filter.AutoAccept != nil {
		conditions = append(conditions, "auto_accept = @filter_auto_accept")
		data["filter_auto_accept"] = *filter.AutoAccept
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "invitation_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

// Ensure imports are used.
var _ = errors.New
var _ = fmt.Sprintf
var _ slog.Logger
var _ pgxdb.Querier
var _ fop.Order
