//go:build integration

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package sessionspgx

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gopernicus/gopernicus/core/repositories/auth/sessions"

	fixtures "github.com/gopernicus/gopernicus/core/testing/fixtures"

	"github.com/gopernicus/gopernicus/workshop/testing/pgxfixtures"
	"github.com/gopernicus/gopernicus/workshop/testing/testpgx"
	"github.com/gopernicus/gopernicus/sdk/fop"
	"github.com/gopernicus/gopernicus/sdk/logger"
)

// Ensure imports are used.
var (
	_ = assert.Equal
)

// setupTestStore creates a test database and store for integration tests.
// migrateTestDB must be defined in store_test.go (bootstrap file).
func setupTestStore(t *testing.T) (context.Context, *testpgx.TestPGX, *Store) {
	t.Helper()

	if testing.Short() {
		t.Skip("skipping integration test")
	}

	ctx := context.Background()
	db := testpgx.SetupTestPGX(t, ctx, testpgx.WithMigrations(migrateTestDB))
	store := NewStore(logger.NewNoop(), db.Pool)
	return ctx, db, store
}

func TestGeneratedSessionStore_Create(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	created := fixtures.CreateTestSession(t, ctx, db)

	// Verify the record was created and can be retrieved.
	result, err := store.Get(ctx, created.SessionID)
	require.NoError(t, err)
	assert.Equal(t, created.SessionID, result.SessionID)
}

func TestGeneratedSessionStore_Get(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	created := fixtures.CreateTestSession(t, ctx, db)

	t.Run("found", func(t *testing.T) {
		result, err := store.Get(ctx, created.SessionID)
		require.NoError(t, err)
		assert.Equal(t, created.SessionID, result.SessionID)
	})

	t.Run("not found", func(t *testing.T) {
		_, err := store.Get(ctx, "nonexistent-id")
		require.Error(t, err)
	})
}

func TestGeneratedSessionStore_List(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	// Create multiple records.
	const numRecords = 3
	for i := 0; i < numRecords; i++ {
		fixtures.CreateTestSession(t, ctx, db)
	}

	t.Run("returns all records", func(t *testing.T) {
		filter := sessions.FilterList{}
		orderBy := fop.NewOrder(sessions.DefaultOrderBy, sessions.DefaultOrderDirection)
		results, err := store.List(ctx, filter, orderBy, fop.PageStringCursor{}, false)
		require.NoError(t, err)
		assert.GreaterOrEqual(t, len(results), numRecords)
	})

	t.Run("respects limit", func(t *testing.T) {
		filter := sessions.FilterList{}
		orderBy := fop.NewOrder(sessions.DefaultOrderBy, sessions.DefaultOrderDirection)
		page := fop.PageStringCursor{Limit: 2}
		results, err := store.List(ctx, filter, orderBy, page, false)
		require.NoError(t, err)
		assert.LessOrEqual(t, len(results), 2)
	})

	t.Run("no duplicates", func(t *testing.T) {
		filter := sessions.FilterList{}
		orderBy := fop.NewOrder(sessions.DefaultOrderBy, sessions.DefaultOrderDirection)
		results, err := store.List(ctx, filter, orderBy, fop.PageStringCursor{}, false)
		require.NoError(t, err)

		seen := make(map[string]bool)
		for _, r := range results {
			assert.False(t, seen[r.SessionID], "duplicate record: %s", r.SessionID)
			seen[r.SessionID] = true
		}
	})
}

func TestGeneratedSessionStore_Delete(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	created := fixtures.CreateTestSession(t, ctx, db)

	err := store.Delete(ctx, created.SessionID)
	require.NoError(t, err)

	// Verify record is gone.
	_, err = store.Get(ctx, created.SessionID)
	require.Error(t, err)
}
