//go:build security

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package usersbridge

import (
	"testing"
)

func TestSecurityUserAuthenticationRequired(t *testing.T) {
	client := setupSecurityServer(t)

	t.Run("List rejects anonymous", func(t *testing.T) {
		client.Get(t, "/users").RequireStatus(t, 401)
	})

	t.Run("Get rejects anonymous", func(t *testing.T) {
		client.Get(t, "/users/probe-id").RequireStatus(t, 401)
	})

	t.Run("Update rejects anonymous", func(t *testing.T) {
		client.Put(t, "/users/probe-id", nil).RequireStatus(t, 401)
	})

	t.Run("SoftDelete rejects anonymous", func(t *testing.T) {
		client.Put(t, "/users/probe-id/delete", nil).RequireStatus(t, 401)
	})

	t.Run("Archive rejects anonymous", func(t *testing.T) {
		client.Put(t, "/users/probe-id/archive", nil).RequireStatus(t, 401)
	})

	t.Run("Restore rejects anonymous", func(t *testing.T) {
		client.Put(t, "/users/probe-id/restore", nil).RequireStatus(t, 401)
	})

	t.Run("Delete rejects anonymous", func(t *testing.T) {
		client.Delete(t, "/users/probe-id").RequireStatus(t, 401)
	})

	// Same routes with a malformed bearer token — still 401.
	client.SetBearerToken("not-a-real-token")

	t.Run("List rejects malformed token", func(t *testing.T) {
		client.Get(t, "/users").RequireStatus(t, 401)
	})

	t.Run("Get rejects malformed token", func(t *testing.T) {
		client.Get(t, "/users/probe-id").RequireStatus(t, 401)
	})

	t.Run("Update rejects malformed token", func(t *testing.T) {
		client.Put(t, "/users/probe-id", nil).RequireStatus(t, 401)
	})

	t.Run("SoftDelete rejects malformed token", func(t *testing.T) {
		client.Put(t, "/users/probe-id/delete", nil).RequireStatus(t, 401)
	})

	t.Run("Archive rejects malformed token", func(t *testing.T) {
		client.Put(t, "/users/probe-id/archive", nil).RequireStatus(t, 401)
	})

	t.Run("Restore rejects malformed token", func(t *testing.T) {
		client.Put(t, "/users/probe-id/restore", nil).RequireStatus(t, 401)
	})

	t.Run("Delete rejects malformed token", func(t *testing.T) {
		client.Delete(t, "/users/probe-id").RequireStatus(t, 401)
	})
}
