// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package securityevents

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/gopernicus/gopernicus/infrastructure/events"
	"github.com/gopernicus/gopernicus/sdk/errs"
	"github.com/gopernicus/gopernicus/sdk/fop"
)

// =============================================================================
// Errors
// =============================================================================

var (
	ErrSecurityEventNotFound         = fmt.Errorf("securityevent: %w", errs.ErrNotFound)
	ErrSecurityEventAlreadyExists    = fmt.Errorf("securityevent: %w", errs.ErrAlreadyExists)
	ErrSecurityEventInvalidReference = fmt.Errorf("securityevent: %w", errs.ErrInvalidReference)
	ErrSecurityEventInvalidInput     = fmt.Errorf("securityevent: %w", errs.ErrInvalidInput)
)

// =============================================================================
// OrderBy constants
// =============================================================================

const (
	OrderByPK           = "event_id"
	OrderByUserID       = "user_id"
	OrderByEventType    = "event_type"
	OrderByEventStatus  = "event_status"
	OrderByEventDetails = "event_details"
	OrderByIpAddress    = "ip_address"
	OrderByUserAgent    = "user_agent"
	OrderByCreatedAt    = "created_at"
)

// OrderByFields maps user-facing field names to OrderField definitions.
var OrderByFields = map[string]fop.OrderField{
	OrderByPK:           {Column: "event_id"},
	OrderByUserID:       {Column: "user_id", CastLower: true},
	OrderByEventType:    {Column: "event_type", CastLower: true},
	OrderByEventStatus:  {Column: "event_status", CastLower: true},
	OrderByEventDetails: {Column: "event_details"},
	OrderByIpAddress:    {Column: "ip_address", CastLower: true},
	OrderByUserAgent:    {Column: "user_agent", CastLower: true},
	OrderByCreatedAt:    {Column: "created_at"},
}

// =============================================================================
// Max page limits (from @max annotations)
// =============================================================================

const MaxLimitList = 100

// =============================================================================
// Entity struct
// =============================================================================

// SecurityEvent is the database entity.
type SecurityEvent struct {
	EventID      string           `json:"event_id" db:"event_id"`
	UserID       *string          `json:"user_id" db:"user_id"`
	EventType    string           `json:"event_type" db:"event_type"`
	EventStatus  string           `json:"event_status" db:"event_status"`
	EventDetails *json.RawMessage `json:"event_details" db:"event_details"`
	IpAddress    *string          `json:"ip_address" db:"ip_address"`
	UserAgent    *string          `json:"user_agent" db:"user_agent"`
	CreatedAt    time.Time        `json:"created_at" db:"created_at"`
}

// =============================================================================
// Input structs
// =============================================================================

// CreateSecurityEvent is the input for creating a security_event.
type CreateSecurityEvent struct {
	EventID      string           `json:"event_id,omitempty"`
	UserID       *string          `json:"user_id,omitempty"`
	EventType    string           `json:"event_type,omitempty"`
	EventStatus  string           `json:"event_status,omitempty"`
	EventDetails *json.RawMessage `json:"event_details,omitempty"`
	IpAddress    *string          `json:"ip_address,omitempty"`
	UserAgent    *string          `json:"user_agent,omitempty"`
}

// UpdateSecurityEvent is the input for updating a security_event.
type UpdateSecurityEvent struct {
	UserID       *string          `json:"user_id,omitempty"`
	EventType    *string          `json:"event_type,omitempty"`
	EventStatus  *string          `json:"event_status,omitempty"`
	EventDetails *json.RawMessage `json:"event_details,omitempty"`
	IpAddress    *string          `json:"ip_address,omitempty"`
	UserAgent    *string          `json:"user_agent,omitempty"`
}

// =============================================================================
// Filter structs
// =============================================================================

// FilterList holds filter criteria for List.
type FilterList struct {
	EventID         *string          `json:"event_id,omitempty"`
	UserID          *string          `json:"user_id,omitempty"`
	EventType       *string          `json:"event_type,omitempty"`
	EventStatus     *string          `json:"event_status,omitempty"`
	EventDetails    *json.RawMessage `json:"event_details,omitempty"`
	IpAddress       *string          `json:"ip_address,omitempty"`
	UserAgent       *string          `json:"user_agent,omitempty"`
	CreatedAt       *time.Time       `json:"created_at,omitempty"`
	CreatedAtAfter  *time.Time       `json:"created_at_after,omitempty"`
	CreatedAtBefore *time.Time       `json:"created_at_before,omitempty"`
	SearchTerm      *string          `json:"search_term,omitempty"`

	// AuthorizedIDs restricts results to the given primary key values.
	// Set by the bridge layer for prefilter authorization (authorization-scoped listings).
	// Nil means unrestricted (admin bypass). Empty non-nil means no access.
	AuthorizedIDs []string `json:"-"`
}

// =============================================================================
// Custom result structs
// =============================================================================

// =============================================================================
// Event structs
// =============================================================================

// =============================================================================
// Cursor helpers
// =============================================================================

func EncodeSecurityEventCursor(record SecurityEvent, orderField string) (string, error) {
	orderValue := GetSecurityEventOrderValue(record, orderField)
	return fop.EncodeCursor(orderField, orderValue, record.EventID)
}

func GetSecurityEventOrderValue(record SecurityEvent, field string) any {
	switch field {
	case "event_id":
		return record.EventID
	case "user_id":
		return record.UserID
	case "event_type":
		return record.EventType
	case "event_status":
		return record.EventStatus
	case "event_details":
		return record.EventDetails
	case "ip_address":
		return record.IpAddress
	case "user_agent":
		return record.UserAgent
	case "created_at":
		return record.CreatedAt
	default:
		return record.EventID
	}
}

// =============================================================================
// Repository methods (generated from queries.sql)
// =============================================================================

// List queries the store and wraps the result with pagination metadata.
func (r *Repository) List(ctx context.Context, filter FilterList, orderBy fop.Order, page fop.PageStringCursor) ([]SecurityEvent, fop.Pagination, error) {
	if orderBy.Field == "" {
		orderBy = fop.NewOrder(DefaultOrderBy, DefaultOrderDirection)
	}
	orderField := orderBy.Field

	// Over-fetch by one to detect next page.
	listPage := fop.PageStringCursor{
		Limit:  page.Limit + 1,
		Cursor: page.Cursor,
	}

	records, err := r.store.List(ctx, filter, orderBy, listPage, false)
	if err != nil {
		return nil, fop.Pagination{}, fmt.Errorf("query: %w", err)
	}

	returnableRecords := records
	nextCursor := ""

	if len(records) > page.Limit {
		returnableRecords = records[:page.Limit]
		lastRecord := returnableRecords[len(returnableRecords)-1]
		nextCursor, err = EncodeSecurityEventCursor(lastRecord, orderField)
		if err != nil {
			return nil, fop.Pagination{}, fmt.Errorf("encode next cursor: %w", err)
		}
	}

	pagination := fop.Pagination{
		Limit:      page.Limit,
		NextCursor: nextCursor,
		PageTotal:  len(returnableRecords),
	}

	// Check for previous page when a cursor was provided.
	if page.Cursor != "" {
		prevRecords, err := r.store.List(ctx, filter, orderBy, page, true)
		if err == nil && len(prevRecords) > 0 {
			pagination.HasPrev = true
			if len(prevRecords) == page.Limit {
				firstRecord := prevRecords[0]
				pagination.PreviousCursor, err = EncodeSecurityEventCursor(firstRecord, orderField)
				if err != nil {
					return nil, fop.Pagination{}, fmt.Errorf("encode prev cursor: %w", err)
				}
			}
		}
	}

	return returnableRecords, pagination, nil
}

// Get delegates to the store.
func (r *Repository) Get(ctx context.Context, eventID string) (SecurityEvent, error) {
	result, err := r.store.Get(ctx, eventID)
	if err != nil {
		return SecurityEvent{}, fmt.Errorf("get: %w", err)
	}
	return result, nil
}

// Create generates an ID, sets defaults, and delegates to the store.
func (r *Repository) Create(ctx context.Context, input CreateSecurityEvent) (SecurityEvent, error) {
	if input.EventID == "" {
		id, err := r.generateID()
		if err != nil {
			return SecurityEvent{}, fmt.Errorf("generate id: %w", err)
		}
		input.EventID = id
	}
	result, err := r.store.Create(ctx, input)
	if err != nil {
		return SecurityEvent{}, fmt.Errorf("create: %w", err)
	}
	return result, nil
}

// Update delegates to the store.
func (r *Repository) Update(ctx context.Context, eventID string, input UpdateSecurityEvent) (SecurityEvent, error) {
	result, err := r.store.Update(ctx, eventID, input)
	if err != nil {
		return SecurityEvent{}, fmt.Errorf("update: %w", err)
	}
	return result, nil
}

// Delete delegates to the store.
func (r *Repository) Delete(ctx context.Context, eventID string) error {
	if err := r.store.Delete(ctx, eventID); err != nil {
		return fmt.Errorf("delete: %w", err)
	}
	return nil
}

// Ensure imports are used.
var _ = time.Time{}
var _ = fop.Order{}
var _ context.Context
var _ events.Event
