// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.

package rebacrelationshipspgx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
	"github.com/gopernicus/gopernicus/sdk/fop"

	"github.com/gopernicus/gopernicus/core/repositories/rebac/rebacrelationships"
)

// Store implements rebacrelationships.Storer using PostgreSQL via pgx.
type Store struct {
	log *slog.Logger
	db  pgxdb.Querier
}

// NewStore creates a new rebacrelationships store backed by the given Querier.
// Querier is satisfied by both *pgxpool.Pool and pgx.Tx, enabling
// transaction composition.
func NewStore(log *slog.Logger, db pgxdb.Querier) *Store {
	return &Store{log: log, db: db}
}

// compile-time interface check (Storer is defined in repository.go)
var _ rebacrelationships.Storer = (*Store)(nil)

// ─── error mapping ────────────────────────────────────────────────────────────

func (s *Store) mapError(err error) error {
	dbErr := pgxdb.HandlePgError(err)
	switch {
	case errors.Is(dbErr, pgxdb.ErrDBDuplicatedEntry):
		return rebacrelationships.ErrRebacRelationshipAlreadyExists
	case errors.Is(dbErr, pgxdb.ErrDBForeignKeyViolation):
		return rebacrelationships.ErrRebacRelationshipInvalidReference
	case errors.Is(dbErr, pgxdb.ErrDBCheckViolation),
		errors.Is(dbErr, pgxdb.ErrDBNotNullViolation):
		return rebacrelationships.ErrRebacRelationshipInvalidInput
	default:
		return dbErr
	}
}

// ─── methods ──────────────────────────────────────────────────────────────────

func (s *Store) List(ctx context.Context, filter rebacrelationships.FilterList, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]rebacrelationships.RebacRelationship, error) {
	data := pgx.NamedArgs{}

	baseSQL := `SELECT *
FROM public.rebac_relationships
WHERE $conditions AND $search`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListConditionsFilter(filter, data))
	baseSQL = replaceFilterPlaceholder(baseSQL, "$search", generatedApplyListSearchFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := rebacrelationships.OrderByFields[orderBy.Field]
	if !ok {
		of = rebacrelationships.OrderByFields[rebacrelationships.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "relationship_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "relationship_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[rebacrelationships.RebacRelationship])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) Get(ctx context.Context, relationshipID string) (rebacrelationships.RebacRelationship, error) {
	query := `SELECT relationship_id, resource_type, resource_id, relation, subject_type, subject_id, subject_relation, created_at
FROM public.rebac_relationships
WHERE relationship_id = @relationship_id`

	args := pgx.NamedArgs{
		"relationship_id": relationshipID,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return rebacrelationships.RebacRelationship{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[rebacrelationships.RebacRelationship])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return rebacrelationships.RebacRelationship{}, rebacrelationships.ErrRebacRelationshipNotFound
		}
		return rebacrelationships.RebacRelationship{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) Create(ctx context.Context, input rebacrelationships.CreateRebacRelationship) (rebacrelationships.RebacRelationship, error) {
	now := time.Now().UTC()
	query := `INSERT INTO public.rebac_relationships (relationship_id, resource_type, resource_id, relation, subject_type, subject_id, subject_relation, created_at)
		VALUES (@relationship_id, @resource_type, @resource_id, @relation, @subject_type, @subject_id, @subject_relation, @_created_at)
		RETURNING relationship_id, resource_type, resource_id, relation, subject_type, subject_id, subject_relation, created_at`

	args := pgx.NamedArgs{
		"relationship_id":  input.RelationshipID,
		"resource_type":    input.ResourceType,
		"resource_id":      input.ResourceID,
		"relation":         input.Relation,
		"subject_type":     input.SubjectType,
		"subject_id":       input.SubjectID,
		"subject_relation": input.SubjectRelation,
		"_created_at":      now,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return rebacrelationships.RebacRelationship{}, s.mapError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[rebacrelationships.RebacRelationship])
	if err != nil {
		return rebacrelationships.RebacRelationship{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Update(ctx context.Context, relationshipID string, input rebacrelationships.UpdateRebacRelationship) (rebacrelationships.RebacRelationship, error) {
	buf := bytes.NewBufferString("UPDATE public.rebac_relationships SET ")
	args := pgx.NamedArgs{
		"relationship_id": relationshipID,
	}
	var setClauses []string
	if input.ResourceType != nil {
		setClauses = append(setClauses, "resource_type = @resource_type")
		args["resource_type"] = *input.ResourceType
	}
	if input.ResourceID != nil {
		setClauses = append(setClauses, "resource_id = @resource_id")
		args["resource_id"] = *input.ResourceID
	}
	if input.Relation != nil {
		setClauses = append(setClauses, "relation = @relation")
		args["relation"] = *input.Relation
	}
	if input.SubjectType != nil {
		setClauses = append(setClauses, "subject_type = @subject_type")
		args["subject_type"] = *input.SubjectType
	}
	if input.SubjectID != nil {
		setClauses = append(setClauses, "subject_id = @subject_id")
		args["subject_id"] = *input.SubjectID
	}
	if input.SubjectRelation != nil {
		setClauses = append(setClauses, "subject_relation = @subject_relation")
		args["subject_relation"] = *input.SubjectRelation
	}

	if len(setClauses) == 0 {
		return rebacrelationships.RebacRelationship{}, fmt.Errorf("no fields to update")
	}

	buf.WriteString(strings.Join(setClauses, ", "))
	buf.WriteString(" WHERE relationship_id = @relationship_id")
	buf.WriteString(" RETURNING relationship_id, resource_type, resource_id, relation, subject_type, subject_id, subject_relation, created_at")

	rows, err := s.db.Query(ctx, buf.String(), args)
	if err != nil {
		return rebacrelationships.RebacRelationship{}, s.mapError(err)
	}
	defer rows.Close()
	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[rebacrelationships.RebacRelationship])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return rebacrelationships.RebacRelationship{}, rebacrelationships.ErrRebacRelationshipNotFound
		}
		return rebacrelationships.RebacRelationship{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Delete(ctx context.Context, relationshipID string) error {
	args := pgx.NamedArgs{
		"relationship_id": relationshipID,
	}

	query := `DELETE FROM public.rebac_relationships
WHERE relationship_id = @relationship_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return rebacrelationships.ErrRebacRelationshipNotFound
	}

	return nil
}

func (s *Store) ListBySubject(ctx context.Context, filter rebacrelationships.FilterListBySubject, subjectType string, subjectID string, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]rebacrelationships.RebacRelationship, error) {
	data := pgx.NamedArgs{
		"subject_type": subjectType,
		"subject_id":   subjectID,
	}

	baseSQL := `SELECT *
FROM public.rebac_relationships
WHERE subject_type = @subject_type
AND subject_id = @subject_id
AND $conditions`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListBySubjectConditionsFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := rebacrelationships.OrderByFields[orderBy.Field]
	if !ok {
		of = rebacrelationships.OrderByFields[rebacrelationships.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "relationship_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "relationship_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[rebacrelationships.RebacRelationship])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) ListByResource(ctx context.Context, filter rebacrelationships.FilterListByResource, resourceType string, resourceID string, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]rebacrelationships.RebacRelationship, error) {
	data := pgx.NamedArgs{
		"resource_type": resourceType,
		"resource_id":   resourceID,
	}

	baseSQL := `SELECT *
FROM public.rebac_relationships
WHERE resource_type = @resource_type
AND resource_id = @resource_id
AND $conditions`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListByResourceConditionsFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := rebacrelationships.OrderByFields[orderBy.Field]
	if !ok {
		of = rebacrelationships.OrderByFields[rebacrelationships.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "relationship_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "relationship_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[rebacrelationships.RebacRelationship])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) DeleteAllForResource(ctx context.Context, resourceType string, resourceID string) error {
	args := pgx.NamedArgs{
		"resource_type": resourceType,
		"resource_id":   resourceID,
	}

	query := `DELETE FROM public.rebac_relationships
WHERE resource_type = @resource_type
AND resource_id = @resource_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return rebacrelationships.ErrRebacRelationshipNotFound
	}

	return nil
}

func (s *Store) DeleteByTuple(ctx context.Context, resourceType string, resourceID string, relation string, subjectType string, subjectID string) error {
	args := pgx.NamedArgs{
		"resource_type": resourceType,
		"resource_id":   resourceID,
		"relation":      relation,
		"subject_type":  subjectType,
		"subject_id":    subjectID,
	}

	query := `DELETE FROM public.rebac_relationships
WHERE resource_type = @resource_type
AND resource_id = @resource_id
AND relation = @relation
AND subject_type = @subject_type
AND subject_id = @subject_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return rebacrelationships.ErrRebacRelationshipNotFound
	}

	return nil
}

func (s *Store) DeleteByResourceAndSubject(ctx context.Context, resourceType string, resourceID string, subjectType string, subjectID string) error {
	args := pgx.NamedArgs{
		"resource_type": resourceType,
		"resource_id":   resourceID,
		"subject_type":  subjectType,
		"subject_id":    subjectID,
	}

	query := `DELETE FROM public.rebac_relationships
WHERE resource_type = @resource_type
AND resource_id = @resource_id
AND subject_type = @subject_type
AND subject_id = @subject_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return rebacrelationships.ErrRebacRelationshipNotFound
	}

	return nil
}

func (s *Store) DeleteBySubject(ctx context.Context, subjectType string, subjectID string) error {
	args := pgx.NamedArgs{
		"subject_type": subjectType,
		"subject_id":   subjectID,
	}

	query := `DELETE FROM public.rebac_relationships
WHERE subject_type = @subject_type
AND subject_id = @subject_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return rebacrelationships.ErrRebacRelationshipNotFound
	}

	return nil
}

// ─── filter placeholder substitution ─────────────────────────────────────────

func replaceFilterPlaceholder(sql, placeholder, fragment string) string {
	if fragment == "" {
		fragment = "TRUE"
	}
	return strings.Replace(sql, placeholder, "("+fragment+")", 1)
}

// ─── per-function named filters ──────────────────────────────────────────────

func generatedApplyListConditionsFilter(filter rebacrelationships.FilterList, data pgx.NamedArgs) string {
	var conditions []string
	if filter.RelationshipID != nil {
		conditions = append(conditions, "relationship_id = @filter_relationship_id")
		data["filter_relationship_id"] = *filter.RelationshipID
	}
	if filter.ResourceType != nil {
		conditions = append(conditions, "resource_type = @filter_resource_type")
		data["filter_resource_type"] = *filter.ResourceType
	}
	if filter.ResourceID != nil {
		conditions = append(conditions, "resource_id = @filter_resource_id")
		data["filter_resource_id"] = *filter.ResourceID
	}
	if filter.Relation != nil {
		conditions = append(conditions, "relation = @filter_relation")
		data["filter_relation"] = *filter.Relation
	}
	if filter.SubjectType != nil {
		conditions = append(conditions, "subject_type = @filter_subject_type")
		data["filter_subject_type"] = *filter.SubjectType
	}
	if filter.SubjectID != nil {
		conditions = append(conditions, "subject_id = @filter_subject_id")
		data["filter_subject_id"] = *filter.SubjectID
	}
	if filter.SubjectRelation != nil {
		conditions = append(conditions, "subject_relation = @filter_subject_relation")
		data["filter_subject_relation"] = *filter.SubjectRelation
	}
	if filter.CreatedAt != nil {
		conditions = append(conditions, "created_at = @filter_created_at")
		data["filter_created_at"] = *filter.CreatedAt
	}
	if filter.CreatedAtAfter != nil {
		conditions = append(conditions, "created_at >= @filter_created_at_after")
		data["filter_created_at_after"] = *filter.CreatedAtAfter
	}
	if filter.CreatedAtBefore != nil {
		conditions = append(conditions, "created_at <= @filter_created_at_before")
		data["filter_created_at_before"] = *filter.CreatedAtBefore
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "relationship_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

func generatedApplyListSearchFilter(filter rebacrelationships.FilterList, data pgx.NamedArgs) string {
	if filter.SearchTerm == nil || *filter.SearchTerm == "" {
		return "TRUE"
	}
	// ILIKE pattern search.
	searchPattern := "%" + *filter.SearchTerm + "%"
	data["search_term"] = searchPattern
	var searchConditions []string
	searchConditions = append(searchConditions, "resource_type ILIKE @search_term")
	searchConditions = append(searchConditions, "resource_id ILIKE @search_term")
	searchConditions = append(searchConditions, "relation ILIKE @search_term")
	searchConditions = append(searchConditions, "subject_type ILIKE @search_term")
	searchConditions = append(searchConditions, "subject_id ILIKE @search_term")
	searchConditions = append(searchConditions, "subject_relation ILIKE @search_term")
	if len(searchConditions) == 0 {
		return "TRUE"
	}
	return strings.Join(searchConditions, " OR ")
}

func generatedApplyListBySubjectConditionsFilter(filter rebacrelationships.FilterListBySubject, data pgx.NamedArgs) string {
	var conditions []string
	if filter.ResourceType != nil {
		conditions = append(conditions, "resource_type = @filter_resource_type")
		data["filter_resource_type"] = *filter.ResourceType
	}
	if filter.Relation != nil {
		conditions = append(conditions, "relation = @filter_relation")
		data["filter_relation"] = *filter.Relation
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "relationship_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

func generatedApplyListByResourceConditionsFilter(filter rebacrelationships.FilterListByResource, data pgx.NamedArgs) string {
	var conditions []string
	if filter.SubjectType != nil {
		conditions = append(conditions, "subject_type = @filter_subject_type")
		data["filter_subject_type"] = *filter.SubjectType
	}
	if filter.Relation != nil {
		conditions = append(conditions, "relation = @filter_relation")
		data["filter_relation"] = *filter.Relation
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "relationship_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

// Ensure imports are used.
var _ = errors.New
var _ = fmt.Sprintf
var _ slog.Logger
var _ pgxdb.Querier
var _ fop.Order
