//go:build e2e

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package userpasswordsbridge

import (
	"context"
	"encoding/json"
	"net/url"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gopernicus/gopernicus/core/auth/authorization"
	"github.com/gopernicus/gopernicus/core/repositories/auth/userpasswords"
	"github.com/gopernicus/gopernicus/core/repositories/auth/userpasswords/userpasswordspgx"

	"github.com/gopernicus/gopernicus/sdk/logger"
	"github.com/gopernicus/gopernicus/workshop/testing/fixtures"
	"github.com/gopernicus/gopernicus/workshop/testing/testauth"
	"github.com/gopernicus/gopernicus/workshop/testing/testhttp"
	"github.com/gopernicus/gopernicus/workshop/testing/testpgx"
	"github.com/gopernicus/gopernicus/workshop/testing/testserver"
)

// Ensure imports are used.
var _ = assert.Equal

// e2eDB is the test database handle the stack boots against.
type e2eDB = *testpgx.TestPGX

// e2eAuthSchema is the entity's resource schema, rendered locally — the
// domain composite package exports AuthSchema() but importing it here is an
// import cycle (the composite imports this bridge package). The bridge's
// own @auth.create relationship writes at POST time grant the suite's
// subject the relations these permissions check.
func e2eAuthSchema() []authorization.ResourceSchema {
	return []authorization.ResourceSchema{
		{
			Name: "user_password",
			Def: authorization.ResourceTypeDef{
				Relations: map[string]authorization.RelationDef{
					"owner": {AllowedSubjects: []authorization.SubjectTypeRef{
						{Type: "user"},
						{Type: "service_account"},
					}},
				},
				Permissions: map[string]authorization.PermissionRule{
					"list": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"create": authorization.AnyOf(
						authorization.Direct("authenticated"),
					),
					"read": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"update": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"delete": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"manage": authorization.AnyOf(
						authorization.Direct("owner"),
					),
				},
			},
		},
	}
}

// setupE2EServer boots the full HTTP stack for UserPassword against a fresh
// database: store → repository → bridge, served via testserver.ServeBridge.
// It returns the test DB too so FK parents can be seeded into the same store
// the server reads. migrateE2EDB is defined in e2e_test.go (bootstrap file).
func setupE2EServer(t *testing.T) (*testhttp.Client, e2eDB, string) {
	t.Helper()

	if testing.Short() {
		t.Skip("skipping e2e test")
	}

	ctx := context.Background()
	db := testpgx.SetupTestPGX(t, ctx, testpgx.WithMigrations(migrateE2EDB))

	store := userpasswordspgx.NewStore(logger.NewNoop(), db.Pool)
	repo := userpasswords.NewRepository(userpasswords.NewCacheStore(store, nil))
	authenticator, signer := testauth.Authenticator("e2etest")
	authorizer, _ := testauth.AuthorizerWithStore(authorization.NewSchema(e2eAuthSchema()))
	bridge := NewBridge(logger.NewNoop(), repo, testserver.NewRateLimiter(), authenticator, authorizer)

	client := testserver.ServeBridge(t, bridge)

	// Parent-gated authorize checks target the subject's own user record
	// (checkSelf) — the suite authenticates AS a real fixture user and
	// binds the create request's parent FK to it.
	user := fixtures.CreateTestUserWithDefaults(t, ctx, db)
	client.SetBearerToken(testauth.MintAccessToken(signer, user.UserID))
	return client, db, user.UserID
}

// seededCreateUserPasswordRequest builds a valid create request, populating
// foreign-key fields from parent rows seeded into db.
func seededCreateUserPasswordRequest(t *testing.T, db e2eDB, subjectID string) CreateUserPasswordRequest {
	t.Helper()
	_ = db
	req := validCreateUserPasswordRequest()
	// The parent FK is the suite's own subject — checkSelf authorizes it.
	req.UserID = subjectID
	return req
}

// The suite runs authenticated — one anonymous request must still be
// rejected, proving enforcement is live in this exact stack.
func TestE2EUserPasswordRequiresAuthentication(t *testing.T) {
	client, db, subjectID := setupE2EServer(t)
	anon := client.Anonymous()
	anon.Post(t, "/user-passwords", seededCreateUserPasswordRequest(t, db, subjectID)).RequireStatus(t, 401)
}

func TestE2EUserPasswordCreateAndGet(t *testing.T) {
	client, db, subjectID := setupE2EServer(t)

	resp := client.Post(t, "/user-passwords", seededCreateUserPasswordRequest(t, db, subjectID))
	resp.RequireStatus(t, 201)
	id := resp.String(t, "record.user_id")
	require.NotEmpty(t, id)

	got := client.Get(t, "/user-passwords/"+id)
	got.RequireStatus(t, 200)
	assert.Equal(t, id, got.String(t, "record.user_id"))

	t.Run("not found", func(t *testing.T) {
		id := "nonexistent-e2e-id"
		client.Get(t, "/user-passwords/"+id).RequireStatus(t, 403)
	})
}

func TestE2EUserPasswordList(t *testing.T) {
	client, db, subjectID := setupE2EServer(t)

	client.Post(t, "/user-passwords", seededCreateUserPasswordRequest(t, db, subjectID)).RequireStatus(t, 201)
	client.Get(t, "/user-passwords").RequireStatus(t, 200)
}

func TestE2EUserPasswordDelete(t *testing.T) {
	client, db, subjectID := setupE2EServer(t)

	resp := client.Post(t, "/user-passwords", seededCreateUserPasswordRequest(t, db, subjectID))
	resp.RequireStatus(t, 201)
	id := resp.String(t, "record.user_id")
	require.NotEmpty(t, id)

	client.Delete(t, "/user-passwords/"+id).RequireStatus(t, 204)
	client.Get(t, "/user-passwords/"+id).RequireStatus(t, 404)
}

func TestE2EUserPasswordSQLInjection(t *testing.T) {
	client, db, subjectID := setupE2EServer(t)

	// One known row — an executed OR-1=1 style injection would leak it.
	client.Post(t, "/user-passwords", seededCreateUserPasswordRequest(t, db, subjectID)).RequireStatus(t, 201)

	payloads := []string{
		`' OR 1=1 --`,
		`'; DROP TABLE zzz_not_a_table; --`,
		`" OR ""="`,
	}

	// String filter params are parameterized match values: a payload must
	// never error the server and must never match the seeded row.
	stringParams := []string{"user_id", "password_hash"}
	for _, param := range stringParams {
		for _, payload := range payloads {
			resp := client.Get(t, "/user-passwords?"+url.Values{param: []string{payload}}.Encode())
			require.Less(t, resp.StatusCode, 500,
				"param %q payload %q must not cause a server error", param, payload)
			if resp.StatusCode == 200 {
				// Empty result sets marshal as data: null — only a non-empty
				// array is a leak.
				if data, ok := resp.JSON(t)["data"].([]any); ok {
					assert.Empty(t, data,
						"param %q payload %q matched rows — possible injection", param, payload)
				}
			}
		}
	}

	// Non-string filters and order/limit/cursor reject or ignore garbage —
	// never a server error.
	otherParams := []string{"password_changed_at", "password_verified", "created_at", "updated_at", "order", "limit", "cursor"}
	for _, param := range otherParams {
		for _, payload := range payloads {
			resp := client.Get(t, "/user-passwords?"+url.Values{param: []string{payload}}.Encode())
			require.Less(t, resp.StatusCode, 500,
				"param %q payload %q must not cause a server error", param, payload)
		}
	}
}

func TestE2EUserPasswordOversizedPayload(t *testing.T) {
	client, db, subjectID := setupE2EServer(t)

	// A body past the route's max_body_size (1048576 bytes) must
	// be rejected with 413, not accepted or 500'd. Pad a valid request with a
	// huge string field the server ignores so only the size trips the limit.
	raw, err := json.Marshal(seededCreateUserPasswordRequest(t, db, subjectID))
	require.NoError(t, err)
	var body map[string]any
	require.NoError(t, json.Unmarshal(raw, &body))
	body["_padding"] = strings.Repeat("A", 1048576+1)

	client.Post(t, "/user-passwords", body).RequireStatus(t, 413)
}
