// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package principals

import (
	"context"
	"fmt"
	"time"

	"github.com/gopernicus/gopernicus/infrastructure/events"
	"github.com/gopernicus/gopernicus/sdk/errs"
	"github.com/gopernicus/gopernicus/sdk/fop"
)

// =============================================================================
// Errors
// =============================================================================

var (
	ErrPrincipalNotFound         = fmt.Errorf("principal: %w", errs.ErrNotFound)
	ErrPrincipalAlreadyExists    = fmt.Errorf("principal: %w", errs.ErrAlreadyExists)
	ErrPrincipalInvalidReference = fmt.Errorf("principal: %w", errs.ErrInvalidReference)
	ErrPrincipalInvalidInput     = fmt.Errorf("principal: %w", errs.ErrInvalidInput)
)

// =============================================================================
// OrderBy constants
// =============================================================================

const (
	OrderByPK            = "principal_id"
	OrderByPrincipalType = "principal_type"
	OrderByCreatedAt     = "created_at"
)

// OrderByFields maps user-facing field names to OrderField definitions.
var OrderByFields = map[string]fop.OrderField{
	OrderByPK:            {Column: "principal_id"},
	OrderByPrincipalType: {Column: "principal_type", CastLower: true},
	OrderByCreatedAt:     {Column: "created_at"},
}

// =============================================================================
// Max page limits (from @max annotations)
// =============================================================================

const MaxLimitList = 100

// =============================================================================
// Entity struct
// =============================================================================

// Principal is the database entity.
type Principal struct {
	PrincipalID   string    `json:"principal_id" db:"principal_id"`
	PrincipalType string    `json:"principal_type" db:"principal_type"`
	CreatedAt     time.Time `json:"created_at" db:"created_at"`
}

// =============================================================================
// Input structs
// =============================================================================

// CreatePrincipal is the input for creating a principal.
type CreatePrincipal struct {
	PrincipalID   string `json:"principal_id,omitempty"`
	PrincipalType string `json:"principal_type,omitempty"`
}

// UpdatePrincipal is the input for updating a principal.
type UpdatePrincipal struct {
	PrincipalType *string `json:"principal_type,omitempty"`
}

// =============================================================================
// Filter structs
// =============================================================================

// FilterList holds filter criteria for List.
type FilterList struct {
	PrincipalID     *string    `json:"principal_id,omitempty"`
	PrincipalType   *string    `json:"principal_type,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	CreatedAtAfter  *time.Time `json:"created_at_after,omitempty"`
	CreatedAtBefore *time.Time `json:"created_at_before,omitempty"`
	SearchTerm      *string    `json:"search_term,omitempty"`

	// AuthorizedIDs restricts results to the given primary key values.
	// Set by the bridge layer for prefilter authorization (authorization-scoped listings).
	// Nil means unrestricted (admin bypass). Empty non-nil means no access.
	AuthorizedIDs []string `json:"-"`
}

// =============================================================================
// Custom result structs
// =============================================================================

// =============================================================================
// Event structs
// =============================================================================

// =============================================================================
// Cursor helpers
// =============================================================================

func EncodePrincipalCursor(record Principal, orderField string) (string, error) {
	orderValue := GetPrincipalOrderValue(record, orderField)
	return fop.EncodeCursor(orderField, orderValue, record.PrincipalID)
}

func GetPrincipalOrderValue(record Principal, field string) any {
	switch field {
	case "principal_id":
		return record.PrincipalID
	case "principal_type":
		return record.PrincipalType
	case "created_at":
		return record.CreatedAt
	default:
		return record.PrincipalID
	}
}

// =============================================================================
// Repository methods (generated from queries.sql)
// =============================================================================

// List queries the store and wraps the result with pagination metadata.
func (r *Repository) List(ctx context.Context, filter FilterList, orderBy fop.Order, page fop.PageStringCursor) ([]Principal, fop.Pagination, error) {
	if orderBy.Field == "" {
		orderBy = fop.NewOrder(DefaultOrderBy, DefaultOrderDirection)
	}
	orderField := orderBy.Field

	// Over-fetch by one to detect next page.
	listPage := fop.PageStringCursor{
		Limit:  page.Limit + 1,
		Cursor: page.Cursor,
	}

	records, err := r.store.List(ctx, filter, orderBy, listPage, false)
	if err != nil {
		return nil, fop.Pagination{}, fmt.Errorf("query: %w", err)
	}

	returnableRecords := records
	nextCursor := ""

	if len(records) > page.Limit {
		returnableRecords = records[:page.Limit]
		lastRecord := returnableRecords[len(returnableRecords)-1]
		nextCursor, err = EncodePrincipalCursor(lastRecord, orderField)
		if err != nil {
			return nil, fop.Pagination{}, fmt.Errorf("encode next cursor: %w", err)
		}
	}

	pagination := fop.Pagination{
		Limit:      page.Limit,
		NextCursor: nextCursor,
		PageTotal:  len(returnableRecords),
	}

	// Check for previous page when a cursor was provided.
	if page.Cursor != "" {
		prevRecords, err := r.store.List(ctx, filter, orderBy, page, true)
		if err == nil && len(prevRecords) > 0 {
			pagination.HasPrev = true
			if len(prevRecords) == page.Limit {
				firstRecord := prevRecords[0]
				pagination.PreviousCursor, err = EncodePrincipalCursor(firstRecord, orderField)
				if err != nil {
					return nil, fop.Pagination{}, fmt.Errorf("encode prev cursor: %w", err)
				}
			}
		}
	}

	return returnableRecords, pagination, nil
}

// Get delegates to the store.
func (r *Repository) Get(ctx context.Context, principalID string) (Principal, error) {
	result, err := r.store.Get(ctx, principalID)
	if err != nil {
		return Principal{}, fmt.Errorf("get: %w", err)
	}
	return result, nil
}

// Create generates an ID, sets defaults, and delegates to the store.
func (r *Repository) Create(ctx context.Context, input CreatePrincipal) (Principal, error) {
	if input.PrincipalID == "" {
		id, err := r.generateID()
		if err != nil {
			return Principal{}, fmt.Errorf("generate id: %w", err)
		}
		input.PrincipalID = id
	}
	result, err := r.store.Create(ctx, input)
	if err != nil {
		return Principal{}, fmt.Errorf("create: %w", err)
	}
	return result, nil
}

// Update delegates to the store.
func (r *Repository) Update(ctx context.Context, principalID string, input UpdatePrincipal) (Principal, error) {
	result, err := r.store.Update(ctx, principalID, input)
	if err != nil {
		return Principal{}, fmt.Errorf("update: %w", err)
	}
	return result, nil
}

// Delete delegates to the store.
func (r *Repository) Delete(ctx context.Context, principalID string) error {
	if err := r.store.Delete(ctx, principalID); err != nil {
		return fmt.Errorf("delete: %w", err)
	}
	return nil
}

// Ensure imports are used.
var _ = time.Time{}
var _ = fop.Order{}
var _ context.Context
var _ events.Event
