// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package oauthaccounts

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/gopernicus/gopernicus/infrastructure/events"
	"github.com/gopernicus/gopernicus/sdk/errs"
	"github.com/gopernicus/gopernicus/sdk/fop"
)

// =============================================================================
// Errors
// =============================================================================

var (
	ErrOauthAccountNotFound         = fmt.Errorf("oauthaccount: %w", errs.ErrNotFound)
	ErrOauthAccountAlreadyExists    = fmt.Errorf("oauthaccount: %w", errs.ErrAlreadyExists)
	ErrOauthAccountInvalidReference = fmt.Errorf("oauthaccount: %w", errs.ErrInvalidReference)
	ErrOauthAccountInvalidInput     = fmt.Errorf("oauthaccount: %w", errs.ErrInvalidInput)
)

// =============================================================================
// OrderBy constants
// =============================================================================

const (
	OrderByPK                    = "oauth_account_id"
	OrderByParentUserID          = "parent_user_id"
	OrderByProvider              = "provider"
	OrderByProviderUserID        = "provider_user_id"
	OrderByProviderEmail         = "provider_email"
	OrderByProviderEmailVerified = "provider_email_verified"
	OrderByAccountVerified       = "account_verified"
	OrderByAccessToken           = "access_token"
	OrderByRefreshToken          = "refresh_token"
	OrderByTokenExpiresAt        = "token_expires_at"
	OrderByTokenType             = "token_type"
	OrderByScope                 = "scope"
	OrderByIDToken               = "id_token"
	OrderByProfileData           = "profile_data"
	OrderByLinkedAt              = "linked_at"
	OrderByCreatedAt             = "created_at"
	OrderByUpdatedAt             = "updated_at"
)

// OrderByFields maps user-facing field names to OrderField definitions.
var OrderByFields = map[string]fop.OrderField{
	OrderByPK:                    {Column: "oauth_account_id"},
	OrderByParentUserID:          {Column: "parent_user_id", CastLower: true},
	OrderByProvider:              {Column: "provider", CastLower: true},
	OrderByProviderUserID:        {Column: "provider_user_id", CastLower: true},
	OrderByProviderEmail:         {Column: "provider_email", CastLower: true},
	OrderByProviderEmailVerified: {Column: "provider_email_verified"},
	OrderByAccountVerified:       {Column: "account_verified"},
	OrderByAccessToken:           {Column: "access_token", CastLower: true},
	OrderByRefreshToken:          {Column: "refresh_token", CastLower: true},
	OrderByTokenExpiresAt:        {Column: "token_expires_at"},
	OrderByTokenType:             {Column: "token_type", CastLower: true},
	OrderByScope:                 {Column: "scope", CastLower: true},
	OrderByIDToken:               {Column: "id_token", CastLower: true},
	OrderByProfileData:           {Column: "profile_data"},
	OrderByLinkedAt:              {Column: "linked_at"},
	OrderByCreatedAt:             {Column: "created_at"},
	OrderByUpdatedAt:             {Column: "updated_at"},
}

// =============================================================================
// Max page limits (from @max annotations)
// =============================================================================

const MaxLimitList = 100

// =============================================================================
// Entity struct
// =============================================================================

// OauthAccount is the database entity.
type OauthAccount struct {
	OauthAccountID        string           `json:"oauth_account_id" db:"oauth_account_id"`
	ParentUserID          string           `json:"parent_user_id" db:"parent_user_id"`
	Provider              string           `json:"provider" db:"provider"`
	ProviderUserID        string           `json:"provider_user_id" db:"provider_user_id"`
	ProviderEmail         *string          `json:"provider_email" db:"provider_email"`
	ProviderEmailVerified *bool            `json:"provider_email_verified" db:"provider_email_verified"`
	AccountVerified       bool             `json:"account_verified" db:"account_verified"`
	AccessToken           *string          `json:"access_token" db:"access_token"`
	RefreshToken          *string          `json:"refresh_token" db:"refresh_token"`
	TokenExpiresAt        *time.Time       `json:"token_expires_at" db:"token_expires_at"`
	TokenType             *string          `json:"token_type" db:"token_type"`
	Scope                 *string          `json:"scope" db:"scope"`
	IDToken               *string          `json:"id_token" db:"id_token"`
	ProfileData           *json.RawMessage `json:"profile_data" db:"profile_data"`
	LinkedAt              time.Time        `json:"linked_at" db:"linked_at"`
	CreatedAt             time.Time        `json:"created_at" db:"created_at"`
	UpdatedAt             time.Time        `json:"updated_at" db:"updated_at"`
}

// =============================================================================
// Input structs
// =============================================================================

// CreateOauthAccount is the input for creating a oauth_account.
type CreateOauthAccount struct {
	OauthAccountID        string           `json:"oauth_account_id,omitempty"`
	ParentUserID          string           `json:"parent_user_id,omitempty"`
	Provider              string           `json:"provider,omitempty"`
	ProviderUserID        string           `json:"provider_user_id,omitempty"`
	ProviderEmail         *string          `json:"provider_email,omitempty"`
	ProviderEmailVerified *bool            `json:"provider_email_verified,omitempty"`
	AccountVerified       bool             `json:"account_verified,omitempty"`
	AccessToken           *string          `json:"access_token,omitempty"`
	RefreshToken          *string          `json:"refresh_token,omitempty"`
	TokenExpiresAt        *time.Time       `json:"token_expires_at,omitempty"`
	TokenType             *string          `json:"token_type,omitempty"`
	Scope                 *string          `json:"scope,omitempty"`
	IDToken               *string          `json:"id_token,omitempty"`
	ProfileData           *json.RawMessage `json:"profile_data,omitempty"`
	LinkedAt              time.Time        `json:"linked_at,omitempty"`
}

// UpdateOauthAccount is the input for updating a oauth_account.
type UpdateOauthAccount struct {
	Provider              *string          `json:"provider,omitempty"`
	ProviderUserID        *string          `json:"provider_user_id,omitempty"`
	ProviderEmail         *string          `json:"provider_email,omitempty"`
	ProviderEmailVerified *bool            `json:"provider_email_verified,omitempty"`
	AccountVerified       *bool            `json:"account_verified,omitempty"`
	AccessToken           *string          `json:"access_token,omitempty"`
	RefreshToken          *string          `json:"refresh_token,omitempty"`
	TokenExpiresAt        *time.Time       `json:"token_expires_at,omitempty"`
	TokenType             *string          `json:"token_type,omitempty"`
	Scope                 *string          `json:"scope,omitempty"`
	IDToken               *string          `json:"id_token,omitempty"`
	ProfileData           *json.RawMessage `json:"profile_data,omitempty"`
	LinkedAt              *time.Time       `json:"linked_at,omitempty"`
	UpdatedAt             *time.Time       `json:"updated_at,omitempty"`
}

// =============================================================================
// Filter structs
// =============================================================================

// FilterList holds filter criteria for List.
type FilterList struct {
	OauthAccountID        *string          `json:"oauth_account_id,omitempty"`
	ParentUserID          *string          `json:"parent_user_id,omitempty"`
	Provider              *string          `json:"provider,omitempty"`
	ProviderUserID        *string          `json:"provider_user_id,omitempty"`
	ProviderEmail         *string          `json:"provider_email,omitempty"`
	ProviderEmailVerified *bool            `json:"provider_email_verified,omitempty"`
	AccountVerified       *bool            `json:"account_verified,omitempty"`
	AccessToken           *string          `json:"access_token,omitempty"`
	RefreshToken          *string          `json:"refresh_token,omitempty"`
	TokenExpiresAt        *time.Time       `json:"token_expires_at,omitempty"`
	TokenExpiresAtAfter   *time.Time       `json:"token_expires_at_after,omitempty"`
	TokenExpiresAtBefore  *time.Time       `json:"token_expires_at_before,omitempty"`
	TokenType             *string          `json:"token_type,omitempty"`
	Scope                 *string          `json:"scope,omitempty"`
	IDToken               *string          `json:"id_token,omitempty"`
	ProfileData           *json.RawMessage `json:"profile_data,omitempty"`
	LinkedAt              *time.Time       `json:"linked_at,omitempty"`
	LinkedAtAfter         *time.Time       `json:"linked_at_after,omitempty"`
	LinkedAtBefore        *time.Time       `json:"linked_at_before,omitempty"`
	CreatedAt             *time.Time       `json:"created_at,omitempty"`
	CreatedAtAfter        *time.Time       `json:"created_at_after,omitempty"`
	CreatedAtBefore       *time.Time       `json:"created_at_before,omitempty"`
	UpdatedAt             *time.Time       `json:"updated_at,omitempty"`
	UpdatedAtAfter        *time.Time       `json:"updated_at_after,omitempty"`
	UpdatedAtBefore       *time.Time       `json:"updated_at_before,omitempty"`
	SearchTerm            *string          `json:"search_term,omitempty"`

	// AuthorizedIDs restricts results to the given primary key values.
	// Set by the bridge layer for prefilter authorization (authorization-scoped listings).
	// Nil means unrestricted (admin bypass). Empty non-nil means no access.
	AuthorizedIDs []string `json:"-"`
}

// =============================================================================
// Custom result structs
// =============================================================================

// =============================================================================
// Event structs
// =============================================================================

// =============================================================================
// Cursor helpers
// =============================================================================

func EncodeOauthAccountCursor(record OauthAccount, orderField string) (string, error) {
	orderValue := GetOauthAccountOrderValue(record, orderField)
	return fop.EncodeCursor(orderField, orderValue, record.OauthAccountID)
}

func GetOauthAccountOrderValue(record OauthAccount, field string) any {
	switch field {
	case "oauth_account_id":
		return record.OauthAccountID
	case "parent_user_id":
		return record.ParentUserID
	case "provider":
		return record.Provider
	case "provider_user_id":
		return record.ProviderUserID
	case "provider_email":
		return record.ProviderEmail
	case "provider_email_verified":
		return record.ProviderEmailVerified
	case "account_verified":
		return record.AccountVerified
	case "access_token":
		return record.AccessToken
	case "refresh_token":
		return record.RefreshToken
	case "token_expires_at":
		return record.TokenExpiresAt
	case "token_type":
		return record.TokenType
	case "scope":
		return record.Scope
	case "id_token":
		return record.IDToken
	case "profile_data":
		return record.ProfileData
	case "linked_at":
		return record.LinkedAt
	case "created_at":
		return record.CreatedAt
	case "updated_at":
		return record.UpdatedAt
	default:
		return record.OauthAccountID
	}
}

// =============================================================================
// Repository methods (generated from queries.sql)
// =============================================================================

// List queries the store and wraps the result with pagination metadata.
func (r *Repository) List(ctx context.Context, filter FilterList, parentUserID string, orderBy fop.Order, page fop.PageStringCursor) ([]OauthAccount, fop.Pagination, error) {
	if orderBy.Field == "" {
		orderBy = fop.NewOrder(DefaultOrderBy, DefaultOrderDirection)
	}
	orderField := orderBy.Field

	// Over-fetch by one to detect next page.
	listPage := fop.PageStringCursor{
		Limit:  page.Limit + 1,
		Cursor: page.Cursor,
	}

	records, err := r.store.List(ctx, filter, parentUserID, orderBy, listPage, false)
	if err != nil {
		return nil, fop.Pagination{}, fmt.Errorf("query: %w", err)
	}

	returnableRecords := records
	nextCursor := ""

	if len(records) > page.Limit {
		returnableRecords = records[:page.Limit]
		lastRecord := returnableRecords[len(returnableRecords)-1]
		nextCursor, err = EncodeOauthAccountCursor(lastRecord, orderField)
		if err != nil {
			return nil, fop.Pagination{}, fmt.Errorf("encode next cursor: %w", err)
		}
	}

	pagination := fop.Pagination{
		Limit:      page.Limit,
		NextCursor: nextCursor,
		PageTotal:  len(returnableRecords),
	}

	// Check for previous page when a cursor was provided.
	if page.Cursor != "" {
		prevRecords, err := r.store.List(ctx, filter, parentUserID, orderBy, page, true)
		if err == nil && len(prevRecords) > 0 {
			pagination.HasPrev = true
			if len(prevRecords) == page.Limit {
				firstRecord := prevRecords[0]
				pagination.PreviousCursor, err = EncodeOauthAccountCursor(firstRecord, orderField)
				if err != nil {
					return nil, fop.Pagination{}, fmt.Errorf("encode prev cursor: %w", err)
				}
			}
		}
	}

	return returnableRecords, pagination, nil
}

// Get delegates to the store.
func (r *Repository) Get(ctx context.Context, oauthAccountID string, parentUserID string) (OauthAccount, error) {
	result, err := r.store.Get(ctx, oauthAccountID, parentUserID)
	if err != nil {
		return OauthAccount{}, fmt.Errorf("get: %w", err)
	}
	return result, nil
}

// Create generates an ID, sets defaults, and delegates to the store.
func (r *Repository) Create(ctx context.Context, input CreateOauthAccount) (OauthAccount, error) {
	if input.OauthAccountID == "" {
		id, err := r.generateID()
		if err != nil {
			return OauthAccount{}, fmt.Errorf("generate id: %w", err)
		}
		input.OauthAccountID = id
	}
	result, err := r.store.Create(ctx, input)
	if err != nil {
		return OauthAccount{}, fmt.Errorf("create: %w", err)
	}
	return result, nil
}

// Update delegates to the store.
func (r *Repository) Update(ctx context.Context, oauthAccountID string, parentUserID string, input UpdateOauthAccount) (OauthAccount, error) {
	result, err := r.store.Update(ctx, oauthAccountID, parentUserID, input)
	if err != nil {
		return OauthAccount{}, fmt.Errorf("update: %w", err)
	}
	return result, nil
}

// Delete delegates to the store.
func (r *Repository) Delete(ctx context.Context, oauthAccountID string, parentUserID string) error {
	if err := r.store.Delete(ctx, oauthAccountID, parentUserID); err != nil {
		return fmt.Errorf("delete: %w", err)
	}
	return nil
}

// Ensure imports are used.
var _ = time.Time{}
var _ = fop.Order{}
var _ context.Context
var _ events.Event
