// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.
//
// Unit tests for the generated request-model Validate methods: each negative
// case mutates exactly one field on a known-valid baseline. Pure Go — no
// build tag, no infrastructure.

package principalsbridge

import (
	"strings"
	"testing"
)

func testPtr[T any](v T) *T { return &v }

func validCreatePrincipalRequest() CreatePrincipalRequest {
	return CreatePrincipalRequest{
		PrincipalType: "ok",
	}
}

func TestCreatePrincipalRequestValidate(t *testing.T) {
	t.Run("valid request passes", func(t *testing.T) {
		r := validCreatePrincipalRequest()
		if err := r.Validate(); err != nil {
			t.Fatalf("valid request: unexpected error: %v", err)
		}
	})
	t.Run("missing required principal_type", func(t *testing.T) {
		r := validCreatePrincipalRequest()
		r.PrincipalType = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("principal_type rejects value over max length", func(t *testing.T) {
		r := validCreatePrincipalRequest()
		r.PrincipalType = strings.Repeat("a", 65)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
}

func TestUpdatePrincipalRequestValidate(t *testing.T) {
	t.Run("empty update passes", func(t *testing.T) {
		r := UpdatePrincipalRequest{}
		if err := r.Validate(); err != nil {
			t.Fatalf("empty update: unexpected error: %v", err)
		}
	})
	t.Run("update principal_type rejects value over max length", func(t *testing.T) {
		r := UpdatePrincipalRequest{}
		r.PrincipalType = testPtr(strings.Repeat("a", 65))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
}
