// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package rebacrelationships

import (
	"context"
	"fmt"
	"time"

	"github.com/gopernicus/gopernicus/infrastructure/events"
	"github.com/gopernicus/gopernicus/sdk/errs"
	"github.com/gopernicus/gopernicus/sdk/fop"
)

// =============================================================================
// Errors
// =============================================================================

var (
	ErrRebacRelationshipNotFound         = fmt.Errorf("rebacrelationship: %w", errs.ErrNotFound)
	ErrRebacRelationshipAlreadyExists    = fmt.Errorf("rebacrelationship: %w", errs.ErrAlreadyExists)
	ErrRebacRelationshipInvalidReference = fmt.Errorf("rebacrelationship: %w", errs.ErrInvalidReference)
	ErrRebacRelationshipInvalidInput     = fmt.Errorf("rebacrelationship: %w", errs.ErrInvalidInput)
)

// =============================================================================
// OrderBy constants
// =============================================================================

const (
	OrderByPK              = "relationship_id"
	OrderByResourceType    = "resource_type"
	OrderByResourceID      = "resource_id"
	OrderByRelation        = "relation"
	OrderBySubjectType     = "subject_type"
	OrderBySubjectID       = "subject_id"
	OrderBySubjectRelation = "subject_relation"
	OrderByCreatedAt       = "created_at"
)

// OrderByFields maps user-facing field names to OrderField definitions.
var OrderByFields = map[string]fop.OrderField{
	OrderByPK:              {Column: "relationship_id"},
	OrderByResourceType:    {Column: "resource_type", CastLower: true},
	OrderByResourceID:      {Column: "resource_id", CastLower: true},
	OrderByRelation:        {Column: "relation", CastLower: true},
	OrderBySubjectType:     {Column: "subject_type", CastLower: true},
	OrderBySubjectID:       {Column: "subject_id", CastLower: true},
	OrderBySubjectRelation: {Column: "subject_relation", CastLower: true},
	OrderByCreatedAt:       {Column: "created_at"},
}

// =============================================================================
// Max page limits (from @max annotations)
// =============================================================================

const MaxLimitList = 100
const MaxLimitListBySubject = 100
const MaxLimitListByResource = 100

// =============================================================================
// Entity struct
// =============================================================================

// RebacRelationship is the database entity.
type RebacRelationship struct {
	RelationshipID  string    `json:"relationship_id" db:"relationship_id"`
	ResourceType    string    `json:"resource_type" db:"resource_type"`
	ResourceID      string    `json:"resource_id" db:"resource_id"`
	Relation        string    `json:"relation" db:"relation"`
	SubjectType     string    `json:"subject_type" db:"subject_type"`
	SubjectID       string    `json:"subject_id" db:"subject_id"`
	SubjectRelation *string   `json:"subject_relation" db:"subject_relation"`
	CreatedAt       time.Time `json:"created_at" db:"created_at"`
}

// =============================================================================
// Input structs
// =============================================================================

// CreateRebacRelationship is the input for creating a rebac_relationship.
type CreateRebacRelationship struct {
	RelationshipID  string  `json:"relationship_id,omitempty"`
	ResourceType    string  `json:"resource_type,omitempty"`
	ResourceID      string  `json:"resource_id,omitempty"`
	Relation        string  `json:"relation,omitempty"`
	SubjectType     string  `json:"subject_type,omitempty"`
	SubjectID       string  `json:"subject_id,omitempty"`
	SubjectRelation *string `json:"subject_relation,omitempty"`
}

// UpdateRebacRelationship is the input for updating a rebac_relationship.
type UpdateRebacRelationship struct {
	ResourceType    *string `json:"resource_type,omitempty"`
	ResourceID      *string `json:"resource_id,omitempty"`
	Relation        *string `json:"relation,omitempty"`
	SubjectType     *string `json:"subject_type,omitempty"`
	SubjectID       *string `json:"subject_id,omitempty"`
	SubjectRelation *string `json:"subject_relation,omitempty"`
}

// =============================================================================
// Filter structs
// =============================================================================

// FilterList holds filter criteria for List.
type FilterList struct {
	RelationshipID  *string    `json:"relationship_id,omitempty"`
	ResourceType    *string    `json:"resource_type,omitempty"`
	ResourceID      *string    `json:"resource_id,omitempty"`
	Relation        *string    `json:"relation,omitempty"`
	SubjectType     *string    `json:"subject_type,omitempty"`
	SubjectID       *string    `json:"subject_id,omitempty"`
	SubjectRelation *string    `json:"subject_relation,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	CreatedAtAfter  *time.Time `json:"created_at_after,omitempty"`
	CreatedAtBefore *time.Time `json:"created_at_before,omitempty"`
	SearchTerm      *string    `json:"search_term,omitempty"`

	// AuthorizedIDs restricts results to the given primary key values.
	// Set by the bridge layer for prefilter authorization (authorization-scoped listings).
	// Nil means unrestricted (admin bypass). Empty non-nil means no access.
	AuthorizedIDs []string `json:"-"`
}

// FilterListBySubject holds filter criteria for ListBySubject.
type FilterListBySubject struct {
	ResourceType *string `json:"resource_type,omitempty"`
	Relation     *string `json:"relation,omitempty"`
	SearchTerm   *string `json:"search_term,omitempty"`

	// AuthorizedIDs restricts results to the given primary key values.
	// Set by the bridge layer for prefilter authorization (authorization-scoped listings).
	// Nil means unrestricted (admin bypass). Empty non-nil means no access.
	AuthorizedIDs []string `json:"-"`
}

// FilterListByResource holds filter criteria for ListByResource.
type FilterListByResource struct {
	SubjectType *string `json:"subject_type,omitempty"`
	Relation    *string `json:"relation,omitempty"`
	SearchTerm  *string `json:"search_term,omitempty"`

	// AuthorizedIDs restricts results to the given primary key values.
	// Set by the bridge layer for prefilter authorization (authorization-scoped listings).
	// Nil means unrestricted (admin bypass). Empty non-nil means no access.
	AuthorizedIDs []string `json:"-"`
}

// =============================================================================
// Custom result structs
// =============================================================================

// =============================================================================
// Event structs
// =============================================================================

// =============================================================================
// Cursor helpers
// =============================================================================

func EncodeRebacRelationshipCursor(record RebacRelationship, orderField string) (string, error) {
	orderValue := GetRebacRelationshipOrderValue(record, orderField)
	return fop.EncodeCursor(orderField, orderValue, record.RelationshipID)
}

func GetRebacRelationshipOrderValue(record RebacRelationship, field string) any {
	switch field {
	case "relationship_id":
		return record.RelationshipID
	case "resource_type":
		return record.ResourceType
	case "resource_id":
		return record.ResourceID
	case "relation":
		return record.Relation
	case "subject_type":
		return record.SubjectType
	case "subject_id":
		return record.SubjectID
	case "subject_relation":
		return record.SubjectRelation
	case "created_at":
		return record.CreatedAt
	default:
		return record.RelationshipID
	}
}

// =============================================================================
// Repository methods (generated from queries.sql)
// =============================================================================

// List queries the store and wraps the result with pagination metadata.
func (r *Repository) List(ctx context.Context, filter FilterList, orderBy fop.Order, page fop.PageStringCursor) ([]RebacRelationship, fop.Pagination, error) {
	if orderBy.Field == "" {
		orderBy = fop.NewOrder(DefaultOrderBy, DefaultOrderDirection)
	}
	orderField := orderBy.Field

	// Over-fetch by one to detect next page.
	listPage := fop.PageStringCursor{
		Limit:  page.Limit + 1,
		Cursor: page.Cursor,
	}

	records, err := r.store.List(ctx, filter, orderBy, listPage, false)
	if err != nil {
		return nil, fop.Pagination{}, fmt.Errorf("query: %w", err)
	}

	returnableRecords := records
	nextCursor := ""

	if len(records) > page.Limit {
		returnableRecords = records[:page.Limit]
		lastRecord := returnableRecords[len(returnableRecords)-1]
		nextCursor, err = EncodeRebacRelationshipCursor(lastRecord, orderField)
		if err != nil {
			return nil, fop.Pagination{}, fmt.Errorf("encode next cursor: %w", err)
		}
	}

	pagination := fop.Pagination{
		Limit:      page.Limit,
		NextCursor: nextCursor,
		PageTotal:  len(returnableRecords),
	}

	// Check for previous page when a cursor was provided.
	if page.Cursor != "" {
		prevRecords, err := r.store.List(ctx, filter, orderBy, page, true)
		if err == nil && len(prevRecords) > 0 {
			pagination.HasPrev = true
			if len(prevRecords) == page.Limit {
				firstRecord := prevRecords[0]
				pagination.PreviousCursor, err = EncodeRebacRelationshipCursor(firstRecord, orderField)
				if err != nil {
					return nil, fop.Pagination{}, fmt.Errorf("encode prev cursor: %w", err)
				}
			}
		}
	}

	return returnableRecords, pagination, nil
}

// Get delegates to the store.
func (r *Repository) Get(ctx context.Context, relationshipID string) (RebacRelationship, error) {
	result, err := r.store.Get(ctx, relationshipID)
	if err != nil {
		return RebacRelationship{}, fmt.Errorf("get: %w", err)
	}
	return result, nil
}

// Create generates an ID, sets defaults, and delegates to the store.
func (r *Repository) Create(ctx context.Context, input CreateRebacRelationship) (RebacRelationship, error) {
	if input.RelationshipID == "" {
		id, err := r.generateID()
		if err != nil {
			return RebacRelationship{}, fmt.Errorf("generate id: %w", err)
		}
		input.RelationshipID = id
	}
	result, err := r.store.Create(ctx, input)
	if err != nil {
		return RebacRelationship{}, fmt.Errorf("create: %w", err)
	}
	return result, nil
}

// Update delegates to the store.
func (r *Repository) Update(ctx context.Context, relationshipID string, input UpdateRebacRelationship) (RebacRelationship, error) {
	result, err := r.store.Update(ctx, relationshipID, input)
	if err != nil {
		return RebacRelationship{}, fmt.Errorf("update: %w", err)
	}
	return result, nil
}

// Delete delegates to the store.
func (r *Repository) Delete(ctx context.Context, relationshipID string) error {
	if err := r.store.Delete(ctx, relationshipID); err != nil {
		return fmt.Errorf("delete: %w", err)
	}
	return nil
}

// ListBySubject queries the store and wraps the result with pagination metadata.
func (r *Repository) ListBySubject(ctx context.Context, filter FilterListBySubject, subjectType string, subjectID string, orderBy fop.Order, page fop.PageStringCursor) ([]RebacRelationship, fop.Pagination, error) {
	if orderBy.Field == "" {
		orderBy = fop.NewOrder(DefaultOrderBy, DefaultOrderDirection)
	}
	orderField := orderBy.Field

	// Over-fetch by one to detect next page.
	listPage := fop.PageStringCursor{
		Limit:  page.Limit + 1,
		Cursor: page.Cursor,
	}

	records, err := r.store.ListBySubject(ctx, filter, subjectType, subjectID, orderBy, listPage, false)
	if err != nil {
		return nil, fop.Pagination{}, fmt.Errorf("query: %w", err)
	}

	returnableRecords := records
	nextCursor := ""

	if len(records) > page.Limit {
		returnableRecords = records[:page.Limit]
		lastRecord := returnableRecords[len(returnableRecords)-1]
		nextCursor, err = EncodeRebacRelationshipCursor(lastRecord, orderField)
		if err != nil {
			return nil, fop.Pagination{}, fmt.Errorf("encode next cursor: %w", err)
		}
	}

	pagination := fop.Pagination{
		Limit:      page.Limit,
		NextCursor: nextCursor,
		PageTotal:  len(returnableRecords),
	}

	// Check for previous page when a cursor was provided.
	if page.Cursor != "" {
		prevRecords, err := r.store.ListBySubject(ctx, filter, subjectType, subjectID, orderBy, page, true)
		if err == nil && len(prevRecords) > 0 {
			pagination.HasPrev = true
			if len(prevRecords) == page.Limit {
				firstRecord := prevRecords[0]
				pagination.PreviousCursor, err = EncodeRebacRelationshipCursor(firstRecord, orderField)
				if err != nil {
					return nil, fop.Pagination{}, fmt.Errorf("encode prev cursor: %w", err)
				}
			}
		}
	}

	return returnableRecords, pagination, nil
}

// ListByResource queries the store and wraps the result with pagination metadata.
func (r *Repository) ListByResource(ctx context.Context, filter FilterListByResource, resourceType string, resourceID string, orderBy fop.Order, page fop.PageStringCursor) ([]RebacRelationship, fop.Pagination, error) {
	if orderBy.Field == "" {
		orderBy = fop.NewOrder(DefaultOrderBy, DefaultOrderDirection)
	}
	orderField := orderBy.Field

	// Over-fetch by one to detect next page.
	listPage := fop.PageStringCursor{
		Limit:  page.Limit + 1,
		Cursor: page.Cursor,
	}

	records, err := r.store.ListByResource(ctx, filter, resourceType, resourceID, orderBy, listPage, false)
	if err != nil {
		return nil, fop.Pagination{}, fmt.Errorf("query: %w", err)
	}

	returnableRecords := records
	nextCursor := ""

	if len(records) > page.Limit {
		returnableRecords = records[:page.Limit]
		lastRecord := returnableRecords[len(returnableRecords)-1]
		nextCursor, err = EncodeRebacRelationshipCursor(lastRecord, orderField)
		if err != nil {
			return nil, fop.Pagination{}, fmt.Errorf("encode next cursor: %w", err)
		}
	}

	pagination := fop.Pagination{
		Limit:      page.Limit,
		NextCursor: nextCursor,
		PageTotal:  len(returnableRecords),
	}

	// Check for previous page when a cursor was provided.
	if page.Cursor != "" {
		prevRecords, err := r.store.ListByResource(ctx, filter, resourceType, resourceID, orderBy, page, true)
		if err == nil && len(prevRecords) > 0 {
			pagination.HasPrev = true
			if len(prevRecords) == page.Limit {
				firstRecord := prevRecords[0]
				pagination.PreviousCursor, err = EncodeRebacRelationshipCursor(firstRecord, orderField)
				if err != nil {
					return nil, fop.Pagination{}, fmt.Errorf("encode prev cursor: %w", err)
				}
			}
		}
	}

	return returnableRecords, pagination, nil
}

// DeleteAllForResource delegates to the store.
func (r *Repository) DeleteAllForResource(ctx context.Context, resourceType string, resourceID string) error {
	if err := r.store.DeleteAllForResource(ctx, resourceType, resourceID); err != nil {
		return fmt.Errorf("delete all for resource: %w", err)
	}
	return nil
}

// DeleteByTuple delegates to the store.
func (r *Repository) DeleteByTuple(ctx context.Context, resourceType string, resourceID string, relation string, subjectType string, subjectID string) error {
	if err := r.store.DeleteByTuple(ctx, resourceType, resourceID, relation, subjectType, subjectID); err != nil {
		return fmt.Errorf("delete by tuple: %w", err)
	}
	return nil
}

// DeleteByResourceAndSubject delegates to the store.
func (r *Repository) DeleteByResourceAndSubject(ctx context.Context, resourceType string, resourceID string, subjectType string, subjectID string) error {
	if err := r.store.DeleteByResourceAndSubject(ctx, resourceType, resourceID, subjectType, subjectID); err != nil {
		return fmt.Errorf("delete by resource and subject: %w", err)
	}
	return nil
}

// DeleteBySubject delegates to the store.
func (r *Repository) DeleteBySubject(ctx context.Context, subjectType string, subjectID string) error {
	if err := r.store.DeleteBySubject(ctx, subjectType, subjectID); err != nil {
		return fmt.Errorf("delete by subject: %w", err)
	}
	return nil
}

// Ensure imports are used.
var _ = time.Time{}
var _ = fop.Order{}
var _ context.Context
var _ events.Event
