//go:build e2e

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gopernicus/gopernicus/core/testing/fixtures"
	"github.com/gopernicus/gopernicus/infrastructure/cryptids"
	"github.com/gopernicus/gopernicus/workshop/testing/testhttp"
)

// Ensure imports are used.
var (
	_ = assert.Equal
	_ = require.NoError
	_ = cryptids.GenerateID
)

func TestGeneratedSecurityEvent_Get(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestSecurityEventWithDefaults(t, ctx, db)

	t.Run("found", func(t *testing.T) {
		resp := client.Get(t, "/security-events/{event_id}")
		resp.RequireStatus(t, 200)
		assert.Equal(t, created.EventID, resp.String(t, "event_id"))
	})

	t.Run("not found", func(t *testing.T) {
		resp := client.Get(t, "/security-events/{event_id}")
		resp.RequireStatus(t, 404)
	})
}

func TestGeneratedSecurityEvent_List(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	for i := 0; i < 3; i++ {
		fixtures.CreateTestSecurityEventWithDefaults(t, ctx, db)
	}

	resp := client.Get(t, "/security-events")
	resp.RequireStatus(t, 200)
	assert.GreaterOrEqual(t, resp.DataLen(t), 3)
}
