//go:build e2e

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gopernicus/gopernicus/core/testing/fixtures"
	"github.com/gopernicus/gopernicus/infrastructure/cryptids"
	"github.com/gopernicus/gopernicus/workshop/testing/testhttp"
)

// Ensure imports are used.
var (
	_ = assert.Equal
	_ = require.NoError
	_ = cryptids.GenerateID
)

func TestGeneratedSession_Create(t *testing.T) {
	_, _, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())
	// TODO: Set authentication if routes require it.
	// client.SetBearerToken(token)

	testUniqueID, err := cryptids.GenerateID()
	require.NoError(t, err)
	_ = testUniqueID

	body := map[string]any{
		"session_token_hash": "e2e_test_session_token_hash_" + testUniqueID,
	}

	resp := client.Post(t, "/sessions", body)
	resp.RequireStatus(t, 201)

	createdID := resp.String(t, "session_id")
	assert.NotEmpty(t, createdID)

	// Verify via GET.
	getResp := client.Get(t, "/sessions/{session_id}")
	getResp.RequireStatus(t, 200)
	assert.Equal(t, createdID, getResp.String(t, "session_id"))
}

func TestGeneratedSession_Get(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestSessionWithDefaults(t, ctx, db)

	t.Run("found", func(t *testing.T) {
		resp := client.Get(t, "/sessions/{session_id}")
		resp.RequireStatus(t, 200)
		assert.Equal(t, created.SessionID, resp.String(t, "session_id"))
	})

	t.Run("not found", func(t *testing.T) {
		resp := client.Get(t, "/sessions/{session_id}")
		resp.RequireStatus(t, 404)
	})
}

func TestGeneratedSession_List(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	for i := 0; i < 3; i++ {
		fixtures.CreateTestSessionWithDefaults(t, ctx, db)
	}

	resp := client.Get(t, "/sessions")
	resp.RequireStatus(t, 200)
	assert.GreaterOrEqual(t, resp.DataLen(t), 3)
}

func TestGeneratedSession_Update(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestSessionWithDefaults(t, ctx, db)

	body := map[string]any{
		"session_token_hash": "updated_test_value",
	}

	resp := client.Put(t, "/sessions/{session_id}", body)
	resp.RequireStatus(t, 200)

	// Verify via GET.
	getResp := client.Get(t, "/sessions/{session_id}")
	getResp.RequireStatus(t, 200)
}

func TestGeneratedSession_Delete(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestSessionWithDefaults(t, ctx, db)

	resp := client.Delete(t, "/sessions/{session_id}")
	resp.RequireStatus(t, 204)

	// Verify it's gone.
	getResp := client.Get(t, "/sessions/{session_id}")
	getResp.AssertStatus(t, 404)

}
