//go:build e2e

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gopernicus/gopernicus/core/testing/fixtures"
	"github.com/gopernicus/gopernicus/infrastructure/cryptids"
	"github.com/gopernicus/gopernicus/workshop/testing/testhttp"
)

// Ensure imports are used.
var (
	_ = assert.Equal
	_ = require.NoError
	_ = cryptids.GenerateID
)

func TestGeneratedUser_Get(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestUserWithDefaults(t, ctx, db)

	t.Run("found", func(t *testing.T) {
		resp := client.Get(t, "/users/{user_id}")
		resp.RequireStatus(t, 200)
		assert.Equal(t, created.UserID, resp.String(t, "user_id"))
	})

	t.Run("not found", func(t *testing.T) {
		resp := client.Get(t, "/users/{user_id}")
		resp.RequireStatus(t, 404)
	})
}

func TestGeneratedUser_List(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	for i := 0; i < 3; i++ {
		fixtures.CreateTestUserWithDefaults(t, ctx, db)
	}

	resp := client.Get(t, "/users")
	resp.RequireStatus(t, 200)
	assert.GreaterOrEqual(t, resp.DataLen(t), 3)
}

func TestGeneratedUser_Update(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestUserWithDefaults(t, ctx, db)

	body := map[string]any{
		"email": "updated_test_value",
	}

	resp := client.Put(t, "/users/{user_id}", body)
	resp.RequireStatus(t, 200)

	// Verify via GET.
	getResp := client.Get(t, "/users/{user_id}")
	getResp.RequireStatus(t, 200)
}

func TestGeneratedUser_SoftDelete(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestUserWithDefaults(t, ctx, db)

	resp := client.Put(t, "/users/{user_id}/delete", nil)
	resp.RequireStatus(t, 204)
}

func TestGeneratedUser_Archive(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestUserWithDefaults(t, ctx, db)

	resp := client.Put(t, "/users/{user_id}/archive", nil)
	resp.RequireStatus(t, 204)
}

func TestGeneratedUser_Restore(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestUserWithDefaults(t, ctx, db)

	// Archive first, then restore.
	archiveResp := client.Put(t, "/users/{user_id}/archive", nil)
	archiveResp.RequireStatus(t, 204)

	resp := client.Put(t, "/users/{user_id}/restore", nil)
	resp.RequireStatus(t, 204)
}

func TestGeneratedUser_Delete(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestUserWithDefaults(t, ctx, db)

	resp := client.Delete(t, "/users/{user_id}")
	resp.RequireStatus(t, 204)

	// Verify it's gone.
	getResp := client.Get(t, "/users/{user_id}")
	getResp.AssertStatus(t, 404)

}
