package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/gopernicus/gopernicus/pockets/authorization/logic/tuples"

	"github.com/gopernicus/gopernicus/pockets/authorization/logic/decisions"

	authorization "github.com/gopernicus/gopernicus/pockets/authorization"
	audit2 "github.com/gopernicus/gopernicus/pockets/authorization/logic/audit"
	authzmem "github.com/gopernicus/gopernicus/pockets/authorization/stores/memory"
	"github.com/gopernicus/gopernicus/sdk"
	"github.com/gopernicus/gopernicus/sdk/pkg/list"

	// -----------------------------------------------------------------------------
	// Recording apparatus
	// -----------------------------------------------------------------------------
	model "github.com/gopernicus/gopernicus/pockets/authorization/logic/model"
	mutations "github.com/gopernicus/gopernicus/pockets/authorization/logic/mutations"
	relationships "github.com/gopernicus/gopernicus/pockets/authorization/logic/relationships"
)

const proofTranscriptPath = "testdata/az3-proof-transcript.md"

// proofSection is one numbered protocol point's recorded evidence.
type proofSection struct {
	n     int
	title string
	lines []string
}

// proofTranscript accumulates the twelve sections and renders the artifact.
type proofTranscript struct {
	mu       sync.Mutex
	sections []proofSection
}

func (t *proofTranscript) add(n int, title string, lines ...string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	for i := range t.sections {
		if t.sections[i].n == n {
			t.sections[i].lines = append(t.sections[i].lines, lines...)
			return
		}
	}
	t.sections = append(t.sections, proofSection{n: n, title: title, lines: lines})
}

func (t *proofTranscript) render() string {
	t.mu.Lock()
	defer t.mu.Unlock()
	sort.Slice(t.sections, func(i, j int) bool { return t.sections[i].n < t.sections[j].n })

	var b strings.Builder
	b.WriteString("# Authorization v3 — AZ3-4.2 exact-semantics and concurrency proof transcript\n\n")
	b.WriteString("Generated by `go test -run TestAZ3ProofProtocol` in `examples/auth-cms/cmd/server`.\n")
	b.WriteString("This is a recorded artifact: each section below was OBSERVED in a real protocol run\n")
	b.WriteString("over the auth-cms host composition (the AZ3-4.1 memstore bundle under\n")
	b.WriteString("authzGuardianPolicy, the hostMutationGuard, and the separately held SystemMutator)\n")
	b.WriteString("with optional atomic audit recording enabled.\n\n")
	b.WriteString("History contains committed fact changes, including trusted setup. Guard denials, no-ops and failed writes add no entries.\n\n")
	for _, s := range t.sections {
		fmt.Fprintf(&b, "## %d. %s\n\n", s.n, s.title)
		for _, ln := range s.lines {
			fmt.Fprintf(&b, "- %s\n", ln)
		}
		b.WriteString("\n")
	}
	return b.String()
}

// capturedHistory reads the same committed records a host would display.
type capturedHistory struct {
	reader audit2.Reader
	t      *testing.T
}

func (c *capturedHistory) all() []audit2.Record {
	c.t.Helper()
	page, err := c.reader.List(context.Background(), audit2.Filter{}, list.Request{Limit: 100, Order: list.Order{Field: "occurred_at", Direction: list.ASC}})
	if err != nil {
		c.t.Fatal(err)
	}
	return page.Items
}

func auditLines(records []audit2.Record) []string {
	out := make([]string, 0, len(records))
	for _, e := range records {
		source := e.Source.System
		if source == "" {
			source = e.Source.ActorType + ":" + e.Source.ActorID
		}
		row := e.Change.Tuple
		fact := fmt.Sprintf("scope=%v:%s:%s#%s <- %s:%s#%s", row.Scope.Kind, row.Scope.Type, row.Scope.ID, row.Relation, row.Subject.Type, row.Subject.ID, row.Subject.Relation)
		out = append(out, fmt.Sprintf("audit: %s %s; source=%s; reason=%s", e.Change.Action, fact, source, e.Source.Reason))
	}
	return out
}

// -----------------------------------------------------------------------------
// Composition and command helpers
// -----------------------------------------------------------------------------

func proofComposition(t *testing.T, schema decisions.Model, history *capturedHistory) authorization.Components {
	t.Helper()
	// Small proof models omit the project's protected scope. Install its rule
	// only in fixtures that declare that resource type.
	policy := mutations.GuardianPolicy{}
	if _, ok := schema.ResourceTypes[demoResourceType]; ok {
		policy = authzGuardianPolicy()
	}
	store := authzmem.New(authzmem.WithGuardianPolicy(policy), authzmem.WithAudit())
	if history != nil {
		history.reader = store.Audit()
		history.t = t
	}
	comps, err := authorization.New(authorization.Repositories{
		Tuples:    store.Tuples(),
		Mutations: store.Mutations(),
	}, authorization.WithModel(schema), authorization.WithGuard(hostMutationGuard{}))
	if err != nil {
		t.Fatalf("proofComposition: %v", err)
	}
	return comps
}

func subj(t, id string) relationships.SubjectRef { return relationships.SubjectRef{Type: t, ID: id} }

func userset(t, id, relation string) relationships.SubjectRef {
	return relationships.SubjectRef{Type: t, ID: id, Relation: relation}
}

func trustGrant(t *testing.T, sm *mutations.SystemMutator, rt, rid, rel string, s relationships.SubjectRef) {
	t.Helper()
	if _, err := sm.GrantRelationship(proofSystemContext(), mutations.GrantRelationshipCommand{

		ResourceType: rt, ResourceID: rid, Relation: rel, Subject: s,
	}); err != nil {
		t.Fatalf("trustGrant %s:%s#%s <- %s:%s#%s: %v", rt, rid, rel, s.Type, s.ID, s.Relation, err)
	}
}

func proofActor(userID string) mutations.Actor {
	return mutations.Actor{PrincipalRef: model.PrincipalRef{Type: "user", ID: userID}}
}

// check is a small read helper for the transcript's stored-state observations.
func check(t *testing.T, svc authorization.Components, userID, permission, resourceType, resourceID string) bool {
	t.Helper()
	res, err := svc.Decisions.Check(context.Background(), model.CheckRequest{
		Principal:  model.PrincipalRef{Type: "user", ID: userID},
		Permission: permission,
		Resource:   model.Resource{Type: resourceType, ID: resourceID},
	})
	if err != nil {
		t.Fatalf("Check(%s, %s, %s:%s): %v", userID, permission, resourceType, resourceID, err)
	}
	return res.Allowed
}

// -----------------------------------------------------------------------------
// Proof schemas
// -----------------------------------------------------------------------------

// proofUsersetSchema adds a userset-bearing group/doc pair to the host's project +
// platform types so the real hostMutationGuard (manage_access = owner) authorizes a
// manager granting an exact userset subject on a doc.
func proofUsersetSchema() decisions.Model {
	return decisions.NewSchema([]decisions.ResourceSchema{
		{Name: "platform", Def: decisions.ResourceTypeDef{
			Relations:   map[string]decisions.RelationDef{"admin": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "user"}}}},
			Permissions: map[string]decisions.Expression{"admin": decisions.AnyOf(decisions.Direct("admin"))},
		}},
		{Name: "group", Def: decisions.ResourceTypeDef{
			Relations: map[string]decisions.RelationDef{
				"member": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "user"}, {Type: "group", Relation: "member"}}},
				"admin":  {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "user"}}},
			},
		}},
		{Name: "doc", Def: decisions.ResourceTypeDef{
			Relations: map[string]decisions.RelationDef{
				"owner": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "user"}}},
				"viewer": {AllowedSubjects: []decisions.SubjectTypeRef{
					{Type: "user"},
					{Type: "group"},
					{Type: "group", Relation: "member"},
					{Type: "group", Relation: "admin"},
				}},
			},
			Permissions: map[string]decisions.Expression{
				"view":          decisions.AnyOf(decisions.Direct("viewer")),
				"manage_access": decisions.AnyOf(decisions.Direct("owner")),
			},
		}},
	})
}

// proofHierarchySchema is the non-self Through-root hierarchy: a space inherits
// `view` up its `parent` chain AND from its owning `org` (a NON-self Through). Used
// for point 6's Check/Lookup parity.
func proofHierarchySchema() decisions.Model {
	return decisions.NewSchema([]decisions.ResourceSchema{
		{Name: "org", Def: decisions.ResourceTypeDef{
			Relations:   map[string]decisions.RelationDef{"admin": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "user"}}}},
			Permissions: map[string]decisions.Expression{"view": decisions.AnyOf(decisions.Direct("admin"))},
		}},
		{Name: "space", Def: decisions.ResourceTypeDef{
			Relations: map[string]decisions.RelationDef{
				"parent": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "space"}}},
				"viewer": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "user"}}},
				"org":    {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "org"}}},
			},
			Permissions: map[string]decisions.Expression{
				"view": decisions.AnyOf(decisions.Direct("viewer"), decisions.Through("org", "view"), decisions.Through("parent", "view")),
			},
		}},
	})
}

// -----------------------------------------------------------------------------
// The protocol
// -----------------------------------------------------------------------------

// TestAZ3ProofProtocol drives the twelve-point exact-semantics/concurrency protocol
// and writes the recorded transcript artifact. Run it under -race.
func TestAZ3ProofProtocol(t *testing.T) {
	tr := &proofTranscript{}

	points := []struct {
		name string
		fn   func(*testing.T, *proofTranscript)
	}{
		{"01_ordinary_member_cannot_self_grant", proofPoint01},
		{"02_manager_grants_group_member_userset", proofPoint02},
		{"03_group_admin_grant_does_not_authorize_member", proofPoint03},
		{"04_decision_apis_reject_userset_callers", proofPoint04},
		{"05_through_rejects_userset_targets_at_compile", proofPoint05},
		{"06_nonself_through_root_check_lookup_parity", proofPoint06},
		{"07_global_role_in_effective_enumeration", proofPoint07},
		{"08_scoped_revoke_same_role_grant_remains", proofPoint08},
		{"09_concurrent_last_owner_revoke_single_winner", proofPoint09},
		{"10_conflict_leaves_history_unchanged", proofPoint10},
		{"11_repeat_uses_current_state", proofPoint11},
		{"12_teardown_only_via_system_mutator", proofPoint12},
	}
	for _, p := range points {
		t.Run(p.name, func(t *testing.T) { p.fn(t, tr) })
	}

	if err := os.MkdirAll(filepath.Dir(proofTranscriptPath), 0o755); err != nil {
		t.Fatalf("mkdir testdata: %v", err)
	}
	if err := os.WriteFile(proofTranscriptPath, []byte(tr.render()), 0o644); err != nil {
		t.Fatalf("write transcript: %v", err)
	}
	t.Logf("wrote proof transcript to %s (%d sections)", proofTranscriptPath, len(tr.sections))
}

// 1. An ordinary member cannot self-grant.
func proofPoint01(t *testing.T, tr *proofTranscript) {
	sink := &capturedHistory{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "project", "p1", "owner", subj("user", "manager"))
	trustGrant(t, sm, "project", "p1", "member", subj("user", "ordinary")) // trusted seed, not audited

	// The ordinary member attempts to self-grant owner (self-escalation).
	_, err := svc.Mutations.GrantRelationship(ctx, proofActor("ordinary"), mutations.GrantRelationshipCommand{
		ResourceType: "project", ResourceID: "p1",
		Relation: "owner", Subject: subj("user", "ordinary"),
	})
	if !errors.Is(err, sdk.ErrForbidden) {
		t.Fatalf("self-grant: want forbidden, got %v", err)
	}
	wroteOwner := check(t, svc, "ordinary", "manage_access", "project", "p1")
	if wroteOwner {
		t.Fatal("denied self-grant nonetheless wrote an owner row")
	}

	tr.add(1, "Ordinary member cannot self-grant",
		"command: Service.GrantRelationship(actor=user:ordinary, grant project:p1#owner <- user:ordinary)",
		fmt.Sprintf("result: rejected, errors.Is(sdk.ErrForbidden)=%v (guard denied before Apply)", errors.Is(err, sdk.ErrForbidden)),
		fmt.Sprintf("stored-row check: user:ordinary has manage_access on project:p1 = %v (no owner row committed)", wroteOwner),
	)
	tr.add(1, "Ordinary member cannot self-grant", auditLines(sink.all())...)
}

// 2. An authorized manager grants an exact group#member subject and a concrete
// member gains access.
func proofPoint02(t *testing.T, tr *proofTranscript) {
	sink := &capturedHistory{}
	comps := proofComposition(t, proofUsersetSchema(), sink)
	svc, sm := comps, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "group", "eng", "member", subj("user", "alice")) // alice is a member of group:eng
	trustGrant(t, sm, "doc", "d2", "owner", subj("user", "manager"))   // manager holds manage_access on doc:d2

	// The manager (authorized via manage_access) grants the exact group#member userset.
	rcpt, err := svc.Mutations.GrantRelationship(ctx, proofActor("manager"), mutations.GrantRelationshipCommand{
		ResourceType: "doc", ResourceID: "d2",
		Relation: "viewer", Subject: userset("group", "eng", "member"),
	})
	if err != nil || rcpt.Outcome != mutations.OutcomeApplied {
		t.Fatalf("manager userset grant: outcome=%v err=%v", outcomeOf(rcpt), err)
	}
	memberAllowed := check(t, svc, "alice", "view", "doc", "d2")
	if !memberAllowed {
		t.Fatal("concrete member of group:eng did not gain view via the group#member grant")
	}
	strangerAllowed := check(t, svc, "stranger", "view", "doc", "d2")
	if strangerAllowed {
		t.Fatal("a non-member gained access through the group#member userset")
	}

	// Stored-row observation: the viewer target is the EXACT userset (group:eng#member).
	targets, err := svc.Relationships.GetRelationTargets(ctx, "doc", "d2", "viewer")
	if err != nil {
		t.Fatalf("GetRelationTargets: %v", err)
	}
	digest := svc.Decisions.SchemaDigest()

	tr.add(2, "Authorized manager grants an exact group#member subject",
		"command: Service.GrantRelationship(actor=user:manager, grant doc:d2#viewer <- group:eng#member)",
		fmt.Sprintf("result: outcome=%s", rcpt.Outcome),
		fmt.Sprintf("live schema digest: %s (current model)", short(digest)),
		fmt.Sprintf("stored viewer target(s): %s", targetsString(targets)),
		fmt.Sprintf("Check(user:alice member-of-eng, view, doc:d2) = %v (member gains access)", memberAllowed),
		fmt.Sprintf("Check(user:stranger, view, doc:d2) = %v (non-member denied)", strangerAllowed),
	)
	tr.add(2, "Authorized manager grants an exact group#member subject", auditLines(sink.all())...)
}

// 3. A group#admin grant does not authorize an ordinary member.
func proofPoint03(t *testing.T, tr *proofTranscript) {
	sink := &capturedHistory{}
	comps := proofComposition(t, proofUsersetSchema(), sink)
	svc, sm := comps, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "group", "eng", "member", subj("user", "alice")) // ordinary member
	trustGrant(t, sm, "group", "eng", "admin", subj("user", "carol"))  // admin
	trustGrant(t, sm, "doc", "d3", "owner", subj("user", "manager"))

	// The manager grants the group#ADMIN userset on doc:d3#viewer.
	rcpt, err := svc.Mutations.GrantRelationship(ctx, proofActor("manager"), mutations.GrantRelationshipCommand{
		ResourceType: "doc", ResourceID: "d3",
		Relation: "viewer", Subject: userset("group", "eng", "admin"),
	})
	if err != nil || rcpt.Outcome != mutations.OutcomeApplied {
		t.Fatalf("manager admin-userset grant: outcome=%v err=%v", outcomeOf(rcpt), err)
	}
	memberAllowed := check(t, svc, "alice", "view", "doc", "d3") // member, NOT admin
	adminAllowed := check(t, svc, "carol", "view", "doc", "d3")  // admin
	if memberAllowed {
		t.Fatal("a group#admin grant authorized an ordinary member (cross-relation leak)")
	}
	if !adminAllowed {
		t.Fatal("a group#admin grant did not authorize the group admin")
	}

	tr.add(3, "A group#admin grant does not authorize an ordinary member",
		"command: Service.GrantRelationship(actor=user:manager, grant doc:d3#viewer <- group:eng#admin)",
		fmt.Sprintf("result: outcome=%s", rcpt.Outcome),
		fmt.Sprintf("Check(user:alice group:eng#member, view, doc:d3) = %v (member does NOT satisfy the admin userset)", memberAllowed),
		fmt.Sprintf("Check(user:carol group:eng#admin, view, doc:d3) = %v (admin satisfies it)", adminAllowed),
	)
	tr.add(3, "A group#admin grant does not authorize an ordinary member", auditLines(sink.all())...)
}

// 4. Decision APIs reject userset-valued callers.
func proofPoint04(t *testing.T, tr *proofTranscript) {
	sink := &capturedHistory{}
	comps := proofComposition(t, proofUsersetSchema(), sink)
	svc, sm := comps, comps.SystemMutator
	ctx := context.Background()

	// Structural proof: a decision request's caller (CheckRequest.Principal) is a
	// concrete PrincipalRef with only (Type, ID) — no Relation field a caller could
	// set to a userset. The STORED subject type (SubjectRef) is a DIFFERENT type that
	// does carry Relation, and no decision path accepts it.
	prinType := reflect.TypeOf(model.PrincipalRef{})
	crPrincipal, _ := reflect.TypeOf(model.CheckRequest{}).FieldByName("Principal")
	principalHasRelation := hasField(prinType, "Relation")
	subjectHasRelation := hasField(reflect.TypeOf(relationships.SubjectRef{}), "Relation")
	callerIsPrincipalRef := crPrincipal.Type == prinType

	// Driven proof: a caller is always the CONCRETE entity. A concrete-group grant
	// names the group entity itself, never its members — there is no way to ask "as
	// group#member".
	trustGrant(t, sm, "group", "eng", "member", subj("user", "alice"))
	trustGrant(t, sm, "doc", "dc", "owner", subj("user", "manager"))
	if _, err := svc.Mutations.GrantRelationship(ctx, proofActor("manager"), mutations.GrantRelationshipCommand{
		ResourceType: "doc", ResourceID: "dc",
		Relation: "viewer", Subject: subj("group", "eng"), // concrete group entity, no relation
	}); err != nil {
		t.Fatalf("concrete-group grant: %v", err)
	}
	concreteGroupAllowed := checkPrincipal(t, svc, "group", "eng", "view", "doc", "dc") // the group entity is the caller
	memberAsCallerAllowed := check(t, svc, "alice", "view", "doc", "dc")                // a member is NOT the concrete group

	if !callerIsPrincipalRef || principalHasRelation || !subjectHasRelation {
		t.Fatalf("structural: callerIsPrincipalRef=%v principalHasRelation=%v subjectHasRelation=%v",
			callerIsPrincipalRef, principalHasRelation, subjectHasRelation)
	}
	if !concreteGroupAllowed {
		t.Fatal("the concrete group entity (the only expressible group caller) was denied its own grant")
	}
	if memberAsCallerAllowed {
		t.Fatal("a member satisfied a concrete-group grant — userset-caller semantics leaked")
	}

	tr.add(4, "Decision APIs reject userset-valued callers",
		fmt.Sprintf("structural: CheckRequest.Principal is a PrincipalRef=%v; PrincipalRef has a Relation field=%v (none)", callerIsPrincipalRef, principalHasRelation),
		fmt.Sprintf("structural: the STORED subject type SubjectRef has a Relation field=%v — a different type no decision path accepts", subjectHasRelation),
		"consequence: a userset ('type:id#relation') caller cannot be expressed at any decision boundary — it is prevented by the type, never ignored at runtime",
		"command: Check(principal=group:eng CONCRETE, view, doc:dc) — the only group caller expressible is the concrete entity",
		fmt.Sprintf("Check(group:eng concrete, view, doc:dc) = %v (the concrete group entity itself)", concreteGroupAllowed),
		fmt.Sprintf("Check(user:alice member-of-eng, view, doc:dc) = %v (a member is NOT the concrete group; no userset-caller path exists)", memberAsCallerAllowed),
	)
}

// 5. A navigational Through relation rejects userset targets at schema compile.
func proofPoint05(t *testing.T, tr *proofTranscript) {
	// space.parent is used by Through("parent","view") but allows a userset
	// (space#member) — must be rejected at compile (NewService).
	bad := decisions.NewSchema([]decisions.ResourceSchema{{
		Name: "space", Def: decisions.ResourceTypeDef{
			Relations: map[string]decisions.RelationDef{
				"parent": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "space", Relation: "member"}}},
				"member": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "user"}}},
				"viewer": {AllowedSubjects: []decisions.SubjectTypeRef{{Type: "user"}}},
			},
			Permissions: map[string]decisions.Expression{
				"view": decisions.AnyOf(decisions.Direct("viewer"), decisions.Through("parent", "view")),
			},
		},
	}})

	store := authzmem.New(authzmem.WithGuardianPolicy(authzGuardianPolicy()))
	_, err := authorization.New(authorization.Repositories{
		Tuples:    store.Tuples(),
		Mutations: store.Mutations(),
	}, authorization.WithModel(bad), authorization.WithGuard(hostMutationGuard{}))
	if err == nil {
		t.Fatal("a Through relation allowing a userset target must fail schema compile")
	}
	if !errors.Is(err, sdk.ErrInvalidInput) {
		t.Fatalf("compile error must wrap sdk.ErrInvalidInput, got %v", err)
	}
	if !strings.Contains(err.Error(), "concrete resource subjects only") {
		t.Fatalf("compile error must name the userset-Through violation, got %q", err.Error())
	}

	tr.add(5, "A navigational Through relation rejects userset targets at schema compile",
		"command: NewService(schema{ space.view = AnyOf(Direct(viewer), Through(parent, view)); space.parent allows space#member })",
		fmt.Sprintf("result: construction FAILED, errors.Is(sdk.ErrInvalidInput)=%v", errors.Is(err, sdk.ErrInvalidInput)),
		fmt.Sprintf("compile error: %s", err.Error()),
	)
}

// 6. A non-self Through-root hierarchy: Check and Lookup return the same descendants.
func proofPoint06(t *testing.T, tr *proofTranscript) {
	sink := &capturedHistory{}
	comps := proofComposition(t, proofHierarchySchema(), sink)
	svc, sm := comps, comps.SystemMutator
	ctx := context.Background()

	// root <- mid <- leaf; root's access flows ONLY from org O (a non-self Through
	// root), no direct viewer grants anywhere.
	trustGrant(t, sm, "space", "mid", "parent", subj("space", "root"))
	trustGrant(t, sm, "space", "leaf", "parent", subj("space", "mid"))
	trustGrant(t, sm, "space", "root", "org", subj("org", "O"))
	trustGrant(t, sm, "org", "O", "admin", subj("user", "u1"))

	principal := model.PrincipalRef{Type: "user", ID: "u1"}
	// Check honors the org-derived root's descendants.
	leafAllowed := check(t, svc, "u1", "view", "space", "leaf")
	if !leafAllowed {
		t.Fatal("Check on the grandchild of a non-self Through root was denied")
	}
	look, err := svc.Decisions.LookupAllResourceIDs(ctx, principal, "view", "space")
	if err != nil {
		t.Fatalf("LookupAllResourceIDs: %v", err)
	}
	got := append([]string(nil), look.IDs...)
	sort.Strings(got)
	want := []string{"leaf", "mid", "root"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("Lookup: want %v (root + descendants), got %v", want, got)
	}
	// Parity: every Check-allowed id is enumerated by Lookup.
	for _, id := range want {
		if !check(t, svc, "u1", "view", "space", id) {
			t.Fatalf("Check disagrees with Lookup on space:%s", id)
		}
	}

	tr.add(6, "Non-self Through-root hierarchy: Check and Lookup return the same descendants",
		"setup: space:root inherits view ONLY from org:O#admin@user:u1 (a non-self Through root); root<-mid<-leaf via parent",
		fmt.Sprintf("Check(user:u1, view, space:leaf) = %v (grandchild of the org-derived root)", leafAllowed),
		fmt.Sprintf("LookupAllResourceIDs(user:u1, view, space).IDs = %v", got),
		fmt.Sprintf("parity: each Lookup id is Check-allowed = %v", allChecked(t, svc, want)),
	)
}

// 7. Global grants are explicit and never broaden scoped membership.
func proofPoint07(t *testing.T, tr *proofTranscript) {
	comps := proofComposition(t, authzSchema(), nil)
	ctx := audit2.WithSource(context.Background(), audit2.Source{System: "proof"})
	p := model.PrincipalRef{Type: "user", ID: "dave"}
	if _, err := comps.SystemMutator.AssignRole(ctx, mutations.AssignRoleCommand{Subject: p, Role: "auditor", Scope: tuples.Global()}); err != nil {
		t.Fatal(err)
	}
	global, err := comps.Roles.HasRole(ctx, p, "auditor")
	if err != nil || !global {
		t.Fatalf("global: %v %v", global, err)
	}
	scoped, err := comps.Roles.HasRoleIn(ctx, p, "auditor", model.Resource{Type: "project", ID: "p7"})
	if err != nil || scoped {
		t.Fatalf("scoped inherited global: %v %v", scoped, err)
	}
	page, err := comps.Roles.ListRoleAssignmentsByScope(ctx, tuples.Global(), list.Request{})
	if err != nil || len(page.Items) != 1 {
		t.Fatalf("global list: %+v %v", page, err)
	}
	tr.add(7, "Global grants are exact facts", fmt.Sprintf("HasRole=%v; HasRoleIn=%v; global assignments=%d", global, scoped, len(page.Items)))
}

// 8. Scoped revoke removes the scoped fact and preserves an independent global fact.
func proofPoint08(t *testing.T, tr *proofTranscript) {
	sink := &capturedHistory{}
	comps := proofComposition(t, authzSchema(), sink)
	ctx := audit2.WithSource(context.Background(), audit2.Source{System: "proof"})
	p := model.PrincipalRef{Type: "user", ID: "erin"}
	resource := model.Resource{Type: "project", ID: "p8"}
	trustGrant(t, comps.SystemMutator, "project", "p8", "owner", subj("user", "manager"))
	for _, scope := range []tuples.Scope{tuples.Global(), tuples.On("project", "p8")} {
		if _, err := comps.SystemMutator.AssignRole(ctx, mutations.AssignRoleCommand{Subject: p, Role: "auditor", Scope: scope}); err != nil {
			t.Fatal(err)
		}
	}
	result, err := comps.Mutations.UnassignRole(ctx, proofActor("manager"), mutations.UnassignRoleCommand{Subject: p, Role: "auditor", Scope: tuples.On("project", "p8")})
	if err != nil || result.Outcome != mutations.OutcomeApplied {
		t.Fatalf("revoke: %+v %v", result, err)
	}
	scoped, err := comps.Roles.HasRoleIn(ctx, p, "auditor", resource)
	if err != nil || scoped {
		t.Fatalf("scoped after revoke: %v %v", scoped, err)
	}
	global, err := comps.Roles.HasRole(ctx, p, "auditor")
	if err != nil || !global {
		t.Fatalf("global after revoke: %v %v", global, err)
	}
	tr.add(8, "Scoped revocation preserves global identity", fmt.Sprintf("outcome=%s; scoped=%v; global=%v", result.Outcome, scoped, global))
	tr.add(8, "Canonical audit", auditLines(sink.all())...)
}

// 9. Two concurrent last-owner revokes produce one success / one invariant block.
func proofPoint09(t *testing.T, tr *proofTranscript) {
	sink := &capturedHistory{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps, comps.SystemMutator
	ctx := context.Background()

	// A platform admin drives both revokes so the guard passes for either — isolating
	// the concurrency to the single database arbiter of the last-owner invariant.
	trustGrant(t, sm, "platform", "main", "admin", subj("user", "admin"))

	const rounds = 16
	var totalRemaining int
	outcomeSet := map[string]int{}
	for r := 0; r < rounds; r++ {
		res := fmt.Sprintf("prace%d", r)
		trustGrant(t, sm, "project", res, "owner", subj("user", "o1"))
		trustGrant(t, sm, "project", res, "owner", subj("user", "o2"))

		var wg sync.WaitGroup
		outs := make([]mutations.Outcome, 2)
		errs := make([]error, 2)
		revoke := func(i int, ownerID string) {
			defer wg.Done()
			rcpt, err := svc.Mutations.RevokeRelationship(ctx, proofActor("admin"), mutations.RevokeRelationshipCommand{
				ResourceType: "project", ResourceID: res,
				Relation: "owner", Subject: subj("user", ownerID),
			})
			if err != nil {
				errs[i] = err
				return
			}
			outs[i] = rcpt.Outcome
		}
		wg.Add(2)
		go revoke(0, "o1")
		go revoke(1, "o2")
		wg.Wait()

		applied, blocked := 0, 0
		for i, err := range errs {
			switch {
			case errors.Is(err, mutations.ErrInvariantBlocked):
				blocked++
				outcomeSet["invariant_blocked"]++
			case err != nil:
				t.Fatalf("round %d revoke %d: %v", r, i, err)
			case outs[i] == mutations.OutcomeApplied:
				applied++
				outcomeSet[string(outs[i])]++
			default:
				t.Fatalf("round %d revoke %d: unexpected outcome %s", r, i, outs[i])
			}
		}
		if applied != 1 || blocked != 1 {
			t.Fatalf("round %d: want exactly one applied + one invariant_blocked, got applied=%d blocked=%d (%v)", r, applied, blocked, outs)
		}
		remaining := ownerCount(t, svc, res)
		if remaining != 1 {
			t.Fatalf("round %d: exactly one owner must remain, got %d", r, remaining)
		}
		totalRemaining += remaining
	}

	tr.add(9, "Two concurrent last-owner revokes produce one success / one invariant block",
		fmt.Sprintf("setup: each of %d rounds seeds project#owner@{o1,o2}; two goroutines concurrently revoke o1 and o2 (platform-admin actor)", rounds),
		fmt.Sprintf("outcome tally across all rounds: %s", outcomeTally(outcomeSet)),
		fmt.Sprintf("invariant: every round produced exactly one applied + one invariant_blocked, with exactly one owner remaining (total remaining owners across rounds = %d = rounds)", totalRemaining),
		"run under -race: the memstore's single shared lock is the one database arbiter; the two owners can never both be removed",
	)
}

func proofPoint10(t *testing.T, tr *proofTranscript) {
	history := &capturedHistory{}
	comps := proofComposition(t, authzSchema(), history)
	trustGrant(t, comps.SystemMutator, "project", "p10", "owner", subj("user", "manager"))
	before := len(history.all())
	result, err := comps.Mutations.GrantRelationship(context.Background(), proofActor("manager"), mutations.GrantRelationshipCommand{ResourceType: "project", ResourceID: "p10", Relation: "member", Subject: subj("user", "manager")})
	if err != nil || result == nil || result.Outcome != mutations.OutcomeApplied {
		t.Fatalf("coexistence: %+v %v", result, err)
	}
	if len(history.all()) != before+1 {
		t.Fatal("new canonical fact missing history")
	}
	if !check(t, comps, "manager", "manage_access", "project", "p10") {
		t.Fatal("member displaced owner")
	}
	tr.add(10, "Independent labels coexist", "owner plus member: one new canonical fact; original owner preserved")
}

func proofPoint11(t *testing.T, tr *proofTranscript) {
	history := &capturedHistory{}
	comps := proofComposition(t, authzSchema(), history)
	trustGrant(t, comps.SystemMutator, "project", "p11", "owner", subj("user", "manager"))
	cmd := mutations.GrantRelationshipCommand{ResourceType: "project", ResourceID: "p11", Relation: "member", Subject: subj("user", "frank")}
	for _, want := range []mutations.Outcome{mutations.OutcomeApplied, mutations.OutcomeNoChange} {
		result, err := comps.Mutations.GrantRelationship(context.Background(), proofActor("manager"), cmd)
		if err != nil || result == nil || result.Outcome != want {
			t.Fatalf("grant: %+v, %v", result, err)
		}
	}
	if len(history.all()) != 2 {
		t.Fatal("duplicate grant recorded a change")
	}
	tr.add(11, "Repeated grants report current state and add no duplicate history", "first: applied; repeated call: no_change; one added member fact in history")
	tr.add(11, "", auditLines(history.all())...)
}

// 12. Resource teardown is possible only through the separately held SystemMutator
// command with a recorded reason.
func proofPoint12(t *testing.T, tr *proofTranscript) {
	sink := &capturedHistory{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "project", "p12", "owner", subj("user", "manager"))
	trustGrant(t, sm, "project", "p12", "member", subj("user", "someone"))

	// Structural: the actor-facing Service exposes NO teardown method; teardown is on
	// SystemMutator only.
	_, svcHasTeardown := reflect.TypeOf(svc).MethodByName("TeardownResourceAuthorization")
	_, smHasTeardown := reflect.TypeOf(sm).MethodByName("TeardownResourceAuthorization")

	// A reason is REQUIRED: an empty reason is refused before any write.
	_, emptyErr := sm.TeardownResourceAuthorization(audit2.WithSource(ctx, audit2.Source{System: "proof-cleanup"}), mutations.TeardownResourceAuthorizationCommand{
		ResourceType: "project", ResourceID: "p12", Reason: "  ",
	})
	if !errors.Is(emptyErr, mutations.ErrTeardownReasonRequired) {
		t.Fatalf("empty teardown reason: want ErrTeardownReasonRequired, got %v", emptyErr)
	}

	// The trusted teardown zeroes the scope (the one operation allowed to remove the
	// last owner) with an explicit, recorded reason.
	const reason = "az3-4.2 proof: project p12 destroyed by owner request"
	rcpt, err := sm.TeardownResourceAuthorization(audit2.WithSource(ctx, audit2.Source{System: "proof-cleanup"}), mutations.TeardownResourceAuthorizationCommand{
		ResourceType: "project", ResourceID: "p12", Reason: reason,
	})
	if err != nil || rcpt.Outcome != mutations.OutcomeApplied {
		t.Fatalf("teardown: outcome=%v err=%v", outcomeOf(rcpt), err)
	}
	ownerTargets, err := svc.Relationships.GetRelationTargets(ctx, "project", "p12", "owner")
	if err != nil {
		t.Fatalf("GetRelationTargets owner: %v", err)
	}
	memberTargets, _ := svc.Relationships.GetRelationTargets(ctx, "project", "p12", "member")
	if len(ownerTargets) != 0 || len(memberTargets) != 0 {
		t.Fatalf("teardown left rows: owners=%d members=%d", len(ownerTargets), len(memberTargets))
	}

	if svcHasTeardown {
		t.Fatal("the actor-facing Service must not expose TeardownResourceAuthorization")
	}
	if !smHasTeardown {
		t.Fatal("SystemMutator must expose TeardownResourceAuthorization")
	}

	// The reason is recorded observably on the audit seam (Detail), never a secret.
	teardownAudited := false
	for _, e := range sink.all() {
		if e.Change.Action == audit2.ActionRemoved && e.Source.Reason == reason {
			teardownAudited = true
		}
	}
	if !teardownAudited {
		t.Fatal("teardown reason was not recorded on the audit seam")
	}

	tr.add(12, "Resource teardown is possible only through the separately held SystemMutator with a recorded reason",
		fmt.Sprintf("structural: actor-facing Service exposes TeardownResourceAuthorization=%v; SystemMutator exposes it=%v", svcHasTeardown, smHasTeardown),
		fmt.Sprintf("precondition: empty reason rejected, errors.Is(ErrTeardownReasonRequired)=%v", errors.Is(emptyErr, mutations.ErrTeardownReasonRequired)),
		"command: SystemMutator.TeardownResourceAuthorization(project:p12, reason=<recorded>)",
		fmt.Sprintf("result: outcome=%s (the one op allowed to remove the last owner)", rcpt.Outcome),
		fmt.Sprintf("stored-row check after teardown: owner rows=%d member rows=%d", len(ownerTargets), len(memberTargets)),
	)
	tr.add(12, "Resource teardown is possible only through the separately held SystemMutator with a recorded reason", auditLines(sink.all())...)
}

// -----------------------------------------------------------------------------
// Small helpers
// -----------------------------------------------------------------------------

func hasField(t reflect.Type, name string) bool {
	for i := 0; i < t.NumField(); i++ {
		if strings.EqualFold(t.Field(i).Name, name) {
			return true
		}
	}
	return false
}

func checkPrincipal(t *testing.T, svc authorization.Components, st, sid, permission, rt, rid string) bool {
	t.Helper()
	res, err := svc.Decisions.Check(context.Background(), model.CheckRequest{
		Principal:  model.PrincipalRef{Type: st, ID: sid},
		Permission: permission,
		Resource:   model.Resource{Type: rt, ID: rid},
	})
	if err != nil {
		t.Fatalf("Check(%s:%s, %s, %s:%s): %v", st, sid, permission, rt, rid, err)
	}
	return res.Allowed
}

func allChecked(t *testing.T, svc authorization.Components, ids []string) bool {
	t.Helper()
	for _, id := range ids {
		if !check(t, svc, "u1", "view", "space", id) {
			return false
		}
	}
	return true
}

func ownerCount(t *testing.T, svc authorization.Components, resourceID string) int {
	t.Helper()
	targets, err := svc.Relationships.GetRelationTargets(context.Background(), "project", resourceID, "owner")
	if err != nil {
		t.Fatalf("GetRelationTargets owner project:%s: %v", resourceID, err)
	}
	return len(targets)
}

func outcomeOf(r *mutations.Result) mutations.Outcome {
	if r == nil {
		return ""
	}
	return r.Outcome
}

func targetsString(targets []relationships.RelationTarget) string {
	if len(targets) == 0 {
		return "(none)"
	}
	parts := make([]string, 0, len(targets))
	for _, tgt := range targets {
		s := tgt.Type + ":" + tgt.ID
		if tgt.Relation != "" {
			s += "#" + tgt.Relation
		}
		parts = append(parts, s)
	}
	sort.Strings(parts)
	return strings.Join(parts, ", ")
}

func outcomeTally(m map[string]int) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s=%d", k, m[k]))
	}
	return strings.Join(parts, " ")
}

func short(digest string) string {
	if len(digest) <= 16 {
		return digest
	}
	return digest[:16] + "…"
}

func proofSystemContext() context.Context {
	return audit2.WithSource(context.Background(), audit2.Source{System: "proof-setup"})
}
