package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"sync"
	"testing"

	authorization "github.com/gopernicus/gopernicus/features/authorization"
	authzmem "github.com/gopernicus/gopernicus/features/authorization/memstore"
	"github.com/gopernicus/gopernicus/sdk"
	"github.com/gopernicus/gopernicus/sdk/foundation/crud"
)

// AZ3-4.2 — exact-semantics and concurrency proof protocol.
//
// This suite DRIVES and RECORDS the twelve-point protocol over the auth-cms host
// composition (the AZ3-4.1 wiring: the memstore bundle under authzGuardianPolicy,
// the hostMutationGuard, and the separately held SystemMutator) plus a capturing
// AuditSink. Every point is OBSERVED in this run — not merely referenced — and its
// evidence (commands, receipt fields, stored-row reads, audit events) is written to
// a durable transcript artifact at testdata/az3-proof-transcript.md. The transcript
// carries no secrets: there are no session tokens or password material anywhere on
// the authorization path, and MutationIDs are opaque idempotency tokens that are
// safe to retain. It claims no effects delivery and no generic admin API.
//
// Points 2,3,4,6 exercise userset / navigational-Through schema shapes the host's
// live project/platform schema does not declare; they run over the SAME composition
// pattern (proofComposition: hostMutationGuard + the guardian-policy'd memstore
// bundle) with a proof schema that adds the group/doc and org/space types, so the
// real host guard authorizes them. Points 1,7,8,9,10,11,12 run over the live host
// schema (authzSchema).

const proofTranscriptPath = "testdata/az3-proof-transcript.md"

// -----------------------------------------------------------------------------
// Recording apparatus
// -----------------------------------------------------------------------------

// proofSection is one numbered protocol point's recorded evidence.
type proofSection struct {
	n     int
	title string
	lines []string
}

// proofTranscript accumulates the twelve sections and renders the artifact.
type proofTranscript struct {
	mu       sync.Mutex
	sections []proofSection
}

func (t *proofTranscript) add(n int, title string, lines ...string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	for i := range t.sections {
		if t.sections[i].n == n {
			t.sections[i].lines = append(t.sections[i].lines, lines...)
			return
		}
	}
	t.sections = append(t.sections, proofSection{n: n, title: title, lines: lines})
}

func (t *proofTranscript) render() string {
	t.mu.Lock()
	defer t.mu.Unlock()
	sort.Slice(t.sections, func(i, j int) bool { return t.sections[i].n < t.sections[j].n })

	var b strings.Builder
	b.WriteString("# Authorization v3 — AZ3-4.2 exact-semantics and concurrency proof transcript\n\n")
	b.WriteString("Generated by `go test -run TestAZ3ProofProtocol` in `examples/auth-cms/cmd/server`.\n")
	b.WriteString("This is a recorded artifact: each section below was OBSERVED in a real protocol run\n")
	b.WriteString("over the auth-cms host composition (the AZ3-4.1 memstore bundle under\n")
	b.WriteString("authzGuardianPolicy, the hostMutationGuard, and the separately held SystemMutator)\n")
	b.WriteString("with a capturing AuditSink wired into `Config.Audit`.\n\n")
	b.WriteString("No secrets: authorization carries no session tokens or password material; MutationIDs\n")
	b.WriteString("are opaque idempotency tokens (safe to retain). This transcript claims NO effects\n")
	b.WriteString("delivery and NO generic authorization admin API — both are deferred follow-ups.\n\n")
	b.WriteString("MutationIDs in this run are derived deterministically (DeriveMutationID) so the\n")
	b.WriteString("artifact is reproducible; actor-facing production callers mint unguessable IDs with\n")
	b.WriteString("NewMutationID. Possession of a MutationID is never authority — the guard runs on\n")
	b.WriteString("every actor-facing application and replay.\n\n")
	for _, s := range t.sections {
		fmt.Fprintf(&b, "## %d. %s\n\n", s.n, s.title)
		for _, ln := range s.lines {
			fmt.Fprintf(&b, "- %s\n", ln)
		}
		b.WriteString("\n")
	}
	return b.String()
}

// capturingAuditSink records every actor-facing mutation attempt and every trusted
// teardown the composition observes. It is the AZ3-4.2 audit-observation seam.
type capturingAuditSink struct {
	mu     sync.Mutex
	events []authorization.AuditEvent
}

func (c *capturingAuditSink) RecordMutation(_ context.Context, e authorization.AuditEvent) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.events = append(c.events, e)
	return nil
}

func (c *capturingAuditSink) all() []authorization.AuditEvent {
	c.mu.Lock()
	defer c.mu.Unlock()
	return append([]authorization.AuditEvent(nil), c.events...)
}

// auditLines renders captured audit events as transcript lines (coarse, bounded
// fields only — never secrets).
func auditLines(events []authorization.AuditEvent) []string {
	if len(events) == 0 {
		return []string{"audit: (no events captured)"}
	}
	out := make([]string, 0, len(events))
	for _, e := range events {
		line := fmt.Sprintf("audit: decision=%s operation=%s scope=%s:%s(%s)",
			e.Decision, e.Operation, e.Scope.Type, e.Scope.ID, e.Scope.Kind)
		if e.Outcome != "" {
			line += " outcome=" + string(e.Outcome)
		}
		if e.Reason != "" {
			line += " reason=" + string(e.Reason)
		}
		if e.Detail != "" {
			line += " detail=" + e.Detail
		}
		out = append(out, line)
	}
	return out
}

// -----------------------------------------------------------------------------
// Composition and command helpers
// -----------------------------------------------------------------------------

// proofComposition builds the guarded auth composition exactly as newAuthorization
// does — the guardian-policy'd memstore bundle, hostMutationGuard, and the
// separately held SystemMutator — plus a capturing AuditSink and a caller-chosen
// schema. This is the AZ3-4.1 host composition; only the schema and the audit sink
// vary so userset/hierarchy shapes can be proven over the same real guard.
func proofComposition(t *testing.T, schema authorization.Schema, audit authorization.AuditSink) authorization.Components {
	t.Helper()
	store := authzmem.New(authzmem.WithGuardianPolicy(authzGuardianPolicy()))
	comps, err := authorization.NewService(authorization.Repositories{
		Relationships: store.Relationships(),
		Roles:         store.Roles(),
		Mutations:     store.Mutations(),
	}, authorization.Config{
		Model: schema,
		Guard: hostMutationGuard{},
		Audit: audit,
	})
	if err != nil {
		t.Fatalf("proofComposition: %v", err)
	}
	return comps
}

// pid derives a stable MutationID from descriptive parts so the transcript is
// reproducible (see the transcript preamble).
func pid(parts ...string) authorization.MutationID {
	return authorization.DeriveMutationID(append([]string{"az3-4.2"}, parts...)...)
}

func revPtr(v uint64) *authorization.Revision {
	r := authorization.Revision(v)
	return &r
}

func subj(t, id string) authorization.SubjectRef { return authorization.SubjectRef{Type: t, ID: id} }

func userset(t, id, relation string) authorization.SubjectRef {
	return authorization.SubjectRef{Type: t, ID: id, Relation: relation}
}

// trustGrant seeds a relationship through the trusted SystemMutator (bypasses the
// host guard, obeys the atomic contract). Setup uses this; the ACT under test uses
// the guarded Service so the audit sink captures exactly the act.
func trustGrant(t *testing.T, sm *authorization.SystemMutator, rt, rid, rel string, s authorization.SubjectRef) {
	t.Helper()
	if _, err := sm.GrantRelationship(context.Background(), authorization.GrantRelationshipCommand{
		MutationID:   pid("seed", rt, rid, rel, s.Type, s.ID, s.Relation),
		ResourceType: rt, ResourceID: rid, Relation: rel, Subject: s,
	}); err != nil {
		t.Fatalf("trustGrant %s:%s#%s <- %s:%s#%s: %v", rt, rid, rel, s.Type, s.ID, s.Relation, err)
	}
}

func proofActor(userID string) authorization.Actor {
	return authorization.Actor{PrincipalRef: authorization.PrincipalRef{Type: "user", ID: userID}}
}

// check is a small read helper for the transcript's stored-state observations.
func check(t *testing.T, svc *authorization.Service, userID, permission, resourceType, resourceID string) bool {
	t.Helper()
	res, err := svc.Check(context.Background(), authorization.CheckRequest{
		Principal:  authorization.PrincipalRef{Type: "user", ID: userID},
		Permission: permission,
		Resource:   authorization.Resource{Type: resourceType, ID: resourceID},
	})
	if err != nil {
		t.Fatalf("Check(%s, %s, %s:%s): %v", userID, permission, resourceType, resourceID, err)
	}
	return res.Allowed
}

// -----------------------------------------------------------------------------
// Proof schemas
// -----------------------------------------------------------------------------

// proofUsersetSchema adds a userset-bearing group/doc pair to the host's project +
// platform types so the real hostMutationGuard (manage_access = owner) authorizes a
// manager granting an exact userset subject on a doc.
func proofUsersetSchema() authorization.Schema {
	return authorization.NewSchema([]authorization.ResourceSchema{
		{Name: "platform", Def: authorization.ResourceTypeDef{
			Relations:   map[string]authorization.RelationDef{"admin": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "user"}}}},
			Permissions: map[string]authorization.PermissionRule{"admin": authorization.AnyOf(authorization.Direct("admin"))},
		}},
		{Name: "group", Def: authorization.ResourceTypeDef{
			Relations: map[string]authorization.RelationDef{
				"member": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "user"}, {Type: "group", Relation: "member"}}},
				"admin":  {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "user"}}},
			},
		}},
		{Name: "doc", Def: authorization.ResourceTypeDef{
			Relations: map[string]authorization.RelationDef{
				"owner": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "user"}}},
				"viewer": {AllowedSubjects: []authorization.SubjectTypeRef{
					{Type: "user"},
					{Type: "group"},
					{Type: "group", Relation: "member"},
					{Type: "group", Relation: "admin"},
				}},
			},
			Permissions: map[string]authorization.PermissionRule{
				"view":          authorization.AnyOf(authorization.Direct("viewer")),
				"manage_access": authorization.AnyOf(authorization.Direct("owner")),
			},
		}},
	})
}

// proofHierarchySchema is the non-self Through-root hierarchy: a space inherits
// `view` up its `parent` chain AND from its owning `org` (a NON-self Through). Used
// for point 6's Check/Lookup parity.
func proofHierarchySchema() authorization.Schema {
	return authorization.NewSchema([]authorization.ResourceSchema{
		{Name: "org", Def: authorization.ResourceTypeDef{
			Relations:   map[string]authorization.RelationDef{"admin": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "user"}}}},
			Permissions: map[string]authorization.PermissionRule{"view": authorization.AnyOf(authorization.Direct("admin"))},
		}},
		{Name: "space", Def: authorization.ResourceTypeDef{
			Relations: map[string]authorization.RelationDef{
				"parent": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "space"}}},
				"viewer": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "user"}}},
				"org":    {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "org"}}},
			},
			Permissions: map[string]authorization.PermissionRule{
				"view": authorization.AnyOf(authorization.Direct("viewer"), authorization.Through("org", "view"), authorization.Through("parent", "view")),
			},
		}},
	})
}

// -----------------------------------------------------------------------------
// The protocol
// -----------------------------------------------------------------------------

// TestAZ3ProofProtocol drives the twelve-point exact-semantics/concurrency protocol
// and writes the recorded transcript artifact. Run it under -race.
func TestAZ3ProofProtocol(t *testing.T) {
	tr := &proofTranscript{}

	points := []struct {
		name string
		fn   func(*testing.T, *proofTranscript)
	}{
		{"01_ordinary_member_cannot_self_grant", proofPoint01},
		{"02_manager_grants_group_member_userset", proofPoint02},
		{"03_group_admin_grant_does_not_authorize_member", proofPoint03},
		{"04_decision_apis_reject_userset_callers", proofPoint04},
		{"05_through_rejects_userset_targets_at_compile", proofPoint05},
		{"06_nonself_through_root_check_lookup_parity", proofPoint06},
		{"07_global_role_in_effective_enumeration", proofPoint07},
		{"08_scoped_revoke_same_role_grant_remains", proofPoint08},
		{"09_concurrent_last_owner_revoke_single_winner", proofPoint09},
		{"10_stale_revision_and_payload_mismatch", proofPoint10},
		{"11_exact_retry_replayed", proofPoint11},
		{"12_teardown_only_via_system_mutator", proofPoint12},
	}
	for _, p := range points {
		t.Run(p.name, func(t *testing.T) { p.fn(t, tr) })
	}

	if err := os.MkdirAll(filepath.Dir(proofTranscriptPath), 0o755); err != nil {
		t.Fatalf("mkdir testdata: %v", err)
	}
	if err := os.WriteFile(proofTranscriptPath, []byte(tr.render()), 0o644); err != nil {
		t.Fatalf("write transcript: %v", err)
	}
	t.Logf("wrote proof transcript to %s (%d sections)", proofTranscriptPath, len(tr.sections))
}

// 1. An ordinary member cannot self-grant.
func proofPoint01(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "project", "p1", "owner", subj("user", "manager"))
	trustGrant(t, sm, "project", "p1", "member", subj("user", "ordinary")) // trusted seed, not audited

	// The ordinary member attempts to self-grant owner (self-escalation).
	_, err := svc.GrantRelationship(ctx, proofActor("ordinary"), authorization.GrantRelationshipCommand{
		MutationID: pid("p1", "self-grant"), ResourceType: "project", ResourceID: "p1",
		Relation: "owner", Subject: subj("user", "ordinary"),
	})
	if !errors.Is(err, sdk.ErrForbidden) {
		t.Fatalf("self-grant: want forbidden, got %v", err)
	}
	wroteOwner := check(t, svc, "ordinary", "manage_access", "project", "p1")
	if wroteOwner {
		t.Fatal("denied self-grant nonetheless wrote an owner row")
	}

	tr.add(1, "Ordinary member cannot self-grant",
		"command: Service.GrantRelationship(actor=user:ordinary, grant project:p1#owner <- user:ordinary)",
		fmt.Sprintf("result: rejected, errors.Is(sdk.ErrForbidden)=%v (guard denied before Apply)", errors.Is(err, sdk.ErrForbidden)),
		fmt.Sprintf("stored-row check: user:ordinary has manage_access on project:p1 = %v (no owner row committed)", wroteOwner),
	)
	tr.add(1, "Ordinary member cannot self-grant", auditLines(sink.all())...)
}

// 2. An authorized manager grants an exact group#member subject and a concrete
// member gains access.
func proofPoint02(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, proofUsersetSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "group", "eng", "member", subj("user", "alice")) // alice is a member of group:eng
	trustGrant(t, sm, "doc", "d2", "owner", subj("user", "manager"))   // manager holds manage_access on doc:d2

	// The manager (authorized via manage_access) grants the exact group#member userset.
	rcpt, err := svc.GrantRelationship(ctx, proofActor("manager"), authorization.GrantRelationshipCommand{
		MutationID: pid("p2", "grant-userset"), ResourceType: "doc", ResourceID: "d2",
		Relation: "viewer", Subject: userset("group", "eng", "member"),
	})
	if err != nil || rcpt.Outcome != authorization.OutcomeApplied {
		t.Fatalf("manager userset grant: outcome=%v err=%v", outcomeOf(rcpt), err)
	}
	memberAllowed := check(t, svc, "alice", "view", "doc", "d2")
	if !memberAllowed {
		t.Fatal("concrete member of group:eng did not gain view via the group#member grant")
	}
	strangerAllowed := check(t, svc, "stranger", "view", "doc", "d2")
	if strangerAllowed {
		t.Fatal("a non-member gained access through the group#member userset")
	}

	// Stored-row observation: the viewer target is the EXACT userset (group:eng#member).
	targets, err := svc.GetRelationTargets(ctx, "doc", "d2", "viewer")
	if err != nil {
		t.Fatalf("GetRelationTargets: %v", err)
	}
	digest, _ := svc.SchemaDigest()

	tr.add(2, "Authorized manager grants an exact group#member subject",
		"command: Service.GrantRelationship(actor=user:manager, grant doc:d2#viewer <- group:eng#member)",
		fmt.Sprintf("receipt: outcome=%s revision=%d replayed=%v schema_digest=%s", rcpt.Outcome, rcpt.Revision, rcpt.Replayed, short(rcpt.SchemaDigest)),
		fmt.Sprintf("live schema digest: %s (matches receipt)", short(digest)),
		fmt.Sprintf("stored viewer target(s): %s", targetsString(targets)),
		fmt.Sprintf("Check(user:alice member-of-eng, view, doc:d2) = %v (member gains access)", memberAllowed),
		fmt.Sprintf("Check(user:stranger, view, doc:d2) = %v (non-member denied)", strangerAllowed),
	)
	tr.add(2, "Authorized manager grants an exact group#member subject", auditLines(sink.all())...)
}

// 3. A group#admin grant does not authorize an ordinary member.
func proofPoint03(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, proofUsersetSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "group", "eng", "member", subj("user", "alice")) // ordinary member
	trustGrant(t, sm, "group", "eng", "admin", subj("user", "carol"))  // admin
	trustGrant(t, sm, "doc", "d3", "owner", subj("user", "manager"))

	// The manager grants the group#ADMIN userset on doc:d3#viewer.
	rcpt, err := svc.GrantRelationship(ctx, proofActor("manager"), authorization.GrantRelationshipCommand{
		MutationID: pid("p3", "grant-admin-userset"), ResourceType: "doc", ResourceID: "d3",
		Relation: "viewer", Subject: userset("group", "eng", "admin"),
	})
	if err != nil || rcpt.Outcome != authorization.OutcomeApplied {
		t.Fatalf("manager admin-userset grant: outcome=%v err=%v", outcomeOf(rcpt), err)
	}
	memberAllowed := check(t, svc, "alice", "view", "doc", "d3") // member, NOT admin
	adminAllowed := check(t, svc, "carol", "view", "doc", "d3")  // admin
	if memberAllowed {
		t.Fatal("a group#admin grant authorized an ordinary member (cross-relation leak)")
	}
	if !adminAllowed {
		t.Fatal("a group#admin grant did not authorize the group admin")
	}

	tr.add(3, "A group#admin grant does not authorize an ordinary member",
		"command: Service.GrantRelationship(actor=user:manager, grant doc:d3#viewer <- group:eng#admin)",
		fmt.Sprintf("receipt: outcome=%s revision=%d", rcpt.Outcome, rcpt.Revision),
		fmt.Sprintf("Check(user:alice group:eng#member, view, doc:d3) = %v (member does NOT satisfy the admin userset)", memberAllowed),
		fmt.Sprintf("Check(user:carol group:eng#admin, view, doc:d3) = %v (admin satisfies it)", adminAllowed),
	)
	tr.add(3, "A group#admin grant does not authorize an ordinary member", auditLines(sink.all())...)
}

// 4. Decision APIs reject userset-valued callers.
func proofPoint04(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, proofUsersetSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	// Structural proof: a decision request's caller (CheckRequest.Principal) is a
	// concrete PrincipalRef with only (Type, ID) — no Relation field a caller could
	// set to a userset. The STORED subject type (SubjectRef) is a DIFFERENT type that
	// does carry Relation, and no decision path accepts it.
	prinType := reflect.TypeOf(authorization.PrincipalRef{})
	crPrincipal, _ := reflect.TypeOf(authorization.CheckRequest{}).FieldByName("Principal")
	principalHasRelation := hasField(prinType, "Relation")
	subjectHasRelation := hasField(reflect.TypeOf(authorization.SubjectRef{}), "Relation")
	callerIsPrincipalRef := crPrincipal.Type == prinType

	// Driven proof: a caller is always the CONCRETE entity. A concrete-group grant
	// names the group entity itself, never its members — there is no way to ask "as
	// group#member".
	trustGrant(t, sm, "group", "eng", "member", subj("user", "alice"))
	trustGrant(t, sm, "doc", "dc", "owner", subj("user", "manager"))
	if _, err := svc.GrantRelationship(ctx, proofActor("manager"), authorization.GrantRelationshipCommand{
		MutationID: pid("p4", "grant-concrete-group"), ResourceType: "doc", ResourceID: "dc",
		Relation: "viewer", Subject: subj("group", "eng"), // concrete group entity, no relation
	}); err != nil {
		t.Fatalf("concrete-group grant: %v", err)
	}
	concreteGroupAllowed := checkPrincipal(t, svc, "group", "eng", "view", "doc", "dc") // the group entity is the caller
	memberAsCallerAllowed := check(t, svc, "alice", "view", "doc", "dc")                // a member is NOT the concrete group

	if !callerIsPrincipalRef || principalHasRelation || !subjectHasRelation {
		t.Fatalf("structural: callerIsPrincipalRef=%v principalHasRelation=%v subjectHasRelation=%v",
			callerIsPrincipalRef, principalHasRelation, subjectHasRelation)
	}
	if !concreteGroupAllowed {
		t.Fatal("the concrete group entity (the only expressible group caller) was denied its own grant")
	}
	if memberAsCallerAllowed {
		t.Fatal("a member satisfied a concrete-group grant — userset-caller semantics leaked")
	}

	tr.add(4, "Decision APIs reject userset-valued callers",
		fmt.Sprintf("structural: CheckRequest.Principal is a PrincipalRef=%v; PrincipalRef has a Relation field=%v (none)", callerIsPrincipalRef, principalHasRelation),
		fmt.Sprintf("structural: the STORED subject type SubjectRef has a Relation field=%v — a different type no decision path accepts", subjectHasRelation),
		"consequence: a userset ('type:id#relation') caller cannot be expressed at any decision boundary — it is prevented by the type, never ignored at runtime",
		"command: Check(principal=group:eng CONCRETE, view, doc:dc) — the only group caller expressible is the concrete entity",
		fmt.Sprintf("Check(group:eng concrete, view, doc:dc) = %v (the concrete group entity itself)", concreteGroupAllowed),
		fmt.Sprintf("Check(user:alice member-of-eng, view, doc:dc) = %v (a member is NOT the concrete group; no userset-caller path exists)", memberAsCallerAllowed),
	)
}

// 5. A navigational Through relation rejects userset targets at schema compile.
func proofPoint05(t *testing.T, tr *proofTranscript) {
	// space.parent is used by Through("parent","view") but allows a userset
	// (space#member) — must be rejected at compile (NewService).
	bad := authorization.NewSchema([]authorization.ResourceSchema{{
		Name: "space", Def: authorization.ResourceTypeDef{
			Relations: map[string]authorization.RelationDef{
				"parent": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "space", Relation: "member"}}},
				"member": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "user"}}},
				"viewer": {AllowedSubjects: []authorization.SubjectTypeRef{{Type: "user"}}},
			},
			Permissions: map[string]authorization.PermissionRule{
				"view": authorization.AnyOf(authorization.Direct("viewer"), authorization.Through("parent", "view")),
			},
		},
	}})

	store := authzmem.New(authzmem.WithGuardianPolicy(authzGuardianPolicy()))
	_, err := authorization.NewService(authorization.Repositories{
		Relationships: store.Relationships(),
		Roles:         store.Roles(),
		Mutations:     store.Mutations(),
	}, authorization.Config{Model: bad, Guard: hostMutationGuard{}})
	if err == nil {
		t.Fatal("a Through relation allowing a userset target must fail schema compile")
	}
	if !errors.Is(err, sdk.ErrInvalidInput) {
		t.Fatalf("compile error must wrap sdk.ErrInvalidInput, got %v", err)
	}
	if !strings.Contains(err.Error(), "concrete resource subjects only") {
		t.Fatalf("compile error must name the userset-Through violation, got %q", err.Error())
	}

	tr.add(5, "A navigational Through relation rejects userset targets at schema compile",
		"command: NewService(schema{ space.view = AnyOf(Direct(viewer), Through(parent, view)); space.parent allows space#member })",
		fmt.Sprintf("result: construction FAILED, errors.Is(sdk.ErrInvalidInput)=%v", errors.Is(err, sdk.ErrInvalidInput)),
		fmt.Sprintf("compile error: %s", err.Error()),
	)
}

// 6. A non-self Through-root hierarchy: Check and Lookup return the same descendants.
func proofPoint06(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, proofHierarchySchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	// root <- mid <- leaf; root's access flows ONLY from org O (a non-self Through
	// root), no direct viewer grants anywhere.
	trustGrant(t, sm, "space", "mid", "parent", subj("space", "root"))
	trustGrant(t, sm, "space", "leaf", "parent", subj("space", "mid"))
	trustGrant(t, sm, "space", "root", "org", subj("org", "O"))
	trustGrant(t, sm, "org", "O", "admin", subj("user", "u1"))

	principal := authorization.PrincipalRef{Type: "user", ID: "u1"}
	// Check honors the org-derived root's descendants.
	leafAllowed := check(t, svc, "u1", "view", "space", "leaf")
	if !leafAllowed {
		t.Fatal("Check on the grandchild of a non-self Through root was denied")
	}
	look, err := svc.LookupResources(ctx, principal, "view", "space")
	if err != nil {
		t.Fatalf("LookupResources: %v", err)
	}
	got := append([]string(nil), look.IDs...)
	sort.Strings(got)
	want := []string{"leaf", "mid", "root"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("Lookup: want %v (root + descendants), got %v", want, got)
	}
	// Parity: every Check-allowed id is enumerated by Lookup.
	for _, id := range want {
		if !check(t, svc, "u1", "view", "space", id) {
			t.Fatalf("Check disagrees with Lookup on space:%s", id)
		}
	}

	tr.add(6, "Non-self Through-root hierarchy: Check and Lookup return the same descendants",
		"setup: space:root inherits view ONLY from org:O#admin@user:u1 (a non-self Through root); root<-mid<-leaf via parent",
		fmt.Sprintf("Check(user:u1, view, space:leaf) = %v (grandchild of the org-derived root)", leafAllowed),
		fmt.Sprintf("LookupResources(user:u1, view, space).IDs = %v", got),
		fmt.Sprintf("parity: each Lookup id is Check-allowed = %v", allChecked(t, svc, want)),
	)
}

// 7. A global role appears in effective role enumeration.
func proofPoint07(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	// A GLOBAL role assignment (trusted-only blast radius) with NO direct scoped row.
	if _, err := sm.AssignRole(ctx, authorization.AssignRoleCommand{
		MutationID: pid("p7", "global-role"), Subject: authorization.PrincipalRef{Type: "user", ID: "dave"}, Role: "auditor",
	}); err != nil {
		t.Fatalf("global AssignRole: %v", err)
	}

	page, err := svc.ListEffectiveRoleGrantsByResource(ctx, "project", "p7", crud.ListRequest{})
	if err != nil {
		t.Fatalf("ListEffectiveRoleGrantsByResource: %v", err)
	}
	var found *authorization.EffectiveGrant
	for i := range page.Items {
		if page.Items[i].SubjectID == "dave" && page.Items[i].Role == "auditor" {
			found = &page.Items[i]
		}
	}
	if found == nil {
		t.Fatal("global role grant did not appear in the resource's effective enumeration")
	}
	if found.Direct || !found.Global {
		t.Fatalf("effective grant provenance: want direct=false global=true, got direct=%v global=%v", found.Direct, found.Global)
	}
	hasRole, err := svc.HasRole(ctx, authorization.PrincipalRef{Type: "user", ID: "dave"}, "auditor", "project", "p7")
	if err != nil {
		t.Fatalf("HasRole: %v", err)
	}
	if !hasRole {
		t.Fatal("scoped HasRole global fallback disagreed with the effective enumeration")
	}

	tr.add(7, "A global role appears in effective role enumeration",
		"command: SystemMutator.AssignRole(user:dave, role=auditor, GLOBAL) — no direct scoped row on project:p7",
		fmt.Sprintf("ListEffectiveRoleGrantsByResource(project:p7): user:dave/auditor present, provenance=%s (direct=%v global=%v)", found.Provenance(), found.Direct, found.Global),
		fmt.Sprintf("HasRole(user:dave, auditor, project:p7) = %v (scoped global fallback agrees with enumeration)", hasRole),
	)
}

// 8. A scoped revoke while a global remains reports same_role_grant_remains.
func proofPoint08(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "project", "p8", "owner", subj("user", "manager"))
	// erin holds BOTH a global auditor and a scoped auditor on project:p8.
	if _, err := sm.AssignRole(ctx, authorization.AssignRoleCommand{
		MutationID: pid("p8", "global-role"), Subject: authorization.PrincipalRef{Type: "user", ID: "erin"}, Role: "auditor",
	}); err != nil {
		t.Fatalf("global AssignRole: %v", err)
	}
	if _, err := svc.AssignRole(ctx, proofActor("manager"), authorization.AssignRoleCommand{
		MutationID: pid("p8", "scoped-role"), Subject: authorization.PrincipalRef{Type: "user", ID: "erin"}, Role: "auditor",
		ResourceType: "project", ResourceID: "p8",
	}); err != nil {
		t.Fatalf("scoped AssignRole: %v", err)
	}

	// The manager revokes the SCOPED assignment; the global still confers the role.
	result, err := svc.UnassignRole(ctx, proofActor("manager"), authorization.UnassignRoleCommand{
		MutationID: pid("p8", "scoped-unassign"), Subject: authorization.PrincipalRef{Type: "user", ID: "erin"}, Role: "auditor",
		ResourceType: "project", ResourceID: "p8",
	})
	if err != nil {
		t.Fatalf("scoped UnassignRole: %v", err)
	}
	if !result.SameRoleGrantRemains {
		t.Fatal("scoped revoke while a global remains must report same_role_grant_remains=true")
	}
	stillHas, err := svc.HasRole(ctx, authorization.PrincipalRef{Type: "user", ID: "erin"}, "auditor", "project", "p8")
	if err != nil {
		t.Fatalf("HasRole after scoped revoke: %v", err)
	}
	if !stillHas {
		t.Fatal("global fallback should still confer the role after the scoped revoke")
	}

	tr.add(8, "A scoped revoke while a global remains reports same_role_grant_remains",
		"setup: user:erin holds auditor GLOBALLY and scoped on project:p8",
		"command: Service.UnassignRole(actor=user:manager, user:erin/auditor scoped on project:p8)",
		fmt.Sprintf("result: outcome=%s same_role_grant_remains=%v (computed inside the atomic critical section)", result.Receipt.Outcome, result.SameRoleGrantRemains),
		fmt.Sprintf("HasRole(user:erin, auditor, project:p8) after revoke = %v (global fallback retains it)", stillHas),
	)
	tr.add(8, "A scoped revoke while a global remains reports same_role_grant_remains", auditLines(sink.all())...)
}

// 9. Two concurrent last-owner revokes produce one success / one invariant block.
func proofPoint09(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	// A platform admin drives both revokes so the guard passes for either — isolating
	// the concurrency to the single database arbiter of the last-owner invariant.
	trustGrant(t, sm, "platform", "main", "admin", subj("user", "admin"))

	const rounds = 16
	var totalRemaining int
	outcomeSet := map[string]int{}
	for r := 0; r < rounds; r++ {
		res := fmt.Sprintf("prace%d", r)
		trustGrant(t, sm, "project", res, "owner", subj("user", "o1"))
		trustGrant(t, sm, "project", res, "owner", subj("user", "o2"))

		var wg sync.WaitGroup
		outs := make([]authorization.Outcome, 2)
		errs := make([]error, 2)
		revoke := func(i int, ownerID string) {
			defer wg.Done()
			rcpt, err := svc.RevokeRelationship(ctx, proofActor("admin"), authorization.RevokeRelationshipCommand{
				MutationID: pid("p9", res, "revoke", ownerID), ResourceType: "project", ResourceID: res,
				Relation: "owner", Subject: subj("user", ownerID),
			})
			if err != nil {
				errs[i] = err
				return
			}
			outs[i] = rcpt.Outcome
		}
		wg.Add(2)
		go revoke(0, "o1")
		go revoke(1, "o2")
		wg.Wait()

		for i, err := range errs {
			if err != nil {
				t.Fatalf("round %d revoke %d errored (must be a domain outcome): %v", r, i, err)
			}
		}
		applied, blocked := 0, 0
		for _, o := range outs {
			switch o {
			case authorization.OutcomeApplied:
				applied++
			case authorization.OutcomeInvariantBlocked:
				blocked++
			}
			outcomeSet[string(o)]++
		}
		if applied != 1 || blocked != 1 {
			t.Fatalf("round %d: want exactly one applied + one invariant_blocked, got applied=%d blocked=%d (%v)", r, applied, blocked, outs)
		}
		remaining := ownerCount(t, svc, res)
		if remaining != 1 {
			t.Fatalf("round %d: exactly one owner must remain, got %d", r, remaining)
		}
		totalRemaining += remaining
	}

	tr.add(9, "Two concurrent last-owner revokes produce one success / one invariant block",
		fmt.Sprintf("setup: each of %d rounds seeds project#owner@{o1,o2}; two goroutines concurrently revoke o1 and o2 (platform-admin actor)", rounds),
		fmt.Sprintf("outcome tally across all rounds: %s", outcomeTally(outcomeSet)),
		fmt.Sprintf("invariant: every round produced exactly one applied + one invariant_blocked, with exactly one owner remaining (total remaining owners across rounds = %d = rounds)", totalRemaining),
		"run under -race: the memstore's single shared lock is the one database arbiter; the two owners can never both be removed",
	)
}

// 10. Stale revision and MutationID payload mismatch return stable errors.
func proofPoint10(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "project", "p10", "owner", subj("user", "manager")) // scope revision now >= 1

	// Stale revision: an ExpectedRevision of 0 no longer matches the scope.
	_, staleErr := svc.GrantRelationship(ctx, proofActor("manager"), authorization.GrantRelationshipCommand{
		MutationID: pid("p10", "stale"), ResourceType: "project", ResourceID: "p10",
		Relation: "member", Subject: subj("user", "x"), ExpectedRevision: revPtr(0),
	})
	if !errors.Is(staleErr, authorization.ErrStaleRevision) {
		t.Fatalf("stale revision: want ErrStaleRevision, got %v", staleErr)
	}

	// Payload mismatch: reuse one MutationID under two different payloads.
	mid := pid("p10", "mismatch")
	if _, err := svc.GrantRelationship(ctx, proofActor("manager"), authorization.GrantRelationshipCommand{
		MutationID: mid, ResourceType: "project", ResourceID: "p10", Relation: "member", Subject: subj("user", "y"),
	}); err != nil {
		t.Fatalf("first grant under reused id: %v", err)
	}
	_, mismatchErr := svc.GrantRelationship(ctx, proofActor("manager"), authorization.GrantRelationshipCommand{
		MutationID: mid, ResourceType: "project", ResourceID: "p10", Relation: "member", Subject: subj("user", "z"),
	})
	if !errors.Is(mismatchErr, authorization.ErrMutationMismatch) {
		t.Fatalf("payload mismatch: want ErrMutationMismatch, got %v", mismatchErr)
	}

	tr.add(10, "Stale revision and MutationID payload mismatch return stable errors",
		"command A: GrantRelationship(actor=user:manager, project:p10#member <- user:x, ExpectedRevision=0) against a scope already at revision >= 1",
		fmt.Sprintf("result A: errors.Is(ErrStaleRevision)=%v (a command error, never a domain outcome, nothing committed)", errors.Is(staleErr, authorization.ErrStaleRevision)),
		"command B: reuse one MutationID for two different payloads (project:p10#member <- user:y, then <- user:z)",
		fmt.Sprintf("result B: errors.Is(ErrMutationMismatch)=%v (never a silent overwrite)", errors.Is(mismatchErr, authorization.ErrMutationMismatch)),
	)
	tr.add(10, "Stale revision and MutationID payload mismatch return stable errors", auditLines(sink.all())...)
}

// 11. An exact retry returns the original outcome with Replayed=true.
func proofPoint11(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "project", "p11", "owner", subj("user", "manager"))
	cmd := authorization.GrantRelationshipCommand{
		MutationID: pid("p11", "retry"), ResourceType: "project", ResourceID: "p11",
		Relation: "member", Subject: subj("user", "frank"),
	}
	first, err := svc.GrantRelationship(ctx, proofActor("manager"), cmd)
	if err != nil {
		t.Fatalf("first grant: %v", err)
	}
	if first.Replayed {
		t.Fatal("first application must not be a replay")
	}
	retry, err := svc.GrantRelationship(ctx, proofActor("manager"), cmd) // exact same command
	if err != nil {
		t.Fatalf("retry: %v", err)
	}
	if !retry.Replayed {
		t.Fatal("exact retry must be Replayed=true")
	}
	if retry.Outcome != first.Outcome || retry.Revision != first.Revision {
		t.Fatalf("retry must return the original receipt: first(outcome=%s rev=%d) retry(outcome=%s rev=%d)",
			first.Outcome, first.Revision, retry.Outcome, retry.Revision)
	}

	tr.add(11, "An exact retry returns the original outcome with Replayed=true",
		"command: GrantRelationship(actor=user:manager, project:p11#member <- user:frank), issued twice with the SAME MutationID and payload",
		fmt.Sprintf("first: outcome=%s revision=%d replayed=%v", first.Outcome, first.Revision, first.Replayed),
		fmt.Sprintf("retry: outcome=%s revision=%d replayed=%v (original outcome, no revision bump)", retry.Outcome, retry.Revision, retry.Replayed),
	)
	tr.add(11, "An exact retry returns the original outcome with Replayed=true", auditLines(sink.all())...)
}

// 12. Resource teardown is possible only through the separately held SystemMutator
// command with a recorded reason.
func proofPoint12(t *testing.T, tr *proofTranscript) {
	sink := &capturingAuditSink{}
	comps := proofComposition(t, authzSchema(), sink)
	svc, sm := comps.Service, comps.SystemMutator
	ctx := context.Background()

	trustGrant(t, sm, "project", "p12", "owner", subj("user", "manager"))
	trustGrant(t, sm, "project", "p12", "member", subj("user", "someone"))

	// Structural: the actor-facing Service exposes NO teardown method; teardown is on
	// SystemMutator only.
	_, svcHasTeardown := reflect.TypeOf(svc).MethodByName("TeardownAuthorizationScope")
	_, smHasTeardown := reflect.TypeOf(sm).MethodByName("TeardownAuthorizationScope")

	// A reason is REQUIRED: an empty reason is refused before any write.
	_, emptyErr := sm.TeardownAuthorizationScope(ctx, authorization.TeardownAuthorizationScopeCommand{
		MutationID: pid("p12", "empty-reason"), ResourceType: "project", ResourceID: "p12", Reason: "  ",
	})
	if !errors.Is(emptyErr, authorization.ErrTeardownReasonRequired) {
		t.Fatalf("empty teardown reason: want ErrTeardownReasonRequired, got %v", emptyErr)
	}

	// The trusted teardown zeroes the scope (the one operation allowed to remove the
	// last owner) with an explicit, recorded reason.
	const reason = "az3-4.2 proof: project p12 destroyed by owner request"
	rcpt, err := sm.TeardownAuthorizationScope(ctx, authorization.TeardownAuthorizationScopeCommand{
		MutationID: pid("p12", "teardown"), ResourceType: "project", ResourceID: "p12", Reason: reason,
	})
	if err != nil || rcpt.Outcome != authorization.OutcomeApplied {
		t.Fatalf("teardown: outcome=%v err=%v", outcomeOf(rcpt), err)
	}
	ownerTargets, err := svc.GetRelationTargets(ctx, "project", "p12", "owner")
	if err != nil {
		t.Fatalf("GetRelationTargets owner: %v", err)
	}
	memberTargets, _ := svc.GetRelationTargets(ctx, "project", "p12", "member")
	if len(ownerTargets) != 0 || len(memberTargets) != 0 {
		t.Fatalf("teardown left rows: owners=%d members=%d", len(ownerTargets), len(memberTargets))
	}

	if svcHasTeardown {
		t.Fatal("the actor-facing Service must not expose TeardownAuthorizationScope")
	}
	if !smHasTeardown {
		t.Fatal("SystemMutator must expose TeardownAuthorizationScope")
	}

	// The reason is recorded observably on the audit seam (Detail), never a secret.
	teardownAudited := false
	for _, e := range sink.all() {
		if e.Operation == authorization.OpTeardown && e.Detail == reason {
			teardownAudited = true
		}
	}
	if !teardownAudited {
		t.Fatal("teardown reason was not recorded on the audit seam")
	}

	tr.add(12, "Resource teardown is possible only through the separately held SystemMutator with a recorded reason",
		fmt.Sprintf("structural: actor-facing Service exposes TeardownAuthorizationScope=%v; SystemMutator exposes it=%v", svcHasTeardown, smHasTeardown),
		fmt.Sprintf("precondition: empty reason rejected, errors.Is(ErrTeardownReasonRequired)=%v", errors.Is(emptyErr, authorization.ErrTeardownReasonRequired)),
		"command: SystemMutator.TeardownAuthorizationScope(project:p12, reason=<recorded>)",
		fmt.Sprintf("receipt: outcome=%s revision=%d (the one op allowed to remove the last owner)", rcpt.Outcome, rcpt.Revision),
		fmt.Sprintf("stored-row check after teardown: owner rows=%d member rows=%d", len(ownerTargets), len(memberTargets)),
	)
	tr.add(12, "Resource teardown is possible only through the separately held SystemMutator with a recorded reason", auditLines(sink.all())...)
}

// -----------------------------------------------------------------------------
// Small helpers
// -----------------------------------------------------------------------------

func hasField(t reflect.Type, name string) bool {
	for i := 0; i < t.NumField(); i++ {
		if strings.EqualFold(t.Field(i).Name, name) {
			return true
		}
	}
	return false
}

func checkPrincipal(t *testing.T, svc *authorization.Service, st, sid, permission, rt, rid string) bool {
	t.Helper()
	res, err := svc.Check(context.Background(), authorization.CheckRequest{
		Principal:  authorization.PrincipalRef{Type: st, ID: sid},
		Permission: permission,
		Resource:   authorization.Resource{Type: rt, ID: rid},
	})
	if err != nil {
		t.Fatalf("Check(%s:%s, %s, %s:%s): %v", st, sid, permission, rt, rid, err)
	}
	return res.Allowed
}

func allChecked(t *testing.T, svc *authorization.Service, ids []string) bool {
	t.Helper()
	for _, id := range ids {
		if !check(t, svc, "u1", "view", "space", id) {
			return false
		}
	}
	return true
}

func ownerCount(t *testing.T, svc *authorization.Service, resourceID string) int {
	t.Helper()
	targets, err := svc.GetRelationTargets(context.Background(), "project", resourceID, "owner")
	if err != nil {
		t.Fatalf("GetRelationTargets owner project:%s: %v", resourceID, err)
	}
	return len(targets)
}

func outcomeOf(r *authorization.Receipt) authorization.Outcome {
	if r == nil {
		return ""
	}
	return r.Outcome
}

func targetsString(targets []authorization.RelationTarget) string {
	if len(targets) == 0 {
		return "(none)"
	}
	parts := make([]string, 0, len(targets))
	for _, tgt := range targets {
		s := tgt.Type + ":" + tgt.ID
		if tgt.Relation != "" {
			s += "#" + tgt.Relation
		}
		parts = append(parts, s)
	}
	sort.Strings(parts)
	return strings.Join(parts, ", ")
}

func outcomeTally(m map[string]int) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s=%d", k, m[k]))
	}
	return strings.Join(parts, " ")
}

func short(digest string) string {
	if len(digest) <= 16 {
		return digest
	}
	return digest[:16] + "…"
}
