// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package securityeventsbridge

import (
	"context"
	"encoding/json"
	"fmt"
	fopb "github.com/gopernicus/gopernicus/bridge/transit/fop"
	"github.com/gopernicus/gopernicus/bridge/transit/httpmid"
	"github.com/gopernicus/gopernicus/core/auth/authorization"
	"github.com/gopernicus/gopernicus/core/repositories/auth/securityevents"
	"github.com/gopernicus/gopernicus/sdk/errs"
	"github.com/gopernicus/gopernicus/sdk/fop"
	"github.com/gopernicus/gopernicus/sdk/validation"
	"github.com/gopernicus/gopernicus/sdk/web"
	"net/http"
	"strings"
	"time"
)

// Ensure imports are used.
var _ = json.RawMessage{}
var _ = fmt.Sprintf

var _ = strings.SplitN
var _ = time.Time{}

// =============================================================================
// Handlers
// =============================================================================

// httpList handles GET /security-events.
func (b *Bridge) httpList(w http.ResponseWriter, r *http.Request) {
	qp := parseQueryParamsList(r)

	page, err := fop.ParsePageStringCursor(qp.Limit, qp.Cursor, securityevents.MaxLimitList)
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest("invalid pagination: "+err.Error()))
		return
	}

	filter, err := parseFilterList(qp)
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest("invalid filter: "+err.Error()))
		return
	}

	orderBy, err := parseOrderBy(qp.Order)
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest("invalid order: "+err.Error()))
		return
	}

	// Prefilter: resolve which specific IDs this subject can read.
	subject := httpmid.GetSubjectInfo(r.Context())
	prefilterResult, err := b.authorizer.LookupResources(r.Context(), authorization.Subject{
		Type: subject.Type,
		ID:   subject.ID,
	}, "read", "security_event")
	if err != nil {
		b.log.ErrorContext(r.Context(), "prefilter authorization", "error", err)
		web.RespondJSONError(w, web.ErrInternal("authorization error"))
		return
	}
	if !prefilterResult.Unrestricted {
		filter.AuthorizedIDs = prefilterResult.IDs
	}
	records, pagination, err := b.securityEventRepository.List(r.Context(), filter, orderBy, page)
	if err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	web.RespondJSONOK(w, fopb.PageResponse[securityevents.SecurityEvent]{
		Data:       records,
		Pagination: pagination,
	})
}

// httpGet handles GET /security-events/{event_id}.
func (b *Bridge) httpGet(w http.ResponseWriter, r *http.Request) {

	eventID := web.Param(r, "event_id")
	if eventID == "" {
		web.RespondJSONError(w, web.ErrBadRequest("event_id is required"))
		return
	}

	record, err := b.securityEventRepository.Get(r.Context(), eventID)
	if err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	web.RespondJSONOK(w, fopb.RecordResponse[securityevents.SecurityEvent]{Record: record})
}

// httpCreate handles POST /security-events.
func (b *Bridge) httpCreate(w http.ResponseWriter, r *http.Request) {

	req, err := web.DecodeJSON[CreateSecurityEventRequest](r)
	if err != nil {
		web.RespondJSONError(w, web.ErrValidation(err))
		return
	}

	input, err := req.ToRepo()
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest(err.Error()))
		return
	}

	record, err := b.securityEventRepository.Create(r.Context(), input)
	if err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	if err := b.createAuthRelationships(r.Context(), record); err != nil {
		b.log.ErrorContext(r.Context(), "create auth relationships", "error", err)
		web.RespondJSONError(w, web.ErrInternal("create auth relationships"))
		return
	}

	web.RespondJSONCreated(w, fopb.RecordResponse[securityevents.SecurityEvent]{Record: record})
}

// httpUpdate handles PUT /security-events/{event_id}.
func (b *Bridge) httpUpdate(w http.ResponseWriter, r *http.Request) {

	eventID := web.Param(r, "event_id")
	if eventID == "" {
		web.RespondJSONError(w, web.ErrBadRequest("event_id is required"))
		return
	}

	req, err := web.DecodeJSON[UpdateSecurityEventRequest](r)
	if err != nil {
		web.RespondJSONError(w, web.ErrValidation(err))
		return
	}

	input, err := req.ToRepo()
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest(err.Error()))
		return
	}

	record, err := b.securityEventRepository.Update(r.Context(), eventID, input)
	if err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	web.RespondJSONOK(w, fopb.RecordResponse[securityevents.SecurityEvent]{Record: record})
}

// httpDelete handles DELETE /security-events/{event_id}.
func (b *Bridge) httpDelete(w http.ResponseWriter, r *http.Request) {

	eventID := web.Param(r, "event_id")
	if eventID == "" {
		web.RespondJSONError(w, web.ErrBadRequest("event_id is required"))
		return
	}

	if err := b.deleteAuthRelationships(r.Context(), "security_event", eventID); err != nil {
		b.log.ErrorContext(r.Context(), "delete auth relationships", "error", err)
		web.RespondJSONError(w, web.ErrInternal("delete auth relationships"))
		return
	}
	if err := b.securityEventRepository.Delete(r.Context(), eventID); err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	web.RespondNoContent(w)
}

// =============================================================================
// Auth Relationship Creation
// =============================================================================

func (b *Bridge) createAuthRelationships(ctx context.Context, record securityevents.SecurityEvent) error {
	if b.authorizer == nil {
		return nil
	}

	subject := httpmid.GetSubject(ctx)
	parts := strings.SplitN(subject, ":", 2)
	if len(parts) != 2 {
		return fmt.Errorf("invalid subject format: %q", subject)
	}
	subjectType, subjectID := parts[0], parts[1]
	_, _ = subjectType, subjectID

	return b.authorizer.CreateRelationships(ctx, []authorization.CreateRelationship{
		{
			ResourceType: "security_event",
			ResourceID:   record.EventID,
			Relation:     "owner",
			SubjectType:  subjectType,
			SubjectID:    subjectID,
		},
	})
}

// =============================================================================
// Auth Relationship Cleanup
// =============================================================================

func (b *Bridge) deleteAuthRelationships(ctx context.Context, resourceType, resourceID string) error {
	if b.authorizer == nil {
		return nil
	}
	return b.authorizer.DeleteResourceRelationships(ctx, resourceType, resourceID)
}

// =============================================================================
// Query Parsing Helpers
// =============================================================================

// QueryParamsList holds raw query string values for List.
type QueryParamsList struct {
	Limit        string
	Cursor       string
	Order        string
	SearchTerm   string
	EventID      string
	UserID       string
	EventType    string
	EventStatus  string
	EventDetails string
	IpAddress    string
	UserAgent    string
	CreatedAt    string
}

func parseQueryParamsList(r *http.Request) QueryParamsList {
	q := r.URL.Query()
	return QueryParamsList{
		Limit:        q.Get("limit"),
		Cursor:       q.Get("cursor"),
		Order:        q.Get("order"),
		SearchTerm:   q.Get("s"),
		EventID:      q.Get("event_id"),
		UserID:       q.Get("user_id"),
		EventType:    q.Get("event_type"),
		EventStatus:  q.Get("event_status"),
		EventDetails: q.Get("event_details"),
		IpAddress:    q.Get("ip_address"),
		UserAgent:    q.Get("user_agent"),
		CreatedAt:    q.Get("created_at"),
	}
}

func parseFilterList(qp QueryParamsList) (securityevents.FilterList, error) {
	var filter securityevents.FilterList

	if qp.SearchTerm != "" {
		filter.SearchTerm = &qp.SearchTerm
	}

	if qp.EventID != "" {
		filter.EventID = &qp.EventID
	}
	if qp.UserID != "" {
		filter.UserID = &qp.UserID
	}
	if qp.EventType != "" {
		filter.EventType = &qp.EventType
	}
	if qp.EventStatus != "" {
		filter.EventStatus = &qp.EventStatus
	}
	if qp.IpAddress != "" {
		filter.IpAddress = &qp.IpAddress
	}
	if qp.UserAgent != "" {
		filter.UserAgent = &qp.UserAgent
	}
	if qp.CreatedAt != "" {
		v, err := time.Parse(time.RFC3339, qp.CreatedAt)
		if err != nil {
			return filter, fmt.Errorf("invalid created_at: %w", err)
		}
		filter.CreatedAt = &v
	}
	return filter, nil
}

func parseOrderBy(order string) (fop.Order, error) {
	return fop.ParseOrder(
		securityevents.OrderByFields,
		order,
		fop.NewOrder(securityevents.DefaultOrderBy, securityevents.DefaultOrderDirection),
	)
}

// =============================================================================
// Request Models
// =============================================================================

// CreateSecurityEventRequest is the HTTP request for creating a securityEvent.
type CreateSecurityEventRequest struct {
	EventID      string           `json:"event_id,omitempty"`
	UserID       *string          `json:"user_id,omitempty"`
	EventType    string           `json:"event_type,omitempty"`
	EventStatus  string           `json:"event_status,omitempty"`
	EventDetails *json.RawMessage `json:"event_details,omitempty"`
	IpAddress    *string          `json:"ip_address,omitempty"`
	UserAgent    *string          `json:"user_agent,omitempty"`
}

// Validate checks all field constraints. Called automatically by web.DecodeJSON.
func (r *CreateSecurityEventRequest) Validate() error {
	var errs web.FieldErrors

	errs.AddErr("event_type", validation.Required("event_type", r.EventType))
	errs.AddErr("event_type", validation.MaxLength("event_type", r.EventType, 50))
	errs.AddErr("event_status", validation.Required("event_status", r.EventStatus))
	errs.AddErr("event_status", validation.MaxLength("event_status", r.EventStatus, 20))
	errs.AddErr("ip_address", validation.MaxLengthPtr("ip_address", r.IpAddress, 45))
	errs.AddErr("user_agent", validation.MaxLengthPtr("user_agent", r.UserAgent, 500))
	return errs.Err()
}

// ToRepo converts the validated request to a repository input.
func (r CreateSecurityEventRequest) ToRepo() (securityevents.CreateSecurityEvent, error) {
	return securityevents.CreateSecurityEvent{
		EventID:      r.EventID,
		UserID:       r.UserID,
		EventType:    r.EventType,
		EventStatus:  r.EventStatus,
		EventDetails: r.EventDetails,
		IpAddress:    r.IpAddress,
		UserAgent:    r.UserAgent,
	}, nil
}

// UpdateSecurityEventRequest is the HTTP request for updating a securityEvent.
type UpdateSecurityEventRequest struct {
	UserID       *string          `json:"user_id,omitempty"`
	EventType    *string          `json:"event_type,omitempty"`
	EventStatus  *string          `json:"event_status,omitempty"`
	EventDetails *json.RawMessage `json:"event_details,omitempty"`
	IpAddress    *string          `json:"ip_address,omitempty"`
	UserAgent    *string          `json:"user_agent,omitempty"`
}

// Validate checks all field constraints. Called automatically by web.DecodeJSON.
func (r *UpdateSecurityEventRequest) Validate() error {
	var errs web.FieldErrors

	errs.AddErr("event_type", validation.MaxLengthPtr("event_type", r.EventType, 50))
	errs.AddErr("event_status", validation.MaxLengthPtr("event_status", r.EventStatus, 20))
	errs.AddErr("ip_address", validation.MaxLengthPtr("ip_address", r.IpAddress, 45))
	errs.AddErr("user_agent", validation.MaxLengthPtr("user_agent", r.UserAgent, 500))
	return errs.Err()
}

// ToRepo converts the validated request to a repository input.
func (r UpdateSecurityEventRequest) ToRepo() (securityevents.UpdateSecurityEvent, error) {
	return securityevents.UpdateSecurityEvent{
		UserID:       r.UserID,
		EventType:    r.EventType,
		EventStatus:  r.EventStatus,
		EventDetails: r.EventDetails,
		IpAddress:    r.IpAddress,
		UserAgent:    r.UserAgent,
	}, nil
}

// =============================================================================
// OpenAPI Spec
// =============================================================================

// =============================================================================
// Generated Route Registration
// =============================================================================

// addGeneratedRoutes registers all generated HTTP routes with middleware.
// Called from AddHttpRoutes in routes.go. Do not edit — regenerated from bridge.yml.
func (b *Bridge) addGeneratedRoutes(group *web.RouteGroup) {
	group.GET("/security-events", b.httpList,
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors),
		httpmid.RateLimit(b.rateLimiter, b.log),
		httpmid.AuthorizeType(b.authorizer, b.log, b.jsonErrors, "security_event", "list"),
	)

	group.GET("/security-events/{event_id}", b.httpGet,
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors),
		httpmid.RateLimit(b.rateLimiter, b.log),
		httpmid.AuthorizeParam(b.authorizer, b.log, b.jsonErrors, "security_event", "read", "event_id"),
	)

	group.POST("/security-events", b.httpCreate,
		httpmid.MaxBodySize(1048576),
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors),
		httpmid.RateLimit(b.rateLimiter, b.log),
	)

	group.PUT("/security-events/{event_id}", b.httpUpdate,
		httpmid.MaxBodySize(1048576),
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors),
		httpmid.RateLimit(b.rateLimiter, b.log),
		httpmid.AuthorizeParam(b.authorizer, b.log, b.jsonErrors, "security_event", "update", "event_id"),
	)

	group.DELETE("/security-events/{event_id}", b.httpDelete,
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors),
		httpmid.RateLimit(b.rateLimiter, b.log),
		httpmid.AuthorizeParam(b.authorizer, b.log, b.jsonErrors, "security_event", "delete", "event_id"),
	)

}

// addGeneratedOpenAPISpec returns OpenAPI route specs for all generated handlers.
func (b *Bridge) addGeneratedOpenAPISpec() []web.RouteSpec {
	return []web.RouteSpec{
		{
			Method:        "GET",
			Path:          "/security-events",
			Summary:       "List securityevents",
			Tags:          []string{"SecurityEvents"},
			Paginated:     true,
			Authenticated: true, // any
			ResponseBody:  fopb.PageResponse[securityevents.SecurityEvent]{},
		},
		{
			Method:        "GET",
			Path:          "/security-events/{event_id}",
			Summary:       "Get securityevent",
			Tags:          []string{"SecurityEvents"},
			Authenticated: true, // any
			ResponseBody:  fopb.RecordResponse[securityevents.SecurityEvent]{},
		},
		{
			Method:        "POST",
			Path:          "/security-events",
			Summary:       "Create securityevent",
			Tags:          []string{"SecurityEvents"},
			Authenticated: true, // any
			RequestBody:   CreateSecurityEventRequest{},
			ResponseBody:  fopb.RecordResponse[securityevents.SecurityEvent]{},
			StatusCode:    201,
		},
		{
			Method:        "PUT",
			Path:          "/security-events/{event_id}",
			Summary:       "Update securityevent",
			Tags:          []string{"SecurityEvents"},
			Authenticated: true, // any
			RequestBody:   UpdateSecurityEventRequest{},
			ResponseBody:  fopb.RecordResponse[securityevents.SecurityEvent]{},
		},
		{
			Method:        "DELETE",
			Path:          "/security-events/{event_id}",
			Summary:       "Delete securityevent",
			Tags:          []string{"SecurityEvents"},
			Authenticated: true, // any
			StatusCode:    204,
		},
	}
}
