//go:build e2e

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package securityeventsbridge

import (
	"context"
	"encoding/json"
	"net/url"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gopernicus/gopernicus/core/auth/authorization"
	"github.com/gopernicus/gopernicus/core/repositories/auth/securityevents"
	"github.com/gopernicus/gopernicus/core/repositories/auth/securityevents/securityeventspgx"

	"github.com/gopernicus/gopernicus/sdk/logger"
	"github.com/gopernicus/gopernicus/workshop/testing/testauth"
	"github.com/gopernicus/gopernicus/workshop/testing/testhttp"
	"github.com/gopernicus/gopernicus/workshop/testing/testpgx"
	"github.com/gopernicus/gopernicus/workshop/testing/testserver"
)

// Ensure imports are used.
var _ = assert.Equal

// e2eDB is the test database handle the stack boots against.
type e2eDB = *testpgx.TestPGX

// e2eAuthSchema is the entity's resource schema, rendered locally — the
// domain composite package exports AuthSchema() but importing it here is an
// import cycle (the composite imports this bridge package). The bridge's
// own @auth.create relationship writes at POST time grant the suite's
// subject the relations these permissions check.
func e2eAuthSchema() []authorization.ResourceSchema {
	return []authorization.ResourceSchema{
		{
			Name: "security_event",
			Def: authorization.ResourceTypeDef{
				Relations: map[string]authorization.RelationDef{
					"owner": {AllowedSubjects: []authorization.SubjectTypeRef{
						{Type: "user"},
						{Type: "service_account"},
					}},
				},
				Permissions: map[string]authorization.PermissionRule{
					"list": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"create": authorization.AnyOf(
						authorization.Direct("authenticated"),
					),
					"read": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"update": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"delete": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"manage": authorization.AnyOf(
						authorization.Direct("owner"),
					),
				},
			},
		},
	}
}

// setupE2EServer boots the full HTTP stack for SecurityEvent against a fresh
// database: store → repository → bridge, served via testserver.ServeBridge.
// It returns the test DB too so FK parents can be seeded into the same store
// the server reads. migrateE2EDB is defined in e2e_test.go (bootstrap file).
func setupE2EServer(t *testing.T) (*testhttp.Client, e2eDB) {
	t.Helper()

	if testing.Short() {
		t.Skip("skipping e2e test")
	}

	ctx := context.Background()
	db := testpgx.SetupTestPGX(t, ctx, testpgx.WithMigrations(migrateE2EDB))

	store := securityeventspgx.NewStore(logger.NewNoop(), db.Pool)
	repo := securityevents.NewRepository(securityevents.NewCacheStore(store, nil))
	authenticator, signer := testauth.Authenticator("e2etest")
	authorizer, _ := testauth.AuthorizerWithStore(authorization.NewSchema(e2eAuthSchema()))
	bridge := NewBridge(logger.NewNoop(), repo, testserver.NewRateLimiter(), authenticator, authorizer)

	client := testserver.ServeBridge(t, bridge)

	// The exercised routes authenticate via the JWT fast path (signature
	// only) — a minted token needs no database rows.
	client.SetBearerToken(testauth.MintAccessToken(signer, "e2e-test-user"))
	return client, db
}

// seededCreateSecurityEventRequest builds a valid create request, populating
// foreign-key fields from parent rows seeded into db.
func seededCreateSecurityEventRequest(t *testing.T, db e2eDB) CreateSecurityEventRequest {
	t.Helper()
	_ = db
	return validCreateSecurityEventRequest()
}

// The suite runs authenticated — one anonymous request must still be
// rejected, proving enforcement is live in this exact stack.
func TestE2ESecurityEventRequiresAuthentication(t *testing.T) {
	client, db := setupE2EServer(t)
	anon := client.Anonymous()
	anon.Post(t, "/security-events", seededCreateSecurityEventRequest(t, db)).RequireStatus(t, 401)
}

func TestE2ESecurityEventCreateAndGet(t *testing.T) {
	client, db := setupE2EServer(t)

	resp := client.Post(t, "/security-events", seededCreateSecurityEventRequest(t, db))
	resp.RequireStatus(t, 201)
	id := resp.String(t, "record.event_id")
	require.NotEmpty(t, id)

	got := client.Get(t, "/security-events/"+id)
	got.RequireStatus(t, 200)
	assert.Equal(t, id, got.String(t, "record.event_id"))

	t.Run("not found", func(t *testing.T) {
		id := "nonexistent-e2e-id"
		client.Get(t, "/security-events/"+id).RequireStatus(t, 403)
	})
}

func TestE2ESecurityEventList(t *testing.T) {
	client, db := setupE2EServer(t)

	client.Post(t, "/security-events", seededCreateSecurityEventRequest(t, db)).RequireStatus(t, 201)
	client.Get(t, "/security-events").RequireStatus(t, 200)
}

func TestE2ESecurityEventPaginationAdvance(t *testing.T) {
	client, db := setupE2EServer(t)

	// Three rows, then walk two pages of two — keyset pagination must not
	// repeat a row across the page boundary (page1 ∩ page2 = ∅).
	for i := 0; i < 3; i++ {
		client.Post(t, "/security-events", seededCreateSecurityEventRequest(t, db)).RequireStatus(t, 201)
	}

	page1 := client.Get(t, "/security-events?limit=2")
	page1.RequireStatus(t, 200)
	cursor := page1.String(t, "pagination.next_cursor")
	require.NotEmpty(t, cursor, "a full first page must yield a next cursor")

	page2 := client.Get(t, "/security-events?limit=2&cursor="+url.QueryEscape(cursor))
	page2.RequireStatus(t, 200)

	seen := map[string]bool{}
	for _, row := range page1.Data(t) {
		if m, ok := row.(map[string]any); ok {
			seen[toStr(m["event_id"])] = true
		}
	}
	advanced := false
	for _, row := range page2.Data(t) {
		m, ok := row.(map[string]any)
		if !ok {
			continue
		}
		pk := toStr(m["event_id"])
		assert.False(t, seen[pk], "row %s appears on both pages", pk)
		advanced = true
	}
	assert.True(t, advanced, "second page should contain the remaining row")
}

func toStr(v any) string {
	s, _ := v.(string)
	return s
}

func TestE2ESecurityEventDelete(t *testing.T) {
	client, db := setupE2EServer(t)

	resp := client.Post(t, "/security-events", seededCreateSecurityEventRequest(t, db))
	resp.RequireStatus(t, 201)
	id := resp.String(t, "record.event_id")
	require.NotEmpty(t, id)

	client.Delete(t, "/security-events/"+id).RequireStatus(t, 204)
	client.Get(t, "/security-events/"+id).RequireStatus(t, 403)
}

func TestE2ESecurityEventSQLInjection(t *testing.T) {
	client, db := setupE2EServer(t)

	// One known row — an executed OR-1=1 style injection would leak it.
	client.Post(t, "/security-events", seededCreateSecurityEventRequest(t, db)).RequireStatus(t, 201)

	payloads := []string{
		`' OR 1=1 --`,
		`'; DROP TABLE zzz_not_a_table; --`,
		`" OR ""="`,
	}

	// String filter params are parameterized match values: a payload must
	// never error the server and must never match the seeded row.
	stringParams := []string{"event_id", "user_id", "event_type", "event_status", "ip_address", "user_agent", "s"}
	for _, param := range stringParams {
		for _, payload := range payloads {
			resp := client.Get(t, "/security-events?"+url.Values{param: []string{payload}}.Encode())
			require.Less(t, resp.StatusCode, 500,
				"param %q payload %q must not cause a server error", param, payload)
			if resp.StatusCode == 200 {
				// Empty result sets marshal as data: null — only a non-empty
				// array is a leak.
				if data, ok := resp.JSON(t)["data"].([]any); ok {
					assert.Empty(t, data,
						"param %q payload %q matched rows — possible injection", param, payload)
				}
			}
		}
	}

	// Non-string filters and order/limit/cursor reject or ignore garbage —
	// never a server error.
	otherParams := []string{"event_details", "created_at", "order", "limit", "cursor"}
	for _, param := range otherParams {
		for _, payload := range payloads {
			resp := client.Get(t, "/security-events?"+url.Values{param: []string{payload}}.Encode())
			require.Less(t, resp.StatusCode, 500,
				"param %q payload %q must not cause a server error", param, payload)
		}
	}
}

func TestE2ESecurityEventOversizedPayload(t *testing.T) {
	client, db := setupE2EServer(t)

	// A body past the route's max_body_size (1048576 bytes) must
	// be rejected with 413, not accepted or 500'd. Pad a valid request with a
	// huge string field the server ignores so only the size trips the limit.
	raw, err := json.Marshal(seededCreateSecurityEventRequest(t, db))
	require.NoError(t, err)
	var body map[string]any
	require.NoError(t, json.Unmarshal(raw, &body))
	body["_padding"] = strings.Repeat("A", 1048576+1)

	client.Post(t, "/security-events", body).RequireStatus(t, 413)
}
