//go:build security

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package invitationsbridge

import (
	"testing"
)

func TestSecurityInvitationAuthenticationRequired(t *testing.T) {
	client := setupSecurityServer(t)
	if client == nil {
		t.Skip("setupSecurityServer not wired — see security_test.go to enable enforcement probes")
	}

	t.Run("List rejects anonymous", func(t *testing.T) {
		client.Get(t, "/invitations").RequireStatus(t, 401)
	})

	t.Run("Get rejects anonymous", func(t *testing.T) {
		client.Get(t, "/invitations/probe-id").RequireStatus(t, 401)
	})

	t.Run("Create rejects anonymous", func(t *testing.T) {
		client.Post(t, "/invitations", nil).RequireStatus(t, 401)
	})

	t.Run("Update rejects anonymous", func(t *testing.T) {
		client.Put(t, "/invitations/probe-id", nil).RequireStatus(t, 401)
	})

	t.Run("SoftDelete rejects anonymous", func(t *testing.T) {
		client.Put(t, "/invitations/probe-id/delete", nil).RequireStatus(t, 401)
	})

	t.Run("Archive rejects anonymous", func(t *testing.T) {
		client.Put(t, "/invitations/probe-id/archive", nil).RequireStatus(t, 401)
	})

	t.Run("Restore rejects anonymous", func(t *testing.T) {
		client.Put(t, "/invitations/probe-id/restore", nil).RequireStatus(t, 401)
	})

	t.Run("Delete rejects anonymous", func(t *testing.T) {
		client.Delete(t, "/invitations/probe-id").RequireStatus(t, 401)
	})

	// Same routes with a malformed bearer token — still 401.
	client.SetBearerToken("not-a-real-token")

	t.Run("List rejects malformed token", func(t *testing.T) {
		client.Get(t, "/invitations").RequireStatus(t, 401)
	})

	t.Run("Get rejects malformed token", func(t *testing.T) {
		client.Get(t, "/invitations/probe-id").RequireStatus(t, 401)
	})

	t.Run("Create rejects malformed token", func(t *testing.T) {
		client.Post(t, "/invitations", nil).RequireStatus(t, 401)
	})

	t.Run("Update rejects malformed token", func(t *testing.T) {
		client.Put(t, "/invitations/probe-id", nil).RequireStatus(t, 401)
	})

	t.Run("SoftDelete rejects malformed token", func(t *testing.T) {
		client.Put(t, "/invitations/probe-id/delete", nil).RequireStatus(t, 401)
	})

	t.Run("Archive rejects malformed token", func(t *testing.T) {
		client.Put(t, "/invitations/probe-id/archive", nil).RequireStatus(t, 401)
	})

	t.Run("Restore rejects malformed token", func(t *testing.T) {
		client.Put(t, "/invitations/probe-id/restore", nil).RequireStatus(t, 401)
	})

	t.Run("Delete rejects malformed token", func(t *testing.T) {
		client.Delete(t, "/invitations/probe-id").RequireStatus(t, 401)
	})
}
