// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.

package jobqueuepgx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
	"github.com/gopernicus/gopernicus/sdk/fop"

	"github.com/gopernicus/gopernicus/core/repositories/jobs/jobqueue"
)

// Store implements jobqueue.Storer using PostgreSQL via pgx.
type Store struct {
	log *slog.Logger
	db  pgxdb.Querier
}

// NewStore creates a new jobqueue store backed by the given Querier.
// Querier is satisfied by both *pgxpool.Pool and pgx.Tx, enabling
// transaction composition.
func NewStore(log *slog.Logger, db pgxdb.Querier) *Store {
	return &Store{log: log, db: db}
}

// compile-time interface check (Storer is defined in repository.go)
var _ jobqueue.Storer = (*Store)(nil)

// ─── error mapping ────────────────────────────────────────────────────────────

func (s *Store) mapError(err error) error {
	dbErr := pgxdb.HandlePgError(err)
	switch {
	case errors.Is(dbErr, pgxdb.ErrDBDuplicatedEntry):
		return jobqueue.ErrJobQueueAlreadyExists
	case errors.Is(dbErr, pgxdb.ErrDBForeignKeyViolation):
		return jobqueue.ErrJobQueueInvalidReference
	case errors.Is(dbErr, pgxdb.ErrDBCheckViolation),
		errors.Is(dbErr, pgxdb.ErrDBNotNullViolation):
		return jobqueue.ErrJobQueueInvalidInput
	default:
		return dbErr
	}
}

// ─── methods ──────────────────────────────────────────────────────────────────

func (s *Store) List(ctx context.Context, filter jobqueue.FilterList, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]jobqueue.JobQueue, error) {
	data := pgx.NamedArgs{}

	baseSQL := `SELECT *
FROM public.job_queue
WHERE $conditions AND $search`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListConditionsFilter(filter, data))
	baseSQL = replaceFilterPlaceholder(baseSQL, "$search", generatedApplyListSearchFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := jobqueue.OrderByFields[orderBy.Field]
	if !ok {
		of = jobqueue.OrderByFields[jobqueue.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "job_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "job_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[jobqueue.JobQueue])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) Get(ctx context.Context, jobID string) (jobqueue.JobQueue, error) {
	query := `SELECT job_id, event_type, correlation_id, tenant_id, aggregate_type, aggregate_id, payload, occurred_at, status, priority, retry_count, max_retries, worker_name, failure_reason, scheduled_for, created_at, updated_at, staged_at, completed_at
FROM public.job_queue
WHERE job_id = @job_id`

	args := pgx.NamedArgs{
		"job_id": jobID,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return jobqueue.JobQueue{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[jobqueue.JobQueue])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return jobqueue.JobQueue{}, jobqueue.ErrJobQueueNotFound
		}
		return jobqueue.JobQueue{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) Create(ctx context.Context, input jobqueue.CreateJobQueue) (jobqueue.JobQueue, error) {
	now := time.Now().UTC()
	query := `INSERT INTO public.job_queue (job_id, event_type, correlation_id, tenant_id, aggregate_type, aggregate_id, payload, occurred_at, status, priority, retry_count, max_retries, worker_name, failure_reason, scheduled_for, staged_at, completed_at, created_at, updated_at)
		VALUES (@job_id, @event_type, @correlation_id, @tenant_id, @aggregate_type, @aggregate_id, @payload, @occurred_at, @status, @priority, @retry_count, @max_retries, @worker_name, @failure_reason, @scheduled_for, @staged_at, @completed_at, @_created_at, @_updated_at)
		RETURNING job_id, event_type, correlation_id, tenant_id, aggregate_type, aggregate_id, payload, occurred_at, status, priority, retry_count, max_retries, worker_name, failure_reason, scheduled_for, created_at, updated_at, staged_at, completed_at`

	args := pgx.NamedArgs{
		"job_id":         input.JobID,
		"event_type":     input.EventType,
		"correlation_id": input.CorrelationID,
		"tenant_id":      input.TenantID,
		"aggregate_type": input.AggregateType,
		"aggregate_id":   input.AggregateID,
		"payload":        input.Payload,
		"occurred_at":    input.OccurredAt,
		"status":         input.Status,
		"priority":       input.Priority,
		"retry_count":    input.RetryCount,
		"max_retries":    input.MaxRetries,
		"worker_name":    input.WorkerName,
		"failure_reason": input.FailureReason,
		"scheduled_for":  input.ScheduledFor,
		"staged_at":      input.StagedAt,
		"completed_at":   input.CompletedAt,
		"_created_at":    now,
		"_updated_at":    now,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return jobqueue.JobQueue{}, s.mapError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[jobqueue.JobQueue])
	if err != nil {
		return jobqueue.JobQueue{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Update(ctx context.Context, jobID string, input jobqueue.UpdateJobQueue) (jobqueue.JobQueue, error) {
	buf := bytes.NewBufferString("UPDATE public.job_queue SET ")
	args := pgx.NamedArgs{
		"job_id": jobID,
	}
	var setClauses []string
	if input.EventType != nil {
		setClauses = append(setClauses, "event_type = @event_type")
		args["event_type"] = *input.EventType
	}
	if input.CorrelationID != nil {
		setClauses = append(setClauses, "correlation_id = @correlation_id")
		args["correlation_id"] = *input.CorrelationID
	}
	if input.TenantID != nil {
		setClauses = append(setClauses, "tenant_id = @tenant_id")
		args["tenant_id"] = *input.TenantID
	}
	if input.AggregateType != nil {
		setClauses = append(setClauses, "aggregate_type = @aggregate_type")
		args["aggregate_type"] = *input.AggregateType
	}
	if input.AggregateID != nil {
		setClauses = append(setClauses, "aggregate_id = @aggregate_id")
		args["aggregate_id"] = *input.AggregateID
	}
	if input.Payload != nil {
		setClauses = append(setClauses, "payload = @payload")
		args["payload"] = *input.Payload
	}
	if input.OccurredAt != nil {
		setClauses = append(setClauses, "occurred_at = @occurred_at")
		args["occurred_at"] = *input.OccurredAt
	}
	if input.Status != nil {
		setClauses = append(setClauses, "status = @status")
		args["status"] = *input.Status
	}
	if input.Priority != nil {
		setClauses = append(setClauses, "priority = @priority")
		args["priority"] = *input.Priority
	}
	if input.RetryCount != nil {
		setClauses = append(setClauses, "retry_count = @retry_count")
		args["retry_count"] = *input.RetryCount
	}
	if input.MaxRetries != nil {
		setClauses = append(setClauses, "max_retries = @max_retries")
		args["max_retries"] = *input.MaxRetries
	}
	if input.WorkerName != nil {
		setClauses = append(setClauses, "worker_name = @worker_name")
		args["worker_name"] = *input.WorkerName
	}
	if input.FailureReason != nil {
		setClauses = append(setClauses, "failure_reason = @failure_reason")
		args["failure_reason"] = *input.FailureReason
	}
	if input.ScheduledFor != nil {
		setClauses = append(setClauses, "scheduled_for = @scheduled_for")
		args["scheduled_for"] = *input.ScheduledFor
	}
	if input.UpdatedAt != nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = *input.UpdatedAt
	}
	if input.StagedAt != nil {
		setClauses = append(setClauses, "staged_at = @staged_at")
		args["staged_at"] = *input.StagedAt
	}
	if input.CompletedAt != nil {
		setClauses = append(setClauses, "completed_at = @completed_at")
		args["completed_at"] = *input.CompletedAt
	}

	// Auto-set updated_at if not explicitly provided.
	if input.UpdatedAt == nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = time.Now().UTC()
	}

	if len(setClauses) == 0 {
		return jobqueue.JobQueue{}, fmt.Errorf("no fields to update")
	}

	buf.WriteString(strings.Join(setClauses, ", "))
	buf.WriteString(" WHERE job_id = @job_id")
	buf.WriteString(" RETURNING job_id, event_type, correlation_id, tenant_id, aggregate_type, aggregate_id, payload, occurred_at, status, priority, retry_count, max_retries, worker_name, failure_reason, scheduled_for, created_at, updated_at, staged_at, completed_at")

	rows, err := s.db.Query(ctx, buf.String(), args)
	if err != nil {
		return jobqueue.JobQueue{}, s.mapError(err)
	}
	defer rows.Close()
	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[jobqueue.JobQueue])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return jobqueue.JobQueue{}, jobqueue.ErrJobQueueNotFound
		}
		return jobqueue.JobQueue{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Delete(ctx context.Context, jobID string) error {
	args := pgx.NamedArgs{
		"job_id": jobID,
	}

	query := `DELETE FROM public.job_queue
WHERE job_id = @job_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return jobqueue.ErrJobQueueNotFound
	}

	return nil
}

// ─── filter placeholder substitution ─────────────────────────────────────────

func replaceFilterPlaceholder(sql, placeholder, fragment string) string {
	if fragment == "" {
		fragment = "TRUE"
	}
	return strings.Replace(sql, placeholder, "("+fragment+")", 1)
}

// ─── per-function named filters ──────────────────────────────────────────────

func generatedApplyListConditionsFilter(filter jobqueue.FilterList, data pgx.NamedArgs) string {
	var conditions []string
	if filter.JobID != nil {
		conditions = append(conditions, "job_id = @filter_job_id")
		data["filter_job_id"] = *filter.JobID
	}
	if filter.EventType != nil {
		conditions = append(conditions, "event_type = @filter_event_type")
		data["filter_event_type"] = *filter.EventType
	}
	if filter.CorrelationID != nil {
		conditions = append(conditions, "correlation_id = @filter_correlation_id")
		data["filter_correlation_id"] = *filter.CorrelationID
	}
	if filter.TenantID != nil {
		conditions = append(conditions, "tenant_id = @filter_tenant_id")
		data["filter_tenant_id"] = *filter.TenantID
	}
	if filter.AggregateType != nil {
		conditions = append(conditions, "aggregate_type = @filter_aggregate_type")
		data["filter_aggregate_type"] = *filter.AggregateType
	}
	if filter.AggregateID != nil {
		conditions = append(conditions, "aggregate_id = @filter_aggregate_id")
		data["filter_aggregate_id"] = *filter.AggregateID
	}
	if filter.Payload != nil {
		conditions = append(conditions, "payload = @filter_payload")
		data["filter_payload"] = *filter.Payload
	}
	if filter.OccurredAt != nil {
		conditions = append(conditions, "occurred_at = @filter_occurred_at")
		data["filter_occurred_at"] = *filter.OccurredAt
	}
	if filter.OccurredAtAfter != nil {
		conditions = append(conditions, "occurred_at >= @filter_occurred_at_after")
		data["filter_occurred_at_after"] = *filter.OccurredAtAfter
	}
	if filter.OccurredAtBefore != nil {
		conditions = append(conditions, "occurred_at <= @filter_occurred_at_before")
		data["filter_occurred_at_before"] = *filter.OccurredAtBefore
	}
	if filter.Status != nil {
		conditions = append(conditions, "status = @filter_status")
		data["filter_status"] = *filter.Status
	}
	if filter.Priority != nil {
		conditions = append(conditions, "priority = @filter_priority")
		data["filter_priority"] = *filter.Priority
	}
	if filter.RetryCount != nil {
		conditions = append(conditions, "retry_count = @filter_retry_count")
		data["filter_retry_count"] = *filter.RetryCount
	}
	if filter.MaxRetries != nil {
		conditions = append(conditions, "max_retries = @filter_max_retries")
		data["filter_max_retries"] = *filter.MaxRetries
	}
	if filter.WorkerName != nil {
		conditions = append(conditions, "worker_name = @filter_worker_name")
		data["filter_worker_name"] = *filter.WorkerName
	}
	if filter.FailureReason != nil {
		conditions = append(conditions, "failure_reason = @filter_failure_reason")
		data["filter_failure_reason"] = *filter.FailureReason
	}
	if filter.ScheduledFor != nil {
		conditions = append(conditions, "scheduled_for = @filter_scheduled_for")
		data["filter_scheduled_for"] = *filter.ScheduledFor
	}
	if filter.ScheduledForAfter != nil {
		conditions = append(conditions, "scheduled_for >= @filter_scheduled_for_after")
		data["filter_scheduled_for_after"] = *filter.ScheduledForAfter
	}
	if filter.ScheduledForBefore != nil {
		conditions = append(conditions, "scheduled_for <= @filter_scheduled_for_before")
		data["filter_scheduled_for_before"] = *filter.ScheduledForBefore
	}
	if filter.CreatedAt != nil {
		conditions = append(conditions, "created_at = @filter_created_at")
		data["filter_created_at"] = *filter.CreatedAt
	}
	if filter.CreatedAtAfter != nil {
		conditions = append(conditions, "created_at >= @filter_created_at_after")
		data["filter_created_at_after"] = *filter.CreatedAtAfter
	}
	if filter.CreatedAtBefore != nil {
		conditions = append(conditions, "created_at <= @filter_created_at_before")
		data["filter_created_at_before"] = *filter.CreatedAtBefore
	}
	if filter.UpdatedAt != nil {
		conditions = append(conditions, "updated_at = @filter_updated_at")
		data["filter_updated_at"] = *filter.UpdatedAt
	}
	if filter.UpdatedAtAfter != nil {
		conditions = append(conditions, "updated_at >= @filter_updated_at_after")
		data["filter_updated_at_after"] = *filter.UpdatedAtAfter
	}
	if filter.UpdatedAtBefore != nil {
		conditions = append(conditions, "updated_at <= @filter_updated_at_before")
		data["filter_updated_at_before"] = *filter.UpdatedAtBefore
	}
	if filter.StagedAt != nil {
		conditions = append(conditions, "staged_at = @filter_staged_at")
		data["filter_staged_at"] = *filter.StagedAt
	}
	if filter.StagedAtAfter != nil {
		conditions = append(conditions, "staged_at >= @filter_staged_at_after")
		data["filter_staged_at_after"] = *filter.StagedAtAfter
	}
	if filter.StagedAtBefore != nil {
		conditions = append(conditions, "staged_at <= @filter_staged_at_before")
		data["filter_staged_at_before"] = *filter.StagedAtBefore
	}
	if filter.CompletedAt != nil {
		conditions = append(conditions, "completed_at = @filter_completed_at")
		data["filter_completed_at"] = *filter.CompletedAt
	}
	if filter.CompletedAtAfter != nil {
		conditions = append(conditions, "completed_at >= @filter_completed_at_after")
		data["filter_completed_at_after"] = *filter.CompletedAtAfter
	}
	if filter.CompletedAtBefore != nil {
		conditions = append(conditions, "completed_at <= @filter_completed_at_before")
		data["filter_completed_at_before"] = *filter.CompletedAtBefore
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "job_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

func generatedApplyListSearchFilter(filter jobqueue.FilterList, data pgx.NamedArgs) string {
	if filter.SearchTerm == nil || *filter.SearchTerm == "" {
		return "TRUE"
	}
	// ILIKE pattern search.
	searchPattern := "%" + *filter.SearchTerm + "%"
	data["search_term"] = searchPattern
	var searchConditions []string
	searchConditions = append(searchConditions, "event_type ILIKE @search_term")
	searchConditions = append(searchConditions, "correlation_id ILIKE @search_term")
	searchConditions = append(searchConditions, "tenant_id ILIKE @search_term")
	searchConditions = append(searchConditions, "aggregate_type ILIKE @search_term")
	searchConditions = append(searchConditions, "aggregate_id ILIKE @search_term")
	searchConditions = append(searchConditions, "status ILIKE @search_term")
	searchConditions = append(searchConditions, "worker_name ILIKE @search_term")
	searchConditions = append(searchConditions, "failure_reason ILIKE @search_term")
	if len(searchConditions) == 0 {
		return "TRUE"
	}
	return strings.Join(searchConditions, " OR ")
}

// Ensure imports are used.
var _ = errors.New
var _ = fmt.Sprintf
var _ slog.Logger
var _ pgxdb.Querier
var _ fop.Order
