// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.

package userpasswordspgx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
	"github.com/gopernicus/gopernicus/sdk/fop"

	"github.com/gopernicus/gopernicus/core/repositories/auth/userpasswords"
)

// Store implements userpasswords.Storer using PostgreSQL via pgx.
type Store struct {
	log *slog.Logger
	db  pgxdb.Querier
}

// NewStore creates a new userpasswords store backed by the given Querier.
// Querier is satisfied by both *pgxpool.Pool and pgx.Tx, enabling
// transaction composition.
func NewStore(log *slog.Logger, db pgxdb.Querier) *Store {
	return &Store{log: log, db: db}
}

// compile-time interface check (Storer is defined in repository.go)
var _ userpasswords.Storer = (*Store)(nil)

// ─── error mapping ────────────────────────────────────────────────────────────

func (s *Store) mapError(err error) error {
	dbErr := pgxdb.HandlePgError(err)
	switch {
	case errors.Is(dbErr, pgxdb.ErrDBDuplicatedEntry):
		return userpasswords.ErrUserPasswordAlreadyExists
	case errors.Is(dbErr, pgxdb.ErrDBForeignKeyViolation):
		return userpasswords.ErrUserPasswordInvalidReference
	case errors.Is(dbErr, pgxdb.ErrDBCheckViolation),
		errors.Is(dbErr, pgxdb.ErrDBNotNullViolation):
		return userpasswords.ErrUserPasswordInvalidInput
	default:
		return dbErr
	}
}

// ─── methods ──────────────────────────────────────────────────────────────────

func (s *Store) List(ctx context.Context, filter userpasswords.FilterList, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]userpasswords.UserPassword, error) {
	data := pgx.NamedArgs{}

	baseSQL := `SELECT *
FROM public.user_passwords
WHERE $conditions`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListConditionsFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := userpasswords.OrderByFields[orderBy.Field]
	if !ok {
		of = userpasswords.OrderByFields[userpasswords.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "user_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "user_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[userpasswords.UserPassword])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) Get(ctx context.Context, userID string) (userpasswords.UserPassword, error) {
	query := `SELECT user_id, password_hash, password_changed_at, password_verified, created_at, updated_at
FROM public.user_passwords
WHERE user_id = @user_id`

	args := pgx.NamedArgs{
		"user_id": userID,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return userpasswords.UserPassword{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[userpasswords.UserPassword])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return userpasswords.UserPassword{}, userpasswords.ErrUserPasswordNotFound
		}
		return userpasswords.UserPassword{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) Create(ctx context.Context, input userpasswords.CreateUserPassword) (userpasswords.UserPassword, error) {
	now := time.Now().UTC()
	query := `INSERT INTO public.user_passwords (user_id, password_hash, password_changed_at, password_verified, created_at, updated_at)
		VALUES (@user_id, @password_hash, @password_changed_at, @password_verified, @_created_at, @_updated_at)
		RETURNING user_id, password_hash, password_changed_at, password_verified, created_at, updated_at`

	args := pgx.NamedArgs{
		"user_id":             input.UserID,
		"password_hash":       input.PasswordHash,
		"password_changed_at": input.PasswordChangedAt,
		"password_verified":   input.PasswordVerified,
		"_created_at":         now,
		"_updated_at":         now,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return userpasswords.UserPassword{}, s.mapError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[userpasswords.UserPassword])
	if err != nil {
		return userpasswords.UserPassword{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Update(ctx context.Context, userID string, input userpasswords.UpdateUserPassword) (userpasswords.UserPassword, error) {
	buf := bytes.NewBufferString("UPDATE public.user_passwords SET ")
	args := pgx.NamedArgs{
		"user_id": userID,
	}
	var setClauses []string
	if input.PasswordHash != nil {
		setClauses = append(setClauses, "password_hash = @password_hash")
		args["password_hash"] = *input.PasswordHash
	}
	if input.PasswordChangedAt != nil {
		setClauses = append(setClauses, "password_changed_at = @password_changed_at")
		args["password_changed_at"] = *input.PasswordChangedAt
	}
	if input.PasswordVerified != nil {
		setClauses = append(setClauses, "password_verified = @password_verified")
		args["password_verified"] = *input.PasswordVerified
	}
	if input.UpdatedAt != nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = *input.UpdatedAt
	}

	// Auto-set updated_at if not explicitly provided.
	if input.UpdatedAt == nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = time.Now().UTC()
	}

	if len(setClauses) == 0 {
		return userpasswords.UserPassword{}, fmt.Errorf("no fields to update")
	}

	buf.WriteString(strings.Join(setClauses, ", "))
	buf.WriteString(" WHERE user_id = @user_id")
	buf.WriteString(" RETURNING user_id, password_hash, password_changed_at, password_verified, created_at, updated_at")

	rows, err := s.db.Query(ctx, buf.String(), args)
	if err != nil {
		return userpasswords.UserPassword{}, s.mapError(err)
	}
	defer rows.Close()
	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[userpasswords.UserPassword])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return userpasswords.UserPassword{}, userpasswords.ErrUserPasswordNotFound
		}
		return userpasswords.UserPassword{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Delete(ctx context.Context, userID string) error {
	args := pgx.NamedArgs{
		"user_id": userID,
	}

	query := `DELETE FROM public.user_passwords
WHERE user_id = @user_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return userpasswords.ErrUserPasswordNotFound
	}

	return nil
}

func (s *Store) SetVerified(ctx context.Context, updatedAt time.Time, userID string) error {
	args := pgx.NamedArgs{
		"updated_at": updatedAt,
		"user_id":    userID,
	}

	query := `UPDATE public.user_passwords
SET password_verified = true, updated_at = @updated_at
WHERE user_id = @user_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return userpasswords.ErrUserPasswordNotFound
	}

	return nil
}

// ─── filter placeholder substitution ─────────────────────────────────────────

func replaceFilterPlaceholder(sql, placeholder, fragment string) string {
	if fragment == "" {
		fragment = "TRUE"
	}
	return strings.Replace(sql, placeholder, "("+fragment+")", 1)
}

// ─── per-function named filters ──────────────────────────────────────────────

func generatedApplyListConditionsFilter(filter userpasswords.FilterList, data pgx.NamedArgs) string {
	var conditions []string
	if filter.UserID != nil {
		conditions = append(conditions, "user_id = @filter_user_id")
		data["filter_user_id"] = *filter.UserID
	}
	if filter.PasswordHash != nil {
		conditions = append(conditions, "password_hash = @filter_password_hash")
		data["filter_password_hash"] = *filter.PasswordHash
	}
	if filter.PasswordChangedAt != nil {
		conditions = append(conditions, "password_changed_at = @filter_password_changed_at")
		data["filter_password_changed_at"] = *filter.PasswordChangedAt
	}
	if filter.PasswordChangedAtAfter != nil {
		conditions = append(conditions, "password_changed_at >= @filter_password_changed_at_after")
		data["filter_password_changed_at_after"] = *filter.PasswordChangedAtAfter
	}
	if filter.PasswordChangedAtBefore != nil {
		conditions = append(conditions, "password_changed_at <= @filter_password_changed_at_before")
		data["filter_password_changed_at_before"] = *filter.PasswordChangedAtBefore
	}
	if filter.PasswordVerified != nil {
		conditions = append(conditions, "password_verified = @filter_password_verified")
		data["filter_password_verified"] = *filter.PasswordVerified
	}
	if filter.CreatedAt != nil {
		conditions = append(conditions, "created_at = @filter_created_at")
		data["filter_created_at"] = *filter.CreatedAt
	}
	if filter.CreatedAtAfter != nil {
		conditions = append(conditions, "created_at >= @filter_created_at_after")
		data["filter_created_at_after"] = *filter.CreatedAtAfter
	}
	if filter.CreatedAtBefore != nil {
		conditions = append(conditions, "created_at <= @filter_created_at_before")
		data["filter_created_at_before"] = *filter.CreatedAtBefore
	}
	if filter.UpdatedAt != nil {
		conditions = append(conditions, "updated_at = @filter_updated_at")
		data["filter_updated_at"] = *filter.UpdatedAt
	}
	if filter.UpdatedAtAfter != nil {
		conditions = append(conditions, "updated_at >= @filter_updated_at_after")
		data["filter_updated_at_after"] = *filter.UpdatedAtAfter
	}
	if filter.UpdatedAtBefore != nil {
		conditions = append(conditions, "updated_at <= @filter_updated_at_before")
		data["filter_updated_at_before"] = *filter.UpdatedAtBefore
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "user_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

// Ensure imports are used.
var _ = errors.New
var _ = fmt.Sprintf
var _ slog.Logger
var _ pgxdb.Querier
var _ fop.Order
