// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.
//
// Unit tests for the generated request-model Validate methods: each negative
// case mutates exactly one field on a known-valid baseline. Pure Go — no
// build tag, no infrastructure.

package rebacrelationshipmetadatabridge

import (
	"testing"
)

func validCreateRebacRelationshipMetadataRequest() CreateRebacRelationshipMetadataRequest {
	return CreateRebacRelationshipMetadataRequest{}
}

func TestCreateRebacRelationshipMetadataRequestValidate(t *testing.T) {
	t.Run("valid request passes", func(t *testing.T) {
		r := validCreateRebacRelationshipMetadataRequest()
		if err := r.Validate(); err != nil {
			t.Fatalf("valid request: unexpected error: %v", err)
		}
	})
}

func TestUpdateRebacRelationshipMetadataRequestValidate(t *testing.T) {
	t.Run("empty update passes", func(t *testing.T) {
		r := UpdateRebacRelationshipMetadataRequest{}
		if err := r.Validate(); err != nil {
			t.Fatalf("empty update: unexpected error: %v", err)
		}
	})
}
