// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.
//
// Unit tests for the generated request-model Validate methods: each negative
// case mutates exactly one field on a known-valid baseline. Pure Go — no
// build tag, no infrastructure.

package groupsbridge

import (
	"strings"
	"testing"
)

func testPtr[T any](v T) *T { return &v }

func validCreateGroupRequest() CreateGroupRequest {
	return CreateGroupRequest{
		Name: "ok",
		Slug: "valid-slug",
	}
}

func TestCreateGroupRequestValidate(t *testing.T) {
	t.Run("valid request passes", func(t *testing.T) {
		r := validCreateGroupRequest()
		if err := r.Validate(); err != nil {
			t.Fatalf("valid request: unexpected error: %v", err)
		}
	})
	t.Run("missing required name", func(t *testing.T) {
		r := validCreateGroupRequest()
		r.Name = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("name rejects value over max length", func(t *testing.T) {
		r := validCreateGroupRequest()
		r.Name = strings.Repeat("a", 256)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("missing required slug", func(t *testing.T) {
		r := validCreateGroupRequest()
		r.Slug = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("slug rejects malformed slug", func(t *testing.T) {
		r := validCreateGroupRequest()
		r.Slug = "Not A Slug!"
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("slug rejects value over max length", func(t *testing.T) {
		r := validCreateGroupRequest()
		r.Slug = strings.Repeat("a", 256)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
}

func TestUpdateGroupRequestValidate(t *testing.T) {
	t.Run("empty update passes", func(t *testing.T) {
		r := UpdateGroupRequest{}
		if err := r.Validate(); err != nil {
			t.Fatalf("empty update: unexpected error: %v", err)
		}
	})
	t.Run("update name rejects value over max length", func(t *testing.T) {
		r := UpdateGroupRequest{}
		r.Name = testPtr(strings.Repeat("a", 256))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update slug rejects malformed slug", func(t *testing.T) {
		r := UpdateGroupRequest{}
		r.Slug = testPtr("Not A Slug!")
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update slug rejects value over max length", func(t *testing.T) {
		r := UpdateGroupRequest{}
		r.Slug = testPtr(strings.Repeat("a", 256))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
}
