package generators

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// satisfierGeneratedHeader marks emitted satisfier files as generated. Only
// files carrying this header (or absent files) are (re)written by
// emitSatisfiers; anything else is treated as hand-written and skipped.
const satisfierGeneratedHeader = "// Code generated by gopernicus. DO NOT EDIT.\n" +
	"// Feature satisfier emitted from the gopernicus framework sources.\n\n"

// Feature → satisfier mapping. Satisfiers adapt the PROJECT's generated
// repositories to the framework's feature engines, so they must live in the
// project (they reference project repo types); the engines and their bridges
// are imported from the framework. The invitations engine rides with the
// authorization feature, mirroring how init has always grouped invitations
// assets under authorization.
var (
	authenticationSatisfierPaths = []string{
		"core/auth/authentication/satisfiers/api_keys.go",
		"core/auth/authentication/satisfiers/oauth_accounts.go",
		"core/auth/authentication/satisfiers/passwords.go",
		"core/auth/authentication/satisfiers/security_events.go",
		"core/auth/authentication/satisfiers/service_account_principals.go",
		"core/auth/authentication/satisfiers/sessions.go",
		"core/auth/authentication/satisfiers/users.go",
		"core/auth/authentication/satisfiers/verification_codes.go",
		"core/auth/authentication/satisfiers/verification_tokens.go",
	}
	authorizationSatisfierPaths = []string{
		"core/auth/authorization/satisfiers/authorization_store.go",
	}
	invitationsSatisfierPaths = []string{
		"core/auth/invitations/satisfiers/invitations.go",
	}
)

// emitSatisfiers writes the feature satisfier packages into the project for
// every enabled feature. Emission is deterministic (fixed path order, fixed
// sources) and idempotent: a regenerate rewrites the same bytes.
//
// Compat: a pre-existing file WITHOUT the generated header is a copied (and
// possibly user-edited) satisfier from a pre-tool-directive project — it is
// left untouched and noted, never overwritten.
func emitSatisfiers(cfg Config, modulePath string, opts Options) error {
	features := cfg.Manifest.Features

	var paths []string
	if features.AuthenticationEnabled() {
		paths = append(paths, authenticationSatisfierPaths...)
	}
	if features.AuthorizationEnabled() {
		paths = append(paths, authorizationSatisfierPaths...)
		paths = append(paths, invitationsSatisfierPaths...)
	}
	if len(paths) == 0 {
		return nil
	}

	fmt.Printf("\n  satisfiers (feature engine adapters)\n")
	for _, rel := range paths {
		source, ok := satisfierSources[rel]
		if !ok {
			// The mapping and the snapshot live side by side; a miss is a
			// gopernicus bug, not a user configuration problem.
			return fmt.Errorf("satisfiers: no source registered for %s (gopernicus bug — please report)", rel)
		}

		path := filepath.Join(cfg.ProjectRoot, filepath.FromSlash(rel))
		handWritten, err := existsWithoutGeneratedHeader(path)
		if err != nil {
			return fmt.Errorf("satisfiers: inspect %s: %w", rel, err)
		}
		if handWritten {
			fmt.Printf("    skip %s (existing file without generated header — left untouched)\n", rel)
			continue
		}

		out := satisfierGeneratedHeader + rewriteSatisfierImports(source, modulePath)
		if err := renderGoFile(rel, []byte(out), path, opts); err != nil {
			return err
		}
		if opts.Verbose {
			fmt.Printf("    wrote %s\n", rel)
		}
	}
	return nil
}

// rewriteSatisfierImports points the framework satisfier source at the
// project's generated repositories. Engine, sdk, and infrastructure imports
// stay on framework paths — only core/repositories moves to the project.
func rewriteSatisfierImports(source, modulePath string) string {
	return strings.ReplaceAll(source,
		`"`+FrameworkModulePath+`/core/repositories/`,
		`"`+modulePath+`/core/repositories/`,
	)
}

// existsWithoutGeneratedHeader reports whether path exists and lacks the
// generated-code header (i.e. is hand-written and must not be overwritten).
func existsWithoutGeneratedHeader(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return !strings.Contains(string(data), "Code generated by gopernicus. DO NOT EDIT."), nil
}
