// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package eventsreposbridge

import (
	"github.com/gopernicus/gopernicus/core/auth/authorization"
)

// GeneratedAuthSchema returns the generated authorization schema for the eventsreposbridge domain.
// Use AuthSchema() from authschema.go to customize.
func GeneratedAuthSchema() []authorization.ResourceSchema {
	return []authorization.ResourceSchema{
		{
			Name: "event_outbox",
			Def: authorization.ResourceTypeDef{
				Relations: map[string]authorization.RelationDef{
					"owner": {AllowedSubjects: []authorization.SubjectTypeRef{
						{Type: "user"},
						{Type: "service_account"},
					}},
				},
				Permissions: map[string]authorization.PermissionRule{
					"list": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"create": authorization.AnyOf(
						authorization.Direct("authenticated"),
					),
					"read": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"update": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"delete": authorization.AnyOf(
						authorization.Direct("owner"),
					),
					"manage": authorization.AnyOf(
						authorization.Direct("owner"),
					),
				},
			},
		},
	}
}
