// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.
//
// Unit tests for the generated request-model Validate methods: each negative
// case mutates exactly one field on a known-valid baseline. Pure Go — no
// build tag, no infrastructure.

package oauthaccountsbridge

import (
	"strings"
	"testing"
)

func testPtr[T any](v T) *T { return &v }

func validCreateOauthAccountRequest() CreateOauthAccountRequest {
	return CreateOauthAccountRequest{
		Provider:       "ok",
		ProviderUserID: "ok",
	}
}

func TestCreateOauthAccountRequestValidate(t *testing.T) {
	t.Run("valid request passes", func(t *testing.T) {
		r := validCreateOauthAccountRequest()
		if err := r.Validate(); err != nil {
			t.Fatalf("valid request: unexpected error: %v", err)
		}
	})
	t.Run("missing required provider", func(t *testing.T) {
		r := validCreateOauthAccountRequest()
		r.Provider = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("provider rejects value over max length", func(t *testing.T) {
		r := validCreateOauthAccountRequest()
		r.Provider = strings.Repeat("a", 51)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("missing required provider_user_id", func(t *testing.T) {
		r := validCreateOauthAccountRequest()
		r.ProviderUserID = ""
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("provider_user_id rejects value over max length", func(t *testing.T) {
		r := validCreateOauthAccountRequest()
		r.ProviderUserID = strings.Repeat("a", 256)
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("provider_email rejects malformed email", func(t *testing.T) {
		r := validCreateOauthAccountRequest()
		r.ProviderEmail = testPtr("not-an-email")
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("provider_email rejects value over max length", func(t *testing.T) {
		r := validCreateOauthAccountRequest()
		r.ProviderEmail = testPtr(strings.Repeat("a", 256))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("token_type rejects value over max length", func(t *testing.T) {
		r := validCreateOauthAccountRequest()
		r.TokenType = testPtr(strings.Repeat("a", 51))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
}

func TestUpdateOauthAccountRequestValidate(t *testing.T) {
	t.Run("empty update passes", func(t *testing.T) {
		r := UpdateOauthAccountRequest{}
		if err := r.Validate(); err != nil {
			t.Fatalf("empty update: unexpected error: %v", err)
		}
	})
	t.Run("update provider rejects value over max length", func(t *testing.T) {
		r := UpdateOauthAccountRequest{}
		r.Provider = testPtr(strings.Repeat("a", 51))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update provider_user_id rejects value over max length", func(t *testing.T) {
		r := UpdateOauthAccountRequest{}
		r.ProviderUserID = testPtr(strings.Repeat("a", 256))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update provider_email rejects malformed email", func(t *testing.T) {
		r := UpdateOauthAccountRequest{}
		r.ProviderEmail = testPtr("not-an-email")
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update provider_email rejects value over max length", func(t *testing.T) {
		r := UpdateOauthAccountRequest{}
		r.ProviderEmail = testPtr(strings.Repeat("a", 256))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
	t.Run("update token_type rejects value over max length", func(t *testing.T) {
		r := UpdateOauthAccountRequest{}
		r.TokenType = testPtr(strings.Repeat("a", 51))
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
}
