// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package rebacreposbridge

import (
	"log/slog"

	"github.com/gopernicus/gopernicus/bridge/repositories/rebacreposbridge/groupsbridge"
	"github.com/gopernicus/gopernicus/bridge/repositories/rebacreposbridge/invitationsbridge"
	"github.com/gopernicus/gopernicus/bridge/repositories/rebacreposbridge/rebacrelationshipmetadatabridge"
	"github.com/gopernicus/gopernicus/bridge/repositories/rebacreposbridge/rebacrelationshipsbridge"

	"github.com/gopernicus/gopernicus/core/auth/authentication"
	"github.com/gopernicus/gopernicus/core/auth/authorization"
	"github.com/gopernicus/gopernicus/core/repositories/rebac"
	"github.com/gopernicus/gopernicus/infrastructure/ratelimiter"
	"github.com/gopernicus/gopernicus/sdk/web"
)

// Bridges contains all bridges for the rebac domain.
type Bridges struct {
	log                       *slog.Logger
	Group                     *groupsbridge.Bridge
	Invitation                *invitationsbridge.Bridge
	RebacRelationship         *rebacrelationshipsbridge.Bridge
	RebacRelationshipMetadata *rebacrelationshipmetadatabridge.Bridge
}

// NewBridges creates all bridges for the rebac domain.
func NewBridges(
	log *slog.Logger,
	repos *rebac.Repositories,
	rateLimiter *ratelimiter.RateLimiter,
	authenticator *authentication.Authenticator,
	authorizer *authorization.Authorizer,
) *Bridges {
	return &Bridges{
		log:                       log,
		Group:                     groupsbridge.NewBridge(log, repos.Group, rateLimiter, authenticator, authorizer),
		Invitation:                invitationsbridge.NewBridge(log, repos.Invitation, rateLimiter, authenticator, authorizer),
		RebacRelationship:         rebacrelationshipsbridge.NewBridge(log, repos.RebacRelationship, rateLimiter, authenticator, authorizer),
		RebacRelationshipMetadata: rebacrelationshipmetadatabridge.NewBridge(log, repos.RebacRelationshipMetadata, rateLimiter, authenticator, authorizer),
	}
}

// AddHttpRoutes registers all HTTP routes for the rebac domain.
func (b *Bridges) AddHttpRoutes(group *web.RouteGroup) {
	b.Group.AddHttpRoutes(group)
	b.Invitation.AddHttpRoutes(group)
	b.RebacRelationship.AddHttpRoutes(group)
	b.RebacRelationshipMetadata.AddHttpRoutes(group)
}

// OpenAPISpec returns aggregated OpenAPI route specs for all rebac bridges.
func (b *Bridges) OpenAPISpec() []web.RouteSpec {
	var specs []web.RouteSpec
	specs = append(specs, b.Group.OpenAPISpec()...)
	specs = append(specs, b.Invitation.OpenAPISpec()...)
	specs = append(specs, b.RebacRelationship.OpenAPISpec()...)
	specs = append(specs, b.RebacRelationshipMetadata.OpenAPISpec()...)
	return specs
}

// AuthSchema returns the authorization schema for the rebac domain.
// Delegates to the customizable AuthSchema() function in authschema.go.
func (b *Bridges) AuthSchema() []authorization.ResourceSchema {
	return AuthSchema()
}
