// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.

package apikeyspgx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
	"github.com/gopernicus/gopernicus/sdk/fop"

	"github.com/gopernicus/gopernicus/core/repositories/auth/apikeys"
)

// Store implements apikeys.Storer using PostgreSQL via pgx.
type Store struct {
	log *slog.Logger
	db  pgxdb.Querier
}

// NewStore creates a new apikeys store backed by the given Querier.
// Querier is satisfied by both *pgxpool.Pool and pgx.Tx, enabling
// transaction composition.
func NewStore(log *slog.Logger, db pgxdb.Querier) *Store {
	return &Store{log: log, db: db}
}

// compile-time interface check (Storer is defined in repository.go)
var _ apikeys.Storer = (*Store)(nil)

// ─── error mapping ────────────────────────────────────────────────────────────

func (s *Store) mapError(err error) error {
	dbErr := pgxdb.HandlePgError(err)
	switch {
	case errors.Is(dbErr, pgxdb.ErrDBDuplicatedEntry):
		return apikeys.ErrAPIKeyAlreadyExists
	case errors.Is(dbErr, pgxdb.ErrDBForeignKeyViolation):
		return apikeys.ErrAPIKeyInvalidReference
	case errors.Is(dbErr, pgxdb.ErrDBCheckViolation),
		errors.Is(dbErr, pgxdb.ErrDBNotNullViolation):
		return apikeys.ErrAPIKeyInvalidInput
	default:
		return dbErr
	}
}

// ─── methods ──────────────────────────────────────────────────────────────────

func (s *Store) List(ctx context.Context, filter apikeys.FilterList, parentServiceAccountID string, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]apikeys.APIKey, error) {
	data := pgx.NamedArgs{
		"parent_service_account_id": parentServiceAccountID,
	}

	baseSQL := `SELECT *
FROM public.api_keys
WHERE parent_service_account_id = @parent_service_account_id AND $conditions AND $search`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListConditionsFilter(filter, data))
	baseSQL = replaceFilterPlaceholder(baseSQL, "$search", generatedApplyListSearchFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := apikeys.OrderByFields[orderBy.Field]
	if !ok {
		of = apikeys.OrderByFields[apikeys.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "api_key_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "api_key_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[apikeys.APIKey])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) Get(ctx context.Context, apiKeyID string, parentServiceAccountID string) (apikeys.APIKey, error) {
	query := `SELECT api_key_id, parent_service_account_id, name, key_prefix, key_hash, expires_at, last_used_at, last_used_ip, rate_limit_per_minute, record_state, revoked_at, created_at, updated_at
FROM public.api_keys
WHERE api_key_id = @api_key_id AND parent_service_account_id = @parent_service_account_id`

	args := pgx.NamedArgs{
		"api_key_id":                apiKeyID,
		"parent_service_account_id": parentServiceAccountID,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return apikeys.APIKey{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[apikeys.APIKey])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return apikeys.APIKey{}, apikeys.ErrAPIKeyNotFound
		}
		return apikeys.APIKey{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) Create(ctx context.Context, input apikeys.CreateAPIKey) (apikeys.APIKey, error) {
	now := time.Now().UTC()
	query := `INSERT INTO public.api_keys (api_key_id, parent_service_account_id, name, key_prefix, key_hash, expires_at, last_used_at, last_used_ip, rate_limit_per_minute, record_state, revoked_at, created_at, updated_at)
		VALUES (@api_key_id, @parent_service_account_id, @name, @key_prefix, @key_hash, @expires_at, @last_used_at, @last_used_ip, @rate_limit_per_minute, @record_state, @revoked_at, @_created_at, @_updated_at)
		RETURNING api_key_id, parent_service_account_id, name, key_prefix, key_hash, expires_at, last_used_at, last_used_ip, rate_limit_per_minute, record_state, revoked_at, created_at, updated_at`

	args := pgx.NamedArgs{
		"api_key_id":                input.APIKeyID,
		"parent_service_account_id": input.ParentServiceAccountID,
		"name":                      input.Name,
		"key_prefix":                input.KeyPrefix,
		"key_hash":                  input.KeyHash,
		"expires_at":                input.ExpiresAt,
		"last_used_at":              input.LastUsedAt,
		"last_used_ip":              input.LastUsedIp,
		"rate_limit_per_minute":     input.RateLimitPerMinute,
		"record_state":              input.RecordState,
		"revoked_at":                input.RevokedAt,
		"_created_at":               now,
		"_updated_at":               now,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return apikeys.APIKey{}, s.mapError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[apikeys.APIKey])
	if err != nil {
		return apikeys.APIKey{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Update(ctx context.Context, apiKeyID string, parentServiceAccountID string, input apikeys.UpdateAPIKey) (apikeys.APIKey, error) {
	buf := bytes.NewBufferString("UPDATE public.api_keys SET ")
	args := pgx.NamedArgs{
		"api_key_id": apiKeyID,
	}
	var setClauses []string
	if input.Name != nil {
		setClauses = append(setClauses, "name = @name")
		args["name"] = *input.Name
	}
	if input.KeyPrefix != nil {
		setClauses = append(setClauses, "key_prefix = @key_prefix")
		args["key_prefix"] = *input.KeyPrefix
	}
	if input.KeyHash != nil {
		setClauses = append(setClauses, "key_hash = @key_hash")
		args["key_hash"] = *input.KeyHash
	}
	if input.ExpiresAt != nil {
		setClauses = append(setClauses, "expires_at = @expires_at")
		args["expires_at"] = *input.ExpiresAt
	}
	if input.LastUsedAt != nil {
		setClauses = append(setClauses, "last_used_at = @last_used_at")
		args["last_used_at"] = *input.LastUsedAt
	}
	if input.LastUsedIp != nil {
		setClauses = append(setClauses, "last_used_ip = @last_used_ip")
		args["last_used_ip"] = *input.LastUsedIp
	}
	if input.RateLimitPerMinute != nil {
		setClauses = append(setClauses, "rate_limit_per_minute = @rate_limit_per_minute")
		args["rate_limit_per_minute"] = *input.RateLimitPerMinute
	}
	if input.RevokedAt != nil {
		setClauses = append(setClauses, "revoked_at = @revoked_at")
		args["revoked_at"] = *input.RevokedAt
	}
	if input.UpdatedAt != nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = *input.UpdatedAt
	}

	// Auto-set updated_at if not explicitly provided.
	if input.UpdatedAt == nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = time.Now().UTC()
	}

	if len(setClauses) == 0 {
		return apikeys.APIKey{}, fmt.Errorf("no fields to update")
	}

	buf.WriteString(strings.Join(setClauses, ", "))
	buf.WriteString(" WHERE api_key_id = @api_key_id")
	buf.WriteString(" RETURNING api_key_id, parent_service_account_id, name, key_prefix, key_hash, expires_at, last_used_at, last_used_ip, rate_limit_per_minute, record_state, revoked_at, created_at, updated_at")

	rows, err := s.db.Query(ctx, buf.String(), args)
	if err != nil {
		return apikeys.APIKey{}, s.mapError(err)
	}
	defer rows.Close()
	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[apikeys.APIKey])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return apikeys.APIKey{}, apikeys.ErrAPIKeyNotFound
		}
		return apikeys.APIKey{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) SoftDelete(ctx context.Context, apiKeyID string, parentServiceAccountID string) error {
	args := pgx.NamedArgs{
		"api_key_id":                apiKeyID,
		"parent_service_account_id": parentServiceAccountID,
	}

	query := `UPDATE public.api_keys
SET record_state = 'deleted'
WHERE api_key_id = @api_key_id AND parent_service_account_id = @parent_service_account_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return apikeys.ErrAPIKeyNotFound
	}

	return nil
}

func (s *Store) Archive(ctx context.Context, apiKeyID string, parentServiceAccountID string) error {
	args := pgx.NamedArgs{
		"api_key_id":                apiKeyID,
		"parent_service_account_id": parentServiceAccountID,
	}

	query := `UPDATE public.api_keys
SET record_state = 'archived'
WHERE api_key_id = @api_key_id AND parent_service_account_id = @parent_service_account_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return apikeys.ErrAPIKeyNotFound
	}

	return nil
}

func (s *Store) Restore(ctx context.Context, apiKeyID string, parentServiceAccountID string) error {
	args := pgx.NamedArgs{
		"api_key_id":                apiKeyID,
		"parent_service_account_id": parentServiceAccountID,
	}

	query := `UPDATE public.api_keys
SET record_state = 'active'
WHERE api_key_id = @api_key_id AND parent_service_account_id = @parent_service_account_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return apikeys.ErrAPIKeyNotFound
	}

	return nil
}

func (s *Store) Delete(ctx context.Context, apiKeyID string, parentServiceAccountID string) error {
	args := pgx.NamedArgs{
		"api_key_id":                apiKeyID,
		"parent_service_account_id": parentServiceAccountID,
	}

	query := `DELETE FROM public.api_keys
WHERE api_key_id = @api_key_id AND parent_service_account_id = @parent_service_account_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return apikeys.ErrAPIKeyNotFound
	}

	return nil
}

// ─── filter placeholder substitution ─────────────────────────────────────────

func replaceFilterPlaceholder(sql, placeholder, fragment string) string {
	if fragment == "" {
		fragment = "TRUE"
	}
	return strings.Replace(sql, placeholder, "("+fragment+")", 1)
}

// ─── per-function named filters ──────────────────────────────────────────────

func generatedApplyListConditionsFilter(filter apikeys.FilterList, data pgx.NamedArgs) string {
	var conditions []string

	// Auto-default record_state to 'active'.
	if filter.RecordState == nil {
		conditions = append(conditions, "record_state = @record_state")
		data["record_state"] = "active"
	} else if strings.Contains(*filter.RecordState, ",") {
		states := strings.Split(*filter.RecordState, ",")
		for i := range states {
			states[i] = strings.TrimSpace(states[i])
		}
		conditions = append(conditions, "record_state = ANY(@record_states)")
		data["record_states"] = states
	} else {
		conditions = append(conditions, "record_state = @record_state")
		data["record_state"] = *filter.RecordState
	}
	if filter.APIKeyID != nil {
		conditions = append(conditions, "api_key_id = @filter_api_key_id")
		data["filter_api_key_id"] = *filter.APIKeyID
	}
	if filter.ParentServiceAccountID != nil {
		conditions = append(conditions, "parent_service_account_id = @filter_parent_service_account_id")
		data["filter_parent_service_account_id"] = *filter.ParentServiceAccountID
	}
	if filter.Name != nil {
		conditions = append(conditions, "name = @filter_name")
		data["filter_name"] = *filter.Name
	}
	if filter.KeyPrefix != nil {
		conditions = append(conditions, "key_prefix = @filter_key_prefix")
		data["filter_key_prefix"] = *filter.KeyPrefix
	}
	if filter.KeyHash != nil {
		conditions = append(conditions, "key_hash = @filter_key_hash")
		data["filter_key_hash"] = *filter.KeyHash
	}
	if filter.ExpiresAt != nil {
		conditions = append(conditions, "expires_at = @filter_expires_at")
		data["filter_expires_at"] = *filter.ExpiresAt
	}
	if filter.ExpiresAtAfter != nil {
		conditions = append(conditions, "expires_at >= @filter_expires_at_after")
		data["filter_expires_at_after"] = *filter.ExpiresAtAfter
	}
	if filter.ExpiresAtBefore != nil {
		conditions = append(conditions, "expires_at <= @filter_expires_at_before")
		data["filter_expires_at_before"] = *filter.ExpiresAtBefore
	}
	if filter.LastUsedAt != nil {
		conditions = append(conditions, "last_used_at = @filter_last_used_at")
		data["filter_last_used_at"] = *filter.LastUsedAt
	}
	if filter.LastUsedAtAfter != nil {
		conditions = append(conditions, "last_used_at >= @filter_last_used_at_after")
		data["filter_last_used_at_after"] = *filter.LastUsedAtAfter
	}
	if filter.LastUsedAtBefore != nil {
		conditions = append(conditions, "last_used_at <= @filter_last_used_at_before")
		data["filter_last_used_at_before"] = *filter.LastUsedAtBefore
	}
	if filter.LastUsedIp != nil {
		conditions = append(conditions, "last_used_ip = @filter_last_used_ip")
		data["filter_last_used_ip"] = *filter.LastUsedIp
	}
	if filter.RateLimitPerMinute != nil {
		conditions = append(conditions, "rate_limit_per_minute = @filter_rate_limit_per_minute")
		data["filter_rate_limit_per_minute"] = *filter.RateLimitPerMinute
	}
	if filter.RevokedAt != nil {
		conditions = append(conditions, "revoked_at = @filter_revoked_at")
		data["filter_revoked_at"] = *filter.RevokedAt
	}
	if filter.RevokedAtAfter != nil {
		conditions = append(conditions, "revoked_at >= @filter_revoked_at_after")
		data["filter_revoked_at_after"] = *filter.RevokedAtAfter
	}
	if filter.RevokedAtBefore != nil {
		conditions = append(conditions, "revoked_at <= @filter_revoked_at_before")
		data["filter_revoked_at_before"] = *filter.RevokedAtBefore
	}
	if filter.CreatedAt != nil {
		conditions = append(conditions, "created_at = @filter_created_at")
		data["filter_created_at"] = *filter.CreatedAt
	}
	if filter.CreatedAtAfter != nil {
		conditions = append(conditions, "created_at >= @filter_created_at_after")
		data["filter_created_at_after"] = *filter.CreatedAtAfter
	}
	if filter.CreatedAtBefore != nil {
		conditions = append(conditions, "created_at <= @filter_created_at_before")
		data["filter_created_at_before"] = *filter.CreatedAtBefore
	}
	if filter.UpdatedAt != nil {
		conditions = append(conditions, "updated_at = @filter_updated_at")
		data["filter_updated_at"] = *filter.UpdatedAt
	}
	if filter.UpdatedAtAfter != nil {
		conditions = append(conditions, "updated_at >= @filter_updated_at_after")
		data["filter_updated_at_after"] = *filter.UpdatedAtAfter
	}
	if filter.UpdatedAtBefore != nil {
		conditions = append(conditions, "updated_at <= @filter_updated_at_before")
		data["filter_updated_at_before"] = *filter.UpdatedAtBefore
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "api_key_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

func generatedApplyListSearchFilter(filter apikeys.FilterList, data pgx.NamedArgs) string {
	if filter.SearchTerm == nil || *filter.SearchTerm == "" {
		return "TRUE"
	}
	// ILIKE pattern search.
	searchPattern := "%" + *filter.SearchTerm + "%"
	data["search_term"] = searchPattern
	var searchConditions []string
	searchConditions = append(searchConditions, "name ILIKE @search_term")
	searchConditions = append(searchConditions, "last_used_ip ILIKE @search_term")
	if len(searchConditions) == 0 {
		return "TRUE"
	}
	return strings.Join(searchConditions, " OR ")
}

// Ensure imports are used.
var _ = errors.New
var _ = fmt.Sprintf
var _ slog.Logger
var _ pgxdb.Querier
var _ fop.Order
