// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.

package verificationcodespgx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
	"github.com/gopernicus/gopernicus/sdk/fop"

	"github.com/gopernicus/gopernicus/core/repositories/auth/verificationcodes"
)

// Store implements verificationcodes.Storer using PostgreSQL via pgx.
type Store struct {
	log *slog.Logger
	db  pgxdb.Querier
}

// NewStore creates a new verificationcodes store backed by the given Querier.
// Querier is satisfied by both *pgxpool.Pool and pgx.Tx, enabling
// transaction composition.
func NewStore(log *slog.Logger, db pgxdb.Querier) *Store {
	return &Store{log: log, db: db}
}

// compile-time interface check (Storer is defined in repository.go)
var _ verificationcodes.Storer = (*Store)(nil)

// ─── error mapping ────────────────────────────────────────────────────────────

func (s *Store) mapError(err error) error {
	dbErr := pgxdb.HandlePgError(err)
	switch {
	case errors.Is(dbErr, pgxdb.ErrDBDuplicatedEntry):
		return verificationcodes.ErrVerificationCodeAlreadyExists
	case errors.Is(dbErr, pgxdb.ErrDBForeignKeyViolation):
		return verificationcodes.ErrVerificationCodeInvalidReference
	case errors.Is(dbErr, pgxdb.ErrDBCheckViolation),
		errors.Is(dbErr, pgxdb.ErrDBNotNullViolation):
		return verificationcodes.ErrVerificationCodeInvalidInput
	default:
		return dbErr
	}
}

// ─── methods ──────────────────────────────────────────────────────────────────

func (s *Store) List(ctx context.Context, filter verificationcodes.FilterList, orderBy fop.Order, page fop.PageStringCursor, forPrevious bool) ([]verificationcodes.VerificationCode, error) {
	data := pgx.NamedArgs{}

	baseSQL := `SELECT *
FROM public.verification_codes
WHERE $conditions AND $search`
	baseSQL = replaceFilterPlaceholder(baseSQL, "$conditions", generatedApplyListConditionsFilter(filter, data))
	baseSQL = replaceFilterPlaceholder(baseSQL, "$search", generatedApplyListSearchFilter(filter, data))

	buf := bytes.NewBufferString(baseSQL)

	// Resolve order field.
	of, ok := verificationcodes.OrderByFields[orderBy.Field]
	if !ok {
		of = verificationcodes.OrderByFields[verificationcodes.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "code_id",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "code_id", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[verificationcodes.VerificationCode])
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}

func (s *Store) Get(ctx context.Context, codeID string) (verificationcodes.VerificationCode, error) {
	query := `SELECT code_id, identifier, code_hash, purpose, user_id, data, attempt_count, expires_at, created_at
FROM public.verification_codes
WHERE code_id = @code_id`

	args := pgx.NamedArgs{
		"code_id": codeID,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return verificationcodes.VerificationCode{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[verificationcodes.VerificationCode])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return verificationcodes.VerificationCode{}, verificationcodes.ErrVerificationCodeNotFound
		}
		return verificationcodes.VerificationCode{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) Create(ctx context.Context, input verificationcodes.CreateVerificationCode) (verificationcodes.VerificationCode, error) {
	now := time.Now().UTC()
	query := `INSERT INTO public.verification_codes (code_id, identifier, code_hash, purpose, user_id, data, attempt_count, expires_at, created_at)
		VALUES (@code_id, @identifier, @code_hash, @purpose, @user_id, @data, @attempt_count, @expires_at, @_created_at)
		RETURNING code_id, identifier, code_hash, purpose, user_id, data, attempt_count, expires_at, created_at`

	args := pgx.NamedArgs{
		"code_id":       input.CodeID,
		"identifier":    input.Identifier,
		"code_hash":     input.CodeHash,
		"purpose":       input.Purpose,
		"user_id":       input.UserID,
		"data":          input.Data,
		"attempt_count": input.AttemptCount,
		"expires_at":    input.ExpiresAt,
		"_created_at":   now,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return verificationcodes.VerificationCode{}, s.mapError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[verificationcodes.VerificationCode])
	if err != nil {
		return verificationcodes.VerificationCode{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Update(ctx context.Context, codeID string, input verificationcodes.UpdateVerificationCode) (verificationcodes.VerificationCode, error) {
	buf := bytes.NewBufferString("UPDATE public.verification_codes SET ")
	args := pgx.NamedArgs{
		"code_id": codeID,
	}
	var setClauses []string
	if input.Identifier != nil {
		setClauses = append(setClauses, "identifier = @identifier")
		args["identifier"] = *input.Identifier
	}
	if input.CodeHash != nil {
		setClauses = append(setClauses, "code_hash = @code_hash")
		args["code_hash"] = *input.CodeHash
	}
	if input.Purpose != nil {
		setClauses = append(setClauses, "purpose = @purpose")
		args["purpose"] = *input.Purpose
	}
	if input.UserID != nil {
		setClauses = append(setClauses, "user_id = @user_id")
		args["user_id"] = *input.UserID
	}
	if input.Data != nil {
		setClauses = append(setClauses, "data = @data")
		args["data"] = *input.Data
	}
	if input.AttemptCount != nil {
		setClauses = append(setClauses, "attempt_count = @attempt_count")
		args["attempt_count"] = *input.AttemptCount
	}
	if input.ExpiresAt != nil {
		setClauses = append(setClauses, "expires_at = @expires_at")
		args["expires_at"] = *input.ExpiresAt
	}

	if len(setClauses) == 0 {
		return verificationcodes.VerificationCode{}, fmt.Errorf("no fields to update")
	}

	buf.WriteString(strings.Join(setClauses, ", "))
	buf.WriteString(" WHERE code_id = @code_id")
	buf.WriteString(" RETURNING code_id, identifier, code_hash, purpose, user_id, data, attempt_count, expires_at, created_at")

	rows, err := s.db.Query(ctx, buf.String(), args)
	if err != nil {
		return verificationcodes.VerificationCode{}, s.mapError(err)
	}
	defer rows.Close()
	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[verificationcodes.VerificationCode])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return verificationcodes.VerificationCode{}, verificationcodes.ErrVerificationCodeNotFound
		}
		return verificationcodes.VerificationCode{}, s.mapError(err)
	}

	return record, nil
}

func (s *Store) Delete(ctx context.Context, codeID string) error {
	args := pgx.NamedArgs{
		"code_id": codeID,
	}

	query := `DELETE FROM public.verification_codes
WHERE code_id = @code_id`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return verificationcodes.ErrVerificationCodeNotFound
	}

	return nil
}

func (s *Store) GetByIdentifierAndPurpose(ctx context.Context, identifier string, purpose string, now time.Time) (verificationcodes.VerificationCode, error) {
	query := `SELECT code_id, identifier, code_hash, purpose, user_id, data, attempt_count, expires_at, created_at
FROM public.verification_codes
WHERE identifier = @identifier
AND purpose = @purpose
AND expires_at > @now`

	args := pgx.NamedArgs{
		"identifier": identifier,
		"purpose":    purpose,
		"now":        now,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return verificationcodes.VerificationCode{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[verificationcodes.VerificationCode])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return verificationcodes.VerificationCode{}, verificationcodes.ErrVerificationCodeNotFound
		}
		return verificationcodes.VerificationCode{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) IncrementAttempts(ctx context.Context, identifier string, purpose string) (verificationcodes.IncrementAttemptsResult, error) {
	query := `UPDATE public.verification_codes
SET attempt_count = attempt_count + 1
WHERE identifier = @identifier
AND purpose = @purpose
RETURNING attempt_count`

	args := pgx.NamedArgs{
		"identifier": identifier,
		"purpose":    purpose,
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return verificationcodes.IncrementAttemptsResult{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[verificationcodes.IncrementAttemptsResult])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return verificationcodes.IncrementAttemptsResult{}, verificationcodes.ErrVerificationCodeNotFound
		}
		return verificationcodes.IncrementAttemptsResult{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}

func (s *Store) DeleteByIdentifierAndPurpose(ctx context.Context, identifier string, purpose string) error {
	args := pgx.NamedArgs{
		"identifier": identifier,
		"purpose":    purpose,
	}

	query := `DELETE FROM public.verification_codes
WHERE identifier = @identifier
AND purpose = @purpose`
	result, err := s.db.Exec(ctx, query, args)
	if err != nil {
		return pgxdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return verificationcodes.ErrVerificationCodeNotFound
	}

	return nil
}

// ─── filter placeholder substitution ─────────────────────────────────────────

func replaceFilterPlaceholder(sql, placeholder, fragment string) string {
	if fragment == "" {
		fragment = "TRUE"
	}
	return strings.Replace(sql, placeholder, "("+fragment+")", 1)
}

// ─── per-function named filters ──────────────────────────────────────────────

func generatedApplyListConditionsFilter(filter verificationcodes.FilterList, data pgx.NamedArgs) string {
	var conditions []string
	if filter.CodeID != nil {
		conditions = append(conditions, "code_id = @filter_code_id")
		data["filter_code_id"] = *filter.CodeID
	}
	if filter.Identifier != nil {
		conditions = append(conditions, "identifier = @filter_identifier")
		data["filter_identifier"] = *filter.Identifier
	}
	if filter.CodeHash != nil {
		conditions = append(conditions, "code_hash = @filter_code_hash")
		data["filter_code_hash"] = *filter.CodeHash
	}
	if filter.Purpose != nil {
		conditions = append(conditions, "purpose = @filter_purpose")
		data["filter_purpose"] = *filter.Purpose
	}
	if filter.UserID != nil {
		conditions = append(conditions, "user_id = @filter_user_id")
		data["filter_user_id"] = *filter.UserID
	}
	if filter.Data != nil {
		conditions = append(conditions, "data = @filter_data")
		data["filter_data"] = *filter.Data
	}
	if filter.AttemptCount != nil {
		conditions = append(conditions, "attempt_count = @filter_attempt_count")
		data["filter_attempt_count"] = *filter.AttemptCount
	}
	if filter.ExpiresAt != nil {
		conditions = append(conditions, "expires_at = @filter_expires_at")
		data["filter_expires_at"] = *filter.ExpiresAt
	}
	if filter.ExpiresAtAfter != nil {
		conditions = append(conditions, "expires_at >= @filter_expires_at_after")
		data["filter_expires_at_after"] = *filter.ExpiresAtAfter
	}
	if filter.ExpiresAtBefore != nil {
		conditions = append(conditions, "expires_at <= @filter_expires_at_before")
		data["filter_expires_at_before"] = *filter.ExpiresAtBefore
	}
	if filter.CreatedAt != nil {
		conditions = append(conditions, "created_at = @filter_created_at")
		data["filter_created_at"] = *filter.CreatedAt
	}
	if filter.CreatedAtAfter != nil {
		conditions = append(conditions, "created_at >= @filter_created_at_after")
		data["filter_created_at_after"] = *filter.CreatedAtAfter
	}
	if filter.CreatedAtBefore != nil {
		conditions = append(conditions, "created_at <= @filter_created_at_before")
		data["filter_created_at_before"] = *filter.CreatedAtBefore
	}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "code_id = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}

func generatedApplyListSearchFilter(filter verificationcodes.FilterList, data pgx.NamedArgs) string {
	if filter.SearchTerm == nil || *filter.SearchTerm == "" {
		return "TRUE"
	}
	// ILIKE pattern search.
	searchPattern := "%" + *filter.SearchTerm + "%"
	data["search_term"] = searchPattern
	var searchConditions []string
	searchConditions = append(searchConditions, "identifier ILIKE @search_term")
	searchConditions = append(searchConditions, "purpose ILIKE @search_term")
	if len(searchConditions) == 0 {
		return "TRUE"
	}
	return strings.Join(searchConditions, " OR ")
}

// Ensure imports are used.
var _ = errors.New
var _ = fmt.Sprintf
var _ slog.Logger
var _ pgxdb.Querier
var _ fop.Order
