//go:build e2e

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gopernicus/gopernicus/core/testing/fixtures"
	"github.com/gopernicus/gopernicus/infrastructure/cryptids"
	"github.com/gopernicus/gopernicus/infrastructure/testing/testhttp"
)

// Ensure imports are used.
var (
	_ = assert.Equal
	_ = require.NoError
	_ = cryptids.GenerateID
)

func TestGeneratedAPIKey_Create(t *testing.T) {
	_, _, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())
	// TODO: Set authentication if routes require it.
	// client.SetBearerToken(token)

	testUniqueID, err := cryptids.GenerateID()
	require.NoError(t, err)
	_ = testUniqueID

	body := map[string]any{
		"name":         "e2e_test_name_" + testUniqueID,
		"key_prefix":   "e2e_test_key_prefix_" + testUniqueID,
		"key_hash":     "e2e_test_key_hash_" + testUniqueID,
		"record_state": "active",
	}

	resp := client.Post(t, "/api-keys", body)
	resp.RequireStatus(t, 201)

	createdID := resp.String(t, "api_key_id")
	assert.NotEmpty(t, createdID)

	// Verify via GET.
	getResp := client.Get(t, "/api-keys/{api_key_id}")
	getResp.RequireStatus(t, 200)
	assert.Equal(t, createdID, getResp.String(t, "api_key_id"))
}

func TestGeneratedAPIKey_Get(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestAPIKeyWithDefaults(t, ctx, db)

	t.Run("found", func(t *testing.T) {
		resp := client.Get(t, "/api-keys/{api_key_id}")
		resp.RequireStatus(t, 200)
		assert.Equal(t, created.APIKeyID, resp.String(t, "api_key_id"))
	})

	t.Run("not found", func(t *testing.T) {
		resp := client.Get(t, "/api-keys/{api_key_id}")
		resp.RequireStatus(t, 404)
	})
}

func TestGeneratedAPIKey_List(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	for i := 0; i < 3; i++ {
		fixtures.CreateTestAPIKeyWithDefaults(t, ctx, db)
	}

	resp := client.Get(t, "/api-keys")
	resp.RequireStatus(t, 200)
	assert.GreaterOrEqual(t, resp.DataLen(t), 3)
}

func TestGeneratedAPIKey_Update(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestAPIKeyWithDefaults(t, ctx, db)

	body := map[string]any{
		"name": "updated_test_value",
	}

	resp := client.Put(t, "/api-keys/{api_key_id}", body)
	resp.RequireStatus(t, 200)

	// Verify via GET.
	getResp := client.Get(t, "/api-keys/{api_key_id}")
	getResp.RequireStatus(t, 200)
}

func TestGeneratedAPIKey_SoftDelete(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestAPIKeyWithDefaults(t, ctx, db)

	resp := client.Put(t, "/api-keys/{api_key_id}/delete", nil)
	resp.RequireStatus(t, 204)
}

func TestGeneratedAPIKey_Archive(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestAPIKeyWithDefaults(t, ctx, db)

	resp := client.Put(t, "/api-keys/{api_key_id}/archive", nil)
	resp.RequireStatus(t, 204)
}

func TestGeneratedAPIKey_Restore(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestAPIKeyWithDefaults(t, ctx, db)

	// Archive first, then restore.
	archiveResp := client.Put(t, "/api-keys/{api_key_id}/archive", nil)
	archiveResp.RequireStatus(t, 204)

	resp := client.Put(t, "/api-keys/{api_key_id}/restore", nil)
	resp.RequireStatus(t, 204)
}

func TestGeneratedAPIKey_Delete(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTestAPIKeyWithDefaults(t, ctx, db)

	resp := client.Delete(t, "/api-keys/{api_key_id}")
	resp.RequireStatus(t, 204)

	// Verify it's gone.
	getResp := client.Get(t, "/api-keys/{api_key_id}")
	getResp.AssertStatus(t, 404)

}
